mi6/ic-ui-kit

- lerna.json
With independent set, running a version check resulted in web-components and react packages being out of sync so fixed has been set. It is not possible to have different configs for different packages. Going forward all packages will have the same version number. Even if a package has not been updated, a version bump will be triggered and recorded in the changelog.
N/A
> fix(root): updated version scope in lerna from independent to fixed

- package-lock.json
- package.json
Downgraded lerna back to 4.0.0 to fix conflicting peer dependencies
> ci(root): fixed conflicting peer dependancies

- audit-ci.json
- package-lock.json
- package.json
- packages/web-components/package-lock.json
- packages/web-components/package.json
updates lerna, commitlint and mdx packages to fix vulnerabilities and removes items from allowlist
#41
> chore(root): fixes vulnerabilities highlighted by npm audit

- packages/web-components/src/components/ic-link/ic-link.tsx
- packages/web-components/src/components/ic-link/readme.md
Add documentation for router-item slot in ic-link
#108
> docs(web-components): add documentation for router-item slot in ic-link

- packages/web-components/package-lock.json
- packages/web-components/package.json
Rolls back mdx/react package to v1.6.22 to fix issue with Storybook docs tab not loading
#117
> chore(web-components): roll back mdx react package

- TESTING.md
This doc is related to testing with Jest in particular. It covers topics such as installation & testing with the shadow DOM
#39
> Add docs for testing with Jest

- .github/workflows/ic-ui-kit-main.yml
Reverted back to 2.0.0 version due to publish version error and CHANGELOG not updating. Updated deploy script. Tested using a local registry
N/A
> revert(root): reverted back to 2.0.0 commit due to incorrect versioning

- packages/web-components/src/components/ic-breadcrumb/ic-breadcrumb.css
- packages/web-components/src/components/ic-button/ic-button.css
- packages/web-components/src/components/ic-card/ic-card.css
- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
- packages/web-components/src/components/ic-footer-link-group/ic-footer-link-group.css
- packages/web-components/src/components/ic-footer-link/ic-footer-link.css
- packages/web-components/src/components/ic-input-component-container/ic-input-component-container.css
- packages/web-components/src/components/ic-link/ic-link.css
- packages/web-components/src/components/ic-menu/ic-menu.css
- packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css
- packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
- packages/web-components/src/components/ic-radio-option/ic-radio-option.css
- packages/web-components/src/components/ic-search-bar/ic-search-bar.spec.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-select/ic-select.css
- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
- packages/web-components/src/components/ic-tab-group/ic-tab-group.css
- packages/web-components/src/components/ic-tab/ic-tab.css
- packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
- packages/web-components/src/global/variables.css
Develop to main for a release. Should be 2.0.0 -> 2.1.0-beta.0 once published
N/A
> Latest components release

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
> Update changelogs on main

- packages/react/package-lock.json
- packages/web-components/package-lock.json
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
Add transparent border-bottom to top nav for high contrast
#89
> Add transparent border-bottom to top nav for high contrast

- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-checkbox-group/__snapshots__/ic-checkbox-group.spec.ts.snap
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.stories.mdx
- packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx
- packages/web-components/src/components/ic-checkbox/readme.md
- packages/web-components/src/utils/helpers.ts
Fixes issue where incorrect data could potentially be posted on form submit.
Also gives more meaningful names to checkbox groups in storybook examples
#148
> fix(web-components): fixes issue with nested input values

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/auto-add-new-issues-to-project.yml
Changed trigger criteria as actual deployments weren't being detected
#15
> fix(root): changed trigger criteria

- package-lock.json
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
Removed nested css media queries to make code easier to read
#166
> style(web-components): removed nested css queries

- .github/workflows/welcome-new-contributors.yml
Transferred workflow to welcome new contributors from ic-design-system to the ui kit
#171
> feat(root): added workflow to welcome contributors

- .github/workflows/add-qa-link-to-issues.yml
Added check to stop workflow running when the PR comes from a fork
> fix(root): added condition to workflow

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Update CHANGELOGs on main branch. The CHANGELOGs on main are referenced in public READMEs so need to be manually updated after a newly published UI Kit. 
N/A
> Updated CHANGELOGs

- packages/web-components/src/components/ic-back-to-top/__snapshots__/ic-back-to-top.spec.tsx.snap
- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.spec.tsx
- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.tsx
Fixes positioning so that it no longer overlaps ic-footer
#197
> fix(web-components): fixes back to top positioning

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/welcome-new-contributors.yml
Changing triggering logic to be more specific to not trigger workflows incorrectly
> fix(root): fixed triggering of workflows incorrectly

- packages/web-components/src/components/ic-loading-indicator/__snapshots__/ic-loading-indicator.spec.ts.snap
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.spec.ts
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.tsx
Fixes console error when updating progress prop for linear determinate variant.
Also improves code coverage in unit tests as was below 80%
#210
> fix(web-components): fixes console error in linear determinate variant

- .github/workflows/ic-ui-kit-main.yml
Updated action to publish which includes pushing tags so github actions can push tags to repo without having to temporarily remove permissions
N/A
> chore(root): updated actions to push tags to repo

- audit-ci.json
- packages/web-components/src/components/ic-menu/ic-menu.tsx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.e2e.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Added the ability to submit a search with highlighted options via keyboard nav, and added ability to type spaces into searchbar
#129 
[#174 in ic-design-system](https://github.com/mi6/ic-design-system/issues/174)
> fix(web-components): fixed issues with search bar

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Regenerated CHANGELOGs which were not updated correctly as part of the publishing step. Changelog have been manually generated using release check command. 
N/A
> [all] - Manually updated changelogs

- packages/web-components/src/components/ic-menu/ic-menu.tsx
Update menu to be >= so that select is scrollable
> fix(web-components): update menu to be >= so that select is scrollable

- packages/docs/README.md
Removes last updated entry from readme to avoid confusion. This is no longer required as docs package now auto updates on publish
> chore(docs): removes last updated date from readme

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
> Changelogs

- packages/react/src/stories/ic-search-bar.stories.mdx
- packages/react/src/stories/ic-text-field.stories.mdx
Fixes component docs in react storybook for searchbar and textfield
> fix(react): fixes react storybook docs

- packages/react/src/stories/ic-search-bar.stories.mdx
- packages/web-components/src/components/ic-menu/ic-menu.tsx
- packages/web-components/src/components/ic-search-bar/__snapshots__/ic-search-bar.spec.ts.snap
- packages/web-components/src/components/ic-search-bar/ic-search-bar.spec.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.stories.mdx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Fixes issues with updating search bar options when results are provide from an external source. In particular, when setting empty options, for no results, as this was causing browser to hang
No longer incorrectly displays "no results found" message when options not set and disableFilter is enabled
Adds react story to show external filtering for searchbar
#297
> Fixes issues when using external filtering to update searchbar options

- CHANGELOG.md
- lerna.json
- packages/docs/CHANGELOG.md
- packages/docs/package.json
- packages/fonts/CHANGELOG.md
- packages/fonts/package-lock.json
- packages/fonts/package.json
- packages/react/CHANGELOG.md
- packages/react/package-lock.json
- packages/react/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package-lock.json
- packages/web-components/package.json
- packages/web-components/src/components/ic-select/ic-select.css
- packages/web-components/src/components/ic-text-field/ic-text-field.css
- packages/web-components/src/components/ic-text-field/ic-text-field.stories.mdx
Regenerated changelogs due to issue with initial release. 
N/A
> [all]: regenerated change logs from new release

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Updated change logs to include 2.1.0-beta.4 & 2.1.0-beta.5
N/A
> Develop -> Main: Updated changelogs to include 2.1.0-beta.5

- .github/workflows/check-pr-target.yml
Prevents raising a PR into main unless source is develop
> ci(root): adds check for PR merge target

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Regenerated CHANGELOGs for 2.1.0-beta.7
N/A
> [UI Kit]: Regenerated CHANGELOGs

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Update CHANGELOGs for 2.1.0-beta.7 release
N/A
> [Release]: Updated CHANGELOG: Develop > Main

- packages/react/package-lock.json
- packages/react/package.json
Rolls back React Storybook to v6.5.15 due to what appears to be bug in latest 6.5.16
> fix(react): Fixes React Storybook not running

- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx
- packages/web-components/src/utils/helpers.ts
Add e2e tests to a new job in the pipeline (for branches, develop and main) to run simultaneously with other tests. 
Add lint and prettier to static analysis job (for branches, develop and main).
Updated some files using prettier:fix due to errors.
#362
> 362 GitHub actions add e2e tests to the build pipeline

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/ic-ui-kit-branches.yml
Add react storybook to deploy step and add react link to PR message.
#377
> build(root): add react storybook to deploy step

- .github/workflows/delete-gh-pages-folder.yml
Add action to delete gh-pages branches when branch is deleted from ui-kit
#387
> chore(root): add action to delete gh-pages branches

- packages/web-components/package-lock.json
- packages/web-components/src/components/ic-link/ic-link.css
Removed unecessary hc outline that was causing flickering when the link is focused
#371
> fix(web-components): fixed flickering link hovering

- packages/react/.storybook/main.js
- packages/web-components/.storybook/main.js
Disable telemetry for web-components and react storybook.
#400
> 400 configure storybook to stop sending telemetry data

- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
Add npm audit to all branches, develop and main
#419
> Add npm audit to all workflows

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
> Fix changelogs

- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.css
- packages/web-components/src/components/ic-back-to-top/readme.md
- packages/web-components/src/components/ic-classification-banner/ic-classification-banner.css
- packages/web-components/src/components/ic-classification-banner/readme.md
- packages/web-components/src/components/ic-menu/ic-menu.css
- packages/web-components/src/components/ic-menu/readme.md
- packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css
- packages/web-components/src/components/ic-navigation-group/readme.md
- packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
- packages/web-components/src/components/ic-navigation-item/readme.md
- packages/web-components/src/components/ic-navigation-menu/ic-navigation-menu.css
- packages/web-components/src/components/ic-navigation-menu/readme.md
- packages/web-components/src/components/ic-page-header/ic-page-header.css
- packages/web-components/src/components/ic-page-header/readme.md
- packages/web-components/src/components/ic-search-bar/ic-search-bar.css
- packages/web-components/src/components/ic-search-bar/readme.md
- packages/web-components/src/components/ic-select/ic-select.css
- packages/web-components/src/components/ic-select/readme.md
- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
- packages/web-components/src/components/ic-side-navigation/readme.md
- packages/web-components/src/components/ic-tooltip/ic-tooltip.css
- packages/web-components/src/components/ic-tooltip/readme.md
- packages/web-components/src/global/variables.css
- packages/web-components/src/z-index.stories.mdx
Adds a base z-index value that is used to calculate z-index of all elements. Values can also be overridden at the component level
#391
> fix(web-components): updates z-index values for components

- packages/fonts/package-lock.json
- packages/fonts/package.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web-components/package-lock.json
- packages/web-components/package.json
Updates webpack version to 5.76 to fix audit failure
> Update webpack version to fix vulnerability

- packages/web-components/package-lock.json
- packages/web-components/package.json
Updates loki version to apply fix for visual tests not running in ci
> chore(web-components): updates loki version

- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
- .github/workflows/update-visual-regression-tests.yml
Adds logging of Chromium version in use for visual tests in ci
> chore(root): adds logging of chromium version

- packages/web-components/src/components/ic-button/__snapshots__/ic-button.spec.ts.snap
- packages/web-components/src/components/ic-button/ic-button.spec.ts
- packages/web-components/src/components/ic-divider/__snapshots__/ic-divider.spec.ts.snap
- packages/web-components/src/components/ic-divider/ic-divider.spec.ts
- packages/web-components/src/components/ic-footer-link/ic-footer-link.spec.ts
- packages/web-components/src/components/ic-page-header/__snapshots__/ic-page-header.spec.ts.snap
- packages/web-components/src/components/ic-page-header/ic-page-header.spec.ts
- packages/web-components/src/components/ic-radio-group/__snapshots__/ic-radio-group.spec.ts.snap
- packages/web-components/src/components/ic-radio-group/ic-radio-group.spec.ts
- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.spec.ts
- packages/web-components/src/components/ic-tab-context/__snapshots__/ic-tab-context.spec.ts.snap
- packages/web-components/src/components/ic-tab-context/ic-tab-context.spec.ts
- packages/web-components/src/components/ic-toast-region/__snapshots__/ic-toast-region.spec.ts.snap
- packages/web-components/src/components/ic-toast-region/ic-toast-region.spec.ts
- packages/web-components/src/components/ic-top-navigation/__snapshots__/ic-top-navigation.spec.ts.snap
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.spec.ts
Adds coverage for missing components:
- ic-divider
- ic-tab-context
- ic-toast-region
Improves coverage for:
- ic-button
- ic-footer-link
- ic-page-header
- ic-radio-group
- ic-tab-panel
- ic-top-navigation
#441
> test(web-components): improves test coverage

- packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.tsx
- packages/web-components/src/components/ic-menu/ic-menu.tsx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-select/ic-select.tsx
- packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
- packages/web-components/src/utils/helpers.ts
Fixes console errors seen in build and running of guidance site
#534
> fix(web-components): fixes console errors

- package-lock.json
- packages/web-components/package-lock.json
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.css
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
Update popover to display none instead of opacity 0.
> Popover fixes

- .github/workflows/ic-ui-kit-main.yml
- .github/workflows/ic-ui-kit-release.yml
Automate release check, create develop -> main PR with version number change, and trigger design system workflow when main workflow finishes
384 in design system
> ci(root): automate release check, develop -> main PR and starting design system workflow

- packages/react/package-lock.json
- packages/web-components/package-lock.json
- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.css
- packages/web-components/src/components/ic-button/ic-button.css
- packages/web-components/src/components/ic-card/ic-card.css
- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
- packages/web-components/src/components/ic-chip/ic-chip.css
- packages/web-components/src/components/ic-data-entity/ic-data-entity.css
- packages/web-components/src/components/ic-data-row/ic-data-row.css
- packages/web-components/src/components/ic-divider/ic-divider.css
- packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.css
- packages/web-components/src/components/ic-input-component-container/ic-input-component-container.css
- packages/web-components/src/components/ic-menu/ic-menu.css
- packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css
- packages/web-components/src/components/ic-navigation-menu/ic-navigation-menu.css
- packages/web-components/src/components/ic-page-header/ic-page-header.css
- packages/web-components/src/components/ic-radio-option/ic-radio-option.css
- packages/web-components/src/components/ic-search-bar/ic-search-bar.css
- packages/web-components/src/components/ic-select/ic-select.css
- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
- packages/web-components/src/components/ic-status-tag/ic-status-tag.css
- packages/web-components/src/components/ic-step/ic-step.css
- packages/web-components/src/components/ic-switch/ic-switch.css
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
- packages/web-components/src/global/variables.css
https://github.com/mi6/ic-ui-kit/pull/549
Tell us, in a few words, added a need css variable of 0.063rem to replace occurences throughout app and make changing the spacing easier in future.
> Create spacing variable 0.063rem #451

- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.spec.tsx
- packages/web-components/src/components/ic-button/ic-button.spec.ts
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.e2e.ts
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.spec.ts
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.tsx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.e2e.ts
- packages/web-components/src/components/ic-radio-group/ic-radio-group.spec.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.e2e.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.spec.ts
- packages/web-components/src/components/ic-select/ic-select.spec.tsx
- packages/web-components/src/components/ic-skeleton/ic-skeleton.spec.ts
- packages/web-components/src/components/ic-step/ic-step.spec.ts
- packages/web-components/src/components/ic-stepper/ic-stepper.e2e.ts
- packages/web-components/src/components/ic-stepper/ic-stepper.spec.ts
- packages/web-components/src/components/ic-tab-context/ic-tab-context.e2e.ts
- packages/web-components/src/components/ic-tab-context/ic-tab-context.spec.ts
- packages/web-components/src/components/ic-theme/ic-theme.spec.tsx
- packages/web-components/src/components/ic-toast/ic-toast.spec.ts
- packages/web-components/src/components/ic-toast/ic-toast.tsx
- packages/web-components/src/components/ic-tooltip/ic-tooltip.spec.ts
Fixes console warnings and issues with worker processes left running.
#602
> fix(web-components): fixes warnings and errors in unit tests

- audit-ci.json
Added GHSA-f9xv-q969-pqx4 to allowlist to allow audit to pass
N/A
> feat(root): added to allowlist for audit

- packages/react/package-lock.json
- packages/react/package.json
Adds license to React package.json
https://github.com/mi6/ic-ui-kit/issues/415
> docs(react): adds license to react package.json

- .github/workflows/ic-ui-kit-main.yml
Updated github action step indentation within yml file. This has removed the error.
N/A
> fix(root): updated github action for release

- .github/workflows/ic-ui-kit-main.yml
Github action change to fix release deployment
N/A
> develop > main fix(root): updated github action for release

- packages/react/src/stories/ic-checkbox.stories.mdx
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.e2e.ts
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.spec.ts
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.stories.mdx
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.tsx
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.types.ts
- packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx
Changed icChange in `ic-checkbox-group` to return an array of checked `ic-checkbox`'s, so that users can easily retrieve values from the components when they are updated
#464
> feat(web-components): changed event.detail for ic-checkbox icChange

- packages/web-components/src/components/ic-menu/ic-menu.tsx
changed the ic-menu to focus the select when closed due to keyboard input
#455
> fix(web-components): fixed focusing of select on menu close

- package-lock.json
- packages/web-components/src/components/ic-menu-item/ic-menu-item.css
- packages/web-components/src/components/ic-menu/ic-menu.tsx
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.css
- packages/web-components/src/components/ic-search-bar/ic-search-bar.e2e.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-select/__snapshots__/ic-select.e2e.ts.snap
- packages/web-components/src/components/ic-select/__snapshots__/ic-select.spec.tsx.snap
- packages/web-components/src/components/ic-select/ic-select.e2e.ts
- packages/web-components/src/components/ic-select/ic-select.spec.tsx
- packages/web-components/src/components/ic-select/ic-select.stories.mdx
- packages/web-components/src/components/ic-select/ic-select.tsx
Updated Searchable so the input value is not updated when highlighting options within the ic-menu. icOptionSelect and icChange are only emitted once the option and been selected. This update also allows the input value to be updated outside of input or menu selection.
Added onBlur to host close menu
PLEASE NOTE: The UX for Searchable select has slightly changed:
- Before: When highlighting menu options, the value in the input would reflect the highlighted option and trigger icChange.
- After: When highlighting menu options, the value in the input is no longer updated until `Enter` is pressed. `icChange` is emitted once the value is updated.
#525
> fix(web-components): updated select searchable to update emitted events

- packages/web-components/src/components/ic-menu/ic-menu.tsx
Reverting blur functionality. 
N/A
> fix(web-components): updating blur functionality on ic-menu

- packages/web-components/src/components/ic-menu/__snapshots__/ic-menu.spec.tsx.snap
- packages/web-components/src/components/ic-menu/ic-menu.spec.tsx
Isolated unit tests for ic-menu.
#617
> 617 ic menu review and create unit tests

- .github/workflows/ic-ui-kit-release.yml
Add git stash to automated release step and remove commit message so that it can successfully create a develop -> main PR
#710
> ci(root): add git stash to automated release step and remove commit message

- packages/web-components/src/components/ic-menu/ic-menu.spec.tsx
Fix lint errors in ic-menu spec tests to fix the lint errors on develop
> refactor(web-components): fix lint errors in ic-menu spec tests

- packages/react/package-lock.json
- packages/react/src/stories/ic-select.stories.mdx
- packages/web-components/package-lock.json
- packages/web-components/src/components/ic-select/ic-select.stories.mdx
Add Storybook playgrounds for default select and select searchable. Update package-lock in react & web-components packages
#665
> docs(web-components): add Storybook playgrounds for default select and select searchable

- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-pagination/readme.md
added changes that were being flagged as missing by build pipeline
> fix(web-components): fixed build issue

- packages/react/src/stories/ic-radio-group.stories.mdx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-radio-group/ic-radio-group.e2e.ts
- packages/web-components/src/components/ic-radio-group/ic-radio-group.spec.ts
- packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.mdx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.types.ts
- packages/web-components/src/components/ic-radio-group/readme.md
- packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
Update icChange in radio to emit the selected radio and optionally the text from the additional field.
#673
> 673 update icchange detail for ic radio group

- packages/web-components/src/components/ic-menu/ic-menu.tsx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.e2e.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.spec.ts
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-select/__snapshots__/ic-select.e2e.ts.snap
- packages/web-components/src/components/ic-select/__snapshots__/ic-select.spec.tsx.snap
- packages/web-components/src/components/ic-select/ic-select.e2e.ts
- packages/web-components/src/components/ic-select/ic-select.spec.tsx
- packages/web-components/src/components/ic-select/ic-select.tsx
Review and changes to the e2e and unit tests for `ic-select` and `ic-search-bar`
#660
> 660 review select searchbar tests

- packages/react/package-lock.json
- packages/react/package.json
- packages/react/src/react-component-lib/createComponent.tsx
- packages/react/src/react-component-lib/createOverlayComponent.tsx
- packages/react/src/react-component-lib/utils/case.ts
- packages/react/src/react-component-lib/utils/index.tsx
- packages/react/src/stories/ic-chip.stories.mdx
- packages/web-components/package-lock.json
- packages/web-components/package.json
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-pagination-item/ic-pagination-item.tsx
- packages/web-components/src/components/ic-pagination/ic-pagination.tsx
- packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.types.ts
- packages/web-components/src/components/ic-select/ic-select.tsx
- packages/web-components/src/components/ic-text-field/ic-text-field.tsx
- packages/web-components/stencil.config.ts
Upgrade stencil to V3 and stencil react output target to 0.4.0, and updated types coming from
interface to come from utils/types to fix build errors from V3 upgrade
https://github.com/mi6/ic-ui-kit/issues/386
> Stencil v3

- .github/workflows/ic-ui-kit-branches.yml
The skip build functionality requires fine tuning but until that work is completed, it has been removed from the feature build action
N/A
> chore(root): temporarily removing skip build func

- packages/react/src/stories/ic-tooltip.stories.mdx
- packages/web-components/src/components/ic-tooltip/ic-tooltip.css
- packages/web-components/src/components/ic-tooltip/ic-tooltip.stories.mdx
Updates to styling to apply border for better visibility on dark background. Also modifies arrow to match latest Figma designs.
#223
> feat(web-components): updates to tooltip styling

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Regenerated changelogs are 2.1.0-beta.16 release
N/A
> [changelogs]: 2.1.0-beta.16 changelogs updated

- .github/workflows/ic-ui-kit-release.yml
- audit-ci.json
Update automation to create PR with api
> fix(root): update automation to create PR with api

- .github/workflows/ic-ui-kit-branches.yml
Added branch name extraction step due to PR trigger setting ref_name to <ticket_number>/merge
N/A
> fix(root): added branch name extraction step

- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
Update navigation items to display slotted labels on menu open for mobile
#775
> fix(web-components): update navigation items to display slotted label

- packages/web-components/src/components/ic-search-bar/ic-search-bar.stories.mdx
- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Update search bar to correctly show no results found state when external filtering is used but not loading. Added story to show this.
#849
> fix(web-components): update search bar to correctly show no results found

- packages/react/src/stories/ic-top-navigation.stories.mdx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.mdx
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx
- packages/web-components/src/components/ic-top-navigation/readme.md
- packages/web-components/src/components/ic-top-navigation/test/a11y/ic-top-navigation.test.a11y.ts
- packages/web-components/src/components/ic-top-navigation/test/basic/__snapshots__/ic-top-navigation.spec.ts.snap
- packages/web-components/src/components/ic-top-navigation/test/basic/ic-top-navigation.e2e.ts
- packages/web-components/src/components/ic-top-navigation/test/basic/ic-top-navigation.spec.ts
Update short title to short app title and wrap short app title in h1 tag.
Responding to comments made in #901 after it was merged.
#853
> 853 update short title to short app title

- CONTRIBUTING.md
Added stencil style guide to contribution
Edit to contribution guide
#507
> docs(root): change to contribution guide

- README.md
local build guidance added to readme
#864
> docs(root): local build guidance

- CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Updated changelogs to reflect beta.18 release. 
N/A
> Develop > Main: Updated changelogs

- packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx
- packages/web-components/src/components/ic-menu-item/test/basic/ic-menu-item.spec.ts
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
> internal issue 2405

- .github/workflows/ic-ui-kit-main.yml
- lerna.json
Updated lerna config to reduce CLI command within github action. Added fetch-depth on checkout action to fix changelog issue. Issue was lerna would not fetch all the commits and tags before updating the changelogs.
Resolved with: https://github.com/lerna/lerna/issues/2542
Updated lerna version so it's in sync with version number in the packages directory (package.json).
Removed HUSKY_SKIP_HOOKS as this is doing the same things as --no-commit-hooks
Closes #923
> fix(root): updated lerna config and github action

- packages/web-components/src/components/ic-date-input/ic-date-input.stories.mdx
- packages/web-components/src/components/ic-date-input/ic-date-input.tsx
- packages/web-components/src/components/ic-date-input/test/basic/ic-date-input.e2e.ts
Now supports setting value to null, empty string and undefined.
NA
> fix(web-components): fixes issue setting date input value to null

- packages/web-components/src/components/ic-accordion/ic-accordion.tsx
- packages/web-components/src/components/ic-accordion/test/basic/__snapshots__/ic-accordion.spec.ts.snap
update labelledby ids due to shadowDOM boundaries
n/a
> fix(web-components): update labelledby ids

- packages/docs/package.json
Updated docs version to publish to NPM with empty state API
N/A
> docs(docs): [ci skip] updated docs version for release

- packages/react/package.json
Update side effects to include css files for webpack bundling
#803
> chore(react): update side effects to include css files

- packages/web-components/src/components/ic-select/ic-select.tsx
- packages/web-components/src/components/ic-select/test/basic/__snapshots__/ic-select.spec.tsx.snap
- packages/web-components/src/components/ic-select/test/basic/ic-select.e2e.ts
- packages/web-components/src/components/ic-select/test/basic/ic-select.spec.tsx
Check and deduplicate IcMenuOptions and log a warning describing the removed item
#595
> fix(web-components): deduplicate ic-select option values

- .github/pull_request_template.md
> feat(root): add new PR checklist

- .github/workflows/ic-ui-kit-release.yml
Update PR message to cut version in the right place now that beta has been removed
> chore(root): update PR message to cut version in the right place

- .eslintrc.js
- .gitignore
- packages/docs/docs.json
Remove docs.json from git ignore and update lint rules so that docs version gets updated correctly.
#1061
> 1061 ukicdocs does not get updated when publishing to npm

- .gitignore
Add back docs.json to gitignore
> chore(root): add back docs.json to gitignore

- .github/workflows/ic-ui-kit-main.yml
- .gitignore
Update main workflow to revert docs.json timestamp changes by checking out file
#1061
> chore(root): update main workflow to revert docs.json timestamp changes

- package.json
Updated husky script due to typo within package.json.
N/A
> fix(root): updated husky npm script

- packages/web-components/package-lock.json
- packages/web-components/package.json
Upgrades Stencil version to 4.3
#1131
> chore(web-components): upgrade to Stencil 4.3

- packages/web-components/src/components/ic-card/ic-card.css
fixes issue where card width would change when card expands\collapses despite a width being set
#538
> fix(web-components): fixes card width changing on expand

- .github/workflows/ic-ui-kit-branches.yml
No longer runs actions when PR edited. To prevent unnecessary runs, when checklist box ticked
N/A
> ci(root): update to branch actions

- packages/web-components/src/components/ic-search-bar/test/basic/ic-search-bar.e2e.ts
- packages/web-components/src/components/ic-select/test/basic/ic-select.e2e.ts
- packages/web-components/src/components/ic-typography/test/basic/ic-typography.e2e.ts
Updated intermittent ic-search-bar test for loading state.
Updated ic-typography e2e test
Updated intermittent ic-select e2e test
N/A
> test(web-components): updated ic-search/ic-typography e2e test

- audit-ci.json
Adds GHSA-7fh5-64p2-3v2j to whitelist as requires an upgrade to storybook v7
N/A
> chore(root): adds postcss to audit whitelist

- audit-ci.json
Defers issues in allowlist where the fix requires breaking change package upgrades
> docs(root): updates audit-ci to stop build failing

- audit-ci.json
- package-lock.json
- packages/react/package-lock.json
- packages/react/package.json
- packages/web-components/package-lock.json
- packages/web-components/package.json
Updates babel packages to fix critical vulnerability.
Also removes some items from allowlist that are no longer required
N/A
> Audit fix for babel

- packages/docs/docs.json
- packages/web-components/src/components/ic-select/readme.md
- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
- updates docs with some missing info
- fixes lint error in side nav (duplicate selector)
- corrects readme.md for ic-select
N/A
> Adds missing docs info and lint fix

- .github/pull_request_template.md
Add item to checklist on PR template to ensure the docs package always gets checked and any changes are committed.
n/a
> docs(root): add item about docs changes to PR checklist

- audit-ci.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
fixes audit issue and increases expiry on allowed entries
N/A
> npm audit fix

- packages/react/src/stories/ic-switch.stories.mdx
- packages/web-components/src/components/ic-switch/ic-switch.tsx
Added a watch to checked prop so that switch updates as state updates.
#1039
> 1039 ic-switch is not controllable

- packages/docs/docs.json
- packages/web-components/src/components/ic-badge/ic-badge.tsx
- packages/web-components/src/components/ic-badge/readme.md
Added the `@slot` at the top of badge file to add slot info for badge-icon to docs.
> Badge missing slots

- audit-ci.json
Adds audit exception for axios as version won't update
N/A
> chore(root): adds audit exception to fix build

- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.tsx
- packages/web-components/src/components/ic-tab-context/test/basic/__snapshots__/ic-tab-context.spec.ts.snap
- packages/web-components/src/components/ic-tab-context/test/basic/ic-tab-context.e2e.ts
- packages/web-components/src/components/ic-tab-group/ic-tab-group.tsx
fixes issues selecting tabs on smaller viewports
#1254
> fix(web-components): fixes responsive tabs selection issue

- .github/workflows/ic-ui-kit-develop.yml
updated develop branch gh actions to include qa react storybook
#1098
> ci(root): adds react storybook to develop deployment

- packages/docs/docs.json
- packages/web-components/src/components/ic-accordion-group/test/basic/ic-accordion-group.e2e.ts
- packages/web-components/src/components/ic-accordion-group/test/basic/ic-accordion-group.spec.ts
- packages/web-components/src/components/ic-badge/ic-badge.tsx
- packages/web-components/src/components/ic-data-row/test/a11y/ic-data-row.test.a11y.ts
- packages/web-components/src/components/ic-footer/test/a11y/ic-footer.test.a11y.ts
- packages/web-components/src/components/ic-horizontal-scroll/test/a11y/ic-horizontal-scroll.test.a11y.ts
- packages/web-components/src/components/ic-navigation-group/test/a11y/ic-navigation-group.test.a11y.ts
- packages/web-components/src/components/ic-navigation-item/test/a11y/ic-navigation-item.test.a11y.ts
- packages/web-components/src/components/ic-pagination/test/a11y/ic-pagination.test.a11y.ts
- packages/web-components/src/components/ic-pagination/test/basic/__snapshots__/ic-pagination.spec.ts.snap
- packages/web-components/src/components/ic-pagination/test/basic/ic-pagination.spec.ts
- packages/web-components/src/components/ic-popover-menu/test/basic/ic-popover-menu.e2e.ts
- packages/web-components/src/components/ic-top-navigation/test/a11y/ic-top-navigation.test.a11y.ts
Added jest mock functions to unit, e2e and a11y tests to stop console warnings and errors.
#1205
> 1205 console warning/errors when running tests

- packages/web-components/src/components/ic-menu/ic-menu.tsx
Added comment to code regarding testing both Floating UI and Popper JS behaviour
#1099
N/A
> docs(web-components): added comment to code relating to floating ui and popper js

- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.css
- packages/web-components/src/components/ic-button/ic-button.css
- packages/web-components/src/components/ic-card/ic-card.css
- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
- packages/web-components/src/components/ic-chip/ic-chip.css
- packages/web-components/src/components/ic-data-entity/ic-data-entity.css
- packages/web-components/src/components/ic-data-row/ic-data-row.css
- packages/web-components/src/components/ic-input-component-container/ic-input-component-container.css
- packages/web-components/src/components/ic-menu/ic-menu.css
- packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css
- packages/web-components/src/components/ic-navigation-menu/ic-navigation-menu.css
- packages/web-components/src/components/ic-radio-option/ic-radio-option.css
- packages/web-components/src/components/ic-search-bar/ic-search-bar.css
- packages/web-components/src/components/ic-select/ic-select.css
- packages/web-components/src/components/ic-status-tag/ic-status-tag.css
- packages/web-components/src/components/ic-step/ic-step.css
- packages/web-components/src/components/ic-switch/ic-switch.css
- packages/web-components/src/components/ic-tab-group/ic-tab-group.css
- packages/web-components/src/components/ic-tooltip/ic-tooltip.css
- packages/web-components/src/global/variables.css
adds new style token for border width
adds new style token to prevent rounding of border to 1px
#1040
> perf(web-components): adds new style token for border width

- packages/web-components/src/components/ic-search-bar/test/basic/ic-search-bar.e2e.ts
- packages/web-components/src/components/ic-select/test/basic/ic-select.e2e.ts
- packages/web-components/src/components/ic-side-navigation/test/basic/ic-side-navigation.e2e.ts
Update search bar and select e2e tests to not intermittently fail.
Tested by running e2e tests in the ci 25 times and no failures - https://github.com/mi6/ic-ui-kit/actions/runs/7129293190
#928
> test(web-components): update search bar and select e2e tests to not intermittently fail

- audit-ci.json
Updates audit expiry to 29th Jan
N/A
> chore(root): updates audit expiry

- package-lock.json
- packages/web-components/package-lock.json
Bumps the version of follow-redirects package in order to resolve audit issue
N/A
> Audit fix for follow-redirects package

- packages/web-components/.gitignore
- packages/web-components/package.json
- packages/web-components/stencil.config.ts
Enables auto-completion for web components in VS Code.
Requires configuring it in settings.json, (once published the path will be slightly different but this is what I used locally):
```json
{
"html.customData": ["../ic-ui-kit/packages/web-components/vscode-data.json"]
}
```
Screenshots:
Follows https://stenciljs.com/docs/docs-vscode
Fixes https://github.com/mi6/ic-ui-kit/issues/1355
> docs(web-components): add vs-code webcomponent documentation

- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
Updated Cypress tests step to require check-updates to successfully pass.
N/A
N/A
>  ci(root): updated github action deps

- CONTRIBUTING.md
Changes to contribution guidance regarding testing with cypress.
#1270
> docs(root): change in contribution docs

- packages/canary-web-components/src/components/ic-data-table/readme.md
- packages/canary-web-components/src/components/ic-pagination-bar/readme.md
- packages/canary-web-components/stencil.config.ts
fixes readme.md files not being updated for canary components
N/A
> chore(canary-web-components): fixes readme.md files not being generated

- packages/react/cypress/support/commands.ts
- packages/react/cypress/support/index.ts
- packages/react/cypress/utils/a11y.ts
- packages/react/src/component-tests/IcAccordion/IcAccordion.cy.tsx
- packages/react/src/component-tests/IcAlert/IcAlert.cy.tsx
- packages/react/src/component-tests/IcBackToTop/IcBackToTop.cy.tsx
- packages/react/src/component-tests/IcBadge/IcBadge.cy.tsx
- packages/react/src/component-tests/IcButton/IcButton.cy.tsx
- packages/react/src/component-tests/IcClassificationBanner/IcClassificationBanner.cy.tsx
- packages/react/src/component-tests/IcSelect/IcSelect.cy.tsx
- packages/react/src/component-tests/IcSelect/IcSelectSearchable.cy.tsx
- packages/react/src/component-tests/IcToast/IcToast.cy.tsx
- packages/react/src/component-tests/IcTopNavigation/IcTopNavigation.cy.tsx
Refactor of IcBadge cypress tests
#1418
> 1418 investigate icbadge cypress visual and a11y tests ci build failure

- .github/pull_request_template.md
Add SSR to PR checklist to ensure we test all major changes before release
> docs(root): add ssr to pr checklist

- audit-ci.json
increased dates on audit exceptions to fix failure
N/A
> chore(root): bumped dates to allow audit to pass

- CONTRIBUTING.md
Adds info to run `npm run build:all` into contributing.md
N/A
> docs(root): corrects info in contributing.md

- audit-ci.json
Changes date to 1st march as previous change not working
N/A
> chore(root): changes audit dates to fix build

- audit-ci.json
added audit exception for ip package version issue
https://github.com/advisories/GHSA-78xj-cgh5-2h22
> chore(root): add audit exception for ip

- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
Update path for cypress diff screenshots in github workflows for branches, develop and main
> chore(root): update path for cypress diff screenshots

- .github/workflows/ic-ui-kit-release.yml
Update the release check command in develop -> main workflow so that the PR description shows the react/web-components package updates
> chore(root): update the release check command in develop -> main workflow

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/ic-ui-kit-branches.yml
Add cypress diff screenshots and html report as comment on PR when cypress visual tests fail
#1438
> ci(root): add cypress diff screenshots and html report as comment on PR

- audit-ci.json
> chore(root): update audit ci dates

- packages/react/src/stories/ic-badge.stories.mdx
- packages/web-components/src/components/ic-badge/ic-badge.stories.mdx
- packages/web-components/src/components/ic-badge/ic-badge.tsx
- packages/web-components/src/components/ic-badge/test/basic/__snapshots__/ic-badge.spec.tsx.snap
Update badge to have default aria-label and add aria labels for icons in badges to add more context
Half of #1518
> 1518 badge screen reader improvements

- packages/react/package-lock.json
Updated IP package using `audit fix`
This ticket will fix vulnerabilities reported by dependabot:
- https://github.com/mi6/ic-ui-kit/pull/1542
- https://github.com/mi6/ic-ui-kit/pull/1541
N/A
> fix(react): updating packages

- packages/docs/docs.json
- packages/react/src/stories/ic-select.stories.mdx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-select/ic-select.stories.mdx
- packages/web-components/src/components/ic-select/ic-select.tsx
- packages/web-components/src/components/ic-select/readme.md
- packages/web-components/src/components/ic-select/test/basic/__snapshots__/ic-select.spec.tsx.snap
- packages/web-components/src/components/ic-select/test/basic/ic-select.spec.tsx
Adds icOpen and icClose events to icSelect component
#1388
> 1388 select open event

- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/update-cypress-visual-regression-tests.yml
- package.json
- Added caching to improve github efficiency
- Checkout docs file when generating cypress images
- Updates Cypress npm script for granular installation
N/A
N/A
> feat(root): updated github actions for cypress and feature builds

- packages/canary-web-components/src/components/ic-date-input/ic-date-input.css
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
Update date input calendar and clear to update appearance when focused to light variant
N/A
> fix(canary-web-components): update date input calendar and clear to update appearance

- audit-ci.json
- package-lock.json
- packages/web-components/package-lock.json
- packages/web-components/package.json
- upgrades version of loki
- removes some items from allowlist
- bumps dates to 1 month from today
> Fix audit issue

- .github/pull_request_template.md
- CHECKLIST.md
- CONTRIBUTING.md
- GLOSSARY.md
Update contributing.md to include more info on PR checklist and glossary of terms for props and slots names. Updated PR checklist to follow headings created in new checklist.md file.
#1229 and #1328
> docs(root): update contributing.md to include more info on PR checklist and glossary

- GLOSSARY.md
Update additional field slot description in glossary of terms
> docs(root): update additional field slot description in glossary

- packages/canary-react/src/stories/ic-date-picker.stories.mdx
Updated max width story due to styling on React components
N/A
N/A
> fix(canary-react): updated max width story

- packages/canary-react/package-lock.json
- packages/canary-react/src/stories/ic-date-picker.stories.mdx
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Package updates identified by dependabot
Updated canary react date picker code snippet
N/A
N/A
> Package updates identified via dependabot

- packages/react/src/stories/ic-select_(searchable).stories.mdx
- packages/react/src/stories/ic-select_(single).stories.mdx
Noticed small issues with the structure of the select React stories and missing imports.
N/A
> Small select Storybook issues

- .github/workflows/scorecards.yml
- README.md
Add openssf scorecard to github workflows and add badge to readme file
Covers half of #1215 - I will implement these same changes in the design system to cover the other half of the ticket once we're happy with this
> ci(root): add openssf scorecard to github workflows

- .github/workflows/scorecards.yml
Remove develop from scorecard.yml due to only the main branch being supported
N/A
> fix(root): remove develop from scorecard.yml

- .github/workflows/scorecards.yml
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Update scorecard.yml publish_results to false
N/A
> fix(root): update scorecard.yml publish_results to false

- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
- packages/canary-web-components/src/components/ic-date-picker/ic-date-picker.tsx
- packages/canary-web-components/src/components/ic-date-picker/story-data.ts
- packages/canary-web-components/src/components/ic-date-picker/test/basic/ic-date-picker.spec.ts
fixes issues with emitting of IcChange events when opening calendar & selecting\clearing dates
N/A
> fix(canary-web-components): fixes issues with icChange event

- packages/web-components/src/components/ic-dialog/ic-dialog.tsx
Small change to ic-dialog to prevent console errors
#1729
> fix(web-components): ic-dialog

- packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx
- packages/canary-react/src/component-tests/IcDatePicker/IcDatePicker.cy.tsx
- packages/canary-web-components/src/components.d.ts
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
- packages/canary-web-components/src/components/ic-date-input/test/basic/__snapshots__/ic-date-input.spec.tsx.snap
- packages/canary-web-components/src/components/ic-date-input/test/basic/ic-date-input.spec.tsx
- packages/canary-web-components/src/components/ic-date-picker/ic-date-picker.tsx
- packages/canary-web-components/src/components/ic-date-picker/story-data.ts
Changes the way in which icChange is emitted. It will still appear to be emitted from the ic-date-picker component, but is sent from the ic-date-input component by triggering a method in that.
This allows comparing against the previous value emitted & only emit if it has changed.
Also fixes issues in the ic-date-input unit tests.
N/A
> Date input emit icChange fix

- packages/canary-web-components/src/utils/helpers.ts
- packages/web-components/src/utils/helpers.ts
Add helper function for testing that waits for components to be hydrated and returns a promise
#293
> feat(web-components): add helper function for testing that waits for components to be hydrated

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/auto-add-new-issues-to-project.yml
- .github/workflows/delete-gh-pages-folder.yml
- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
- .github/workflows/ic-ui-kit-release.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/scorecards.yml
- .github/workflows/update-cypress-visual-regression-tests.yml
- .github/workflows/update-visual-regression-tests.yml
- .github/workflows/welcome-new-contributors.yml
Update all node- version references from 18 -> 20
#1606
> 1606 ic UI kit transition all workflow actions to run on node 20

- .github/workflows/deploy-storybook-only.yml
This github action is to deploy storybook only when required for further review and testing while the feature or bug is WIP.
N/A
N/A
> feat(root): new github action for deploying storybook

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/auto-add-new-issues-to-project.yml
- .github/workflows/check-pr-target.yml
- .github/workflows/check-tasks-completed.yml
- .github/workflows/delete-gh-pages-folder.yml
- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
- .github/workflows/ic-ui-kit-release.yml
- .github/workflows/run-cypress-tests.yml
- .github/workflows/update-cypress-visual-regression-tests.yml
- .github/workflows/update-visual-regression-tests.yml
- .github/workflows/welcome-new-contributors.yml
- README.md
Update github workflows to fix scorecard issues and remove scorecard badge from readme as we don't publish results so it won't ever have a valid repo url.
#1715
> chore(root): update github workflows to fix scorecard issues

- packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx
- packages/react/src/component-tests/IcRadio/IcRadioTestData.tsx
- packages/react/src/stories/ic-radio-group.stories.mdx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
- packages/web-components/src/components/ic-radio-group/test/basic/ic-radio-group.spec.ts
- packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
Fixes issues where slotted radio options change after initial load. Adds storybook examples and also Cypress tests for these cases. Full Cypress tests will be added by work to be done in #1794 
#1749
> Dynamically adding radio options

- .github/workflows/update-cypress-visual-regression-tests.yml
Updated Cypress VR action to include permissions and streamline steps.
N/A
N/A
> Updated Cypress Visual Regression action

- package-lock.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Fix audit errors in each package.
> Fix audit errors

- .github/workflows/ic-ui-kit-release.yml
Added `contents:write` within the github action to create the initial Develop > Main PR
N/A
N/A
> fix(root): updated permissions in release github action

- packages/web-components/src/global/variables.css
Changed date-picker z-index default value to make it appear above sticky page headers
> fix(web-components): changed date-picker z-index value

- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
- packages/web-components/src/components/ic-select/ic-select.tsx
- packages/web-components/src/utils/helpers.ts
There were some errors appearing in the console for users of the the ic-popover-menu and ic-select components, which are resolved in this PR.
In ic-popover, it is possible for `this.popperInstance` to be null rather than undefined. The fix in this PR prevents `.destroy()` being called on a null popper instance.
In ic-select, it is possible for `this.options` to be null. The fix in this PR prevents an error when trying to get the length of a null array.
Also, a fix to the `hasValidationStatus()` method, to prevent an issue when the validation message and status props are passed in as null or undefined into the ic-select. This was causing the ic-input-validation to displayed in the ic-select, even though the status and message were undefined, causing a console error.
N/A
> Fixed console errors in ic-popover-menu and ic-select components

- CHECKLIST.md
Update PR checklist guide to include information on what to test and look out for when going through components
#1818
> chore(root): update PR checklist guide to include information on what to test

- .github/workflows/deploy-storybook-only.yml
- .github/workflows/scorecards.yml
Update workflows with pinned dependencies to improve security issues
N/A
> chore(root): update workflows with pinned dependencies

- .github/workflows/update-cypress-visual-regression-tests.yml
Fix updating cypress tests workflow
N/A
N/A
> fix(root): fix updating cypress tests

- packages/react/src/component-tests/IcCheckbox/IcCheckbox.cy.tsx
- packages/react/src/component-tests/IcCheckbox/IcCheckboxTestData.tsx
- packages/react/src/stories/ic-checkbox.stories.mdx
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.tsx
- packages/web-components/src/components/ic-checkbox-group/test/basic/__snapshots__/ic-checkbox-group.spec.ts.snap
- packages/web-components/src/components/ic-checkbox-group/test/basic/ic-checkbox-group.spec.ts
- packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx
- Added code to `componentWillLoad` in ic-checkbox to get the `label` and `name` from its parent and set the `groupLabel` and `name` if required. This has been moved for ic-checkbox-group to ensure that if new checkboxes are added then they can populate these properties.
- Added watch handler for `name` and `label` in ic-checkbox-group that will update each child checkbox's `groupLabel` and `name`. If the name has been set on the ic-checkbox element then it will not override it.
- Added tests and stories to the react package, to ensure that this functionality works properly.
- Minor refactoring
#1803 #1817
> Ensure that attributes correctly pass down from ic-checkbox-group to ic-checkbox

- packages/docs/docs.json
- packages/react/src/stories/ic-radio-group.stories.mdx
- packages/react/src/stories/ic-top-navigation.stories.mdx
- packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
- packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.mdx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
- packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
- packages/web-components/src/components/ic-skeleton/ic-skeleton.tsx
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx
- packages/web-components/src/components/ic-top-navigation/readme.md
- Updated prop description for app-icon to clarify that its content will be hidden from screen readers
- Added condition before a top-nav's searchBar has an attribute is applied to ensure the element actually exists
- Added HC mode styling to ic-navigation-item's external link icon
- Added react story showing how to conditionally render tabs, and how to conditionally render slotted text fields into ic-radio-option
- Minor refactoring in ic-skeleton to remove unnecessary state
- Added code to ic-radio-option to update hasAdditionalField when new slot content is added/removed
#1817 #1244 #1633 https://github.com/mi6/ic-design-system/issues/910 #1786
> PR checklist updates for ic-top-navigation/ic-skeleton/ic-radio

- packages/react/src/stories/ic-switch.stories.mdx
- packages/web-components/src/components/ic-switch/ic-switch.css
- packages/web-components/src/components/ic-switch/ic-switch.stories.mdx
Add a playground web-components story for ic-switch. Additionally, add dark mode media query for switch
ref #1817
> docs(web-components): add playground to switch, prep for dark mode

- packages/docs/docs.json
updates docs package with status tag change
N/A
> docs(docs): updates docs with status tag change

- packages/docs/docs.json
New icon variants have been added the ic-button which requires and update to the docs json for the guidance site
#1675
> feat(docs): updated docs to include new icon variants

- audit-ci.json
Adds to allowlist for vulnerability in "ip" package - no current patch available
N/A
> chore(root): adds to allowlist for audit

- packages/canary-react/src/stories/ic-data-table.stories.mdx
Updated storybook code snippet imports for data tables.
N/A
N/A
> fix(canary-react): cleaned up data table code snippets

- packages/web-components/src/components/ic-dialog/ic-dialog.css
Fixes issue where opacity was incorrect when animations disabled. Also only does translate transition if animation are allowed 
#1944
> fix(web-components): fixes opacity issue on dialog

- audit-ci.json
Adds to allowlist for braces package to fix audit issue
N/A
> chore(root): adds to allowlist for braces package

- packages/react/src/stories/ic-tooltip.stories.mdx
- packages/web-components/src/components/ic-tooltip/ic-tooltip.stories.mdx
Add playground for tooltip component.
Toggling disable hover doesn't work so I raised #1990 
Part of #1970
> 1970 tooltip playground

- packages/react/src/stories/ic-pagination.stories.mdx
> 1988 pagination playground

- packages/web-components/stencil.config.ts
Adds checks for 80% coverage for utils code
#1772
> test(web-components): adds coverage check for utils files

- packages/react/src/stories/ic-footer.stories.mdx
add Footer playground to React so all props can be tested
#1970
> 1970 add Footer playground to React 

- packages/react/src/stories/ic-back-to-top.stories.mdx
Adds storybook playground for back to top component
#1970
> feat(react): adds playground for back to top

- packages/react/src/stories/ic-top-navigation.stories.mdx
- packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.mdx
Add playground story for top navigation
Part of #1970
> 1970 top nav playground

- packages/react/src/stories/ic-hero.stories.mdx
add Hero playground to React to test all combinations of props
#1970
> docs(react): add Hero playground to React

- .github/pull_request_template.md
- CHECKLIST.md
Add item to pull_request_template asking that developers keep playground stories up to date. Relevant guidance added to CHECKLIST.md
> docs(root): add pr checklist item for storybook playgrounds

- packages/react/src/stories/ic-page-header.stories.mdx
add Page Header playground to React so all props can be tested
#1970
> add Page Header playground to React so all props can be tested

- package-lock.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Updates braces and ws packages to resolve Dependabot alerts
N/A
> Dependabot fixes

- packages/react/src/component-tests/IcAccordion/IcAccordion.cy.tsx
- packages/react/src/stories/ic-accordion.stories.mdx
- packages/web-components/src/components/ic-accordion-group/ic-accordion-group.tsx
- packages/web-components/src/components/ic-accordion/ic-accordion.stories.mdx
- packages/web-components/src/components/ic-accordion/ic-accordion.tsx
Add playground story and update accordion to watch props and use message prop
Part of #1970
> 1970 accordion playground

- packages/web-components/src/components/ic-badge/ic-badge.css
- packages/web-components/src/global/variables.css
Removed depricated colour tokens from variables
BREAKING CHANGE: This involves removing css variables which may cause user products to appear incorrectly
#996
> feat(web-components): removed depricated colour tokens

- packages/docs/docs.json
- packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
- packages/web-components/src/components/ic-radio-group/test/basic/__snapshots__/ic-radio-group.spec.ts.snap
- packages/web-components/src/components/ic-radio-group/test/basic/ic-radio-group.e2e.ts
- packages/web-components/src/components/ic-radio-group/test/basic/ic-radio-group.spec.ts
- packages/web-components/src/components/ic-radio-option/ic-radio-option.css
- packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
- Removed shadow property from ic-radio-option
- Adjusted css selectors/tests/docs to match component no longer being shadow
- Changed isSlotUsed to slotHasContent in ic-radio-option & ic-radio-group, since this works better no that shadow has been removed.
#1804
> fix(web-components): changed ic-radio-option to no longer be a shadow component

- packages/react/src/stories/ic-link.stories.mdx
- packages/react/src/stories/ic-skeleton.stories.mdx
- packages/web-components/src/components/ic-link/ic-link.stories.mdx
- packages/web-components/src/components/ic-skeleton/ic-skeleton.stories.mdx
Add playground story for link and skeleton
Part of #1970
> 1970 more component playgrounds

- CONTRIBUTING.md
> chore(root): add note section

- README.md
Makes the README a bit nicer.
N/A
> docs(root): add better highlights

- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/update-v3-branch.yml
Apply workflows related to the develop branch to v3.0.0/develop branch
#2058
> ci(root): apply workflows to v3.0.0/develop branch

- .github/workflows/update-v3-branch.yml
Fix API call in V3 workflow
#2058
> ci(root): fix API call in v3 workflow

- .github/workflows/ic-ui-kit-release-v3.yml
- .github/workflows/ic-ui-kit-v3.yml
Add v3 publishing workflow, which should work similar to the main workflow but publish using a--tag=next which will mean it doesn't get automatically installed
#2059
> chore(root): add v3 publishing workflow

- packages/web-components/src/components/ic-page-header/ic-page-header.tsx
- packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap
- packages/web-components/src/components/ic-page-header/test/basic/ic-page-header.spec.ts
Update role on page header to presentation and add aria label to copy old behaviour more
#1908
> 1908 page header complaining of two elements with role banner

- audit-ci.json
Bumps dates for audit allowlist entries
N/A
> chore(root): bumps audit expiry

- .github/workflows/update-v3-branch.yml
Remove line about DELETE-ME.txt in the PR description for update-v3-branch workflow
> ci(root): amend PR description for update-v3-branch workflow

- packages/react/src/stories/ic-popover-menu.stories.mdx
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx
Update popover menu stories to have show/hide in button label to help understand button behaviour better
#1736
> 1736 popover menu accessibility improvements open and close announcements

- README.md
- build-tar.sh
While setting up the dependencies locally towards the ic-design website, I encountered a few steps that could be automated. I've also added some documentation that uses `npm link` instead of generating a tar file.
#2105
- https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557
N/A
> docs(root): improve setup docs and steps

- README.md
There's no link to lerna in the readme, but we mention it. Should have a link to the tool.
N/A
> docs(root): linkify lerna

- .github/pull_request_template.md
- CHECKLIST.md
Update PR checklist and CHECKLIST.md to include testing props/slots after initial render
> chore(root): update PR checklist

- CONTRIBUTING.md
Update contribution guide to include steps on generating cypress images, and an extra step to turn on workflows in forked repos
#1941
> 1941 Add ci visual regression steps to markdown file

- packages/react/src/stories/ic-alert.stories.mdx
- packages/react/src/stories/ic-card.stories.mdx
- packages/react/src/stories/ic-empty-state.stories.mdx
- packages/react/src/stories/ic-hero.stories.mdx
- packages/web-components/src/components/ic-alert/ic-alert.stories.mdx
- packages/web-components/src/components/ic-alert/ic-alert.tsx
- packages/web-components/src/components/ic-alert/test/basic/ic-alert.spec.ts
- packages/web-components/src/components/ic-card/ic-card.stories.mdx
- packages/web-components/src/components/ic-card/ic-card.tsx
- packages/web-components/src/components/ic-card/test/basic/ic-card.spec.ts
- packages/web-components/src/components/ic-empty-state/ic-empty-state.stories.mdx
- packages/web-components/src/components/ic-empty-state/ic-empty-state.tsx
- packages/web-components/src/components/ic-hero/ic-hero.tsx
- packages/web-components/src/components/ic-hero/test/basic/ic-hero.spec.ts
- packages/web-components/src/utils/helpers.ts
Update alert, card, empty state and hero components so that slots can update after initial render
https://github.com/mi6/ic-ui-kit/issues/1901, https://github.com/mi6/ic-ui-kit/issues/1881, https://github.com/mi6/ic-ui-kit/issues/1875, https://github.com/mi6/ic-ui-kit/issues/1879
> Slots not updating after initial render

- .cspell.json
Adds the word "rhoncusut" to cspell dict.
- https://github.com/mi6/ic-ui-kit/issues/2271
> fix(root): add unrecognized latin word to cspell

- .github/workflows/ic-ui-kit-branches.yml
- .github/workflows/ic-ui-kit-develop.yml
- .github/workflows/ic-ui-kit-main.yml
- .github/workflows/ic-ui-kit-v3.yml
- .husky/pre-commit
- package.json
Adds Cspell to the static analysis stage of the CI.
- #2237
> chore(root): fix cspell flags, add cpsell to ci and precommit hook

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Add CODE_OF_CONDUCT.md to `ic-ui-kit` for easy access within the repo and added clarity
- Update link to code of conduct in CONTRIBUTING.md
> Add CODE_OF_CONDUCT.md to `ic-ui-kit` 

- packages/docs/docs.json
- packages/react/src/stories/ic-radio-group.stories.mdx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.mdx
- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
Now when the radio group has an additional field it will change from horizontal to vertical, along with following this rule if there are more then 2 radio options in the group.
Also, radio groups will switch from horizontal to vertical if the totalwidth becomes greater then the client width it finds itself in.
#1820
> 1820 ic radio group overriding orientation

- audit-ci.json
- package-lock.json
Update audit-ci.json to account for new vulnerability.
Update axios version using 'npm update'
> build(root): audit-ci update

- CONTRIBUTING.md
added amending a commit guidance
#1330
> docs(root): added amending a commit guidance

- packages/docs/docs.json
- packages/react/src/stories/ic-footer.stories.mdx
- packages/web-components/src/components/ic-footer-link-group/test/basic/__snapshots__/ic-footer-link-group.spec.ts.snap
- packages/web-components/src/components/ic-footer-link/ic-footer-link.css
- packages/web-components/src/components/ic-footer-link/ic-footer-link.tsx
- packages/web-components/src/components/ic-footer-link/readme.md
- packages/web-components/src/components/ic-footer-link/test/basic/__snapshots__/ic-footer-link.spec.ts.snap
- packages/web-components/src/components/ic-footer/ic-footer.css
- packages/web-components/src/components/ic-link/readme.md
> 265 ic footer to use ic link

- audit-ci.json
- package-lock.json
- packages/nextjs/package-lock.json
Updates allowlist for audit issue - adds one item & removes another
Updates a couple of packages for dependabot issues
N/A
> Audit fix & package update

- packages/web-components/src/components/ic-pagination/ic-pagination.css
- packages/web-components/src/components/ic-pagination/ic-pagination.tsx
- packages/web-components/src/components/ic-pagination/test/basic/__snapshots__/ic-pagination.spec.ts.snap
Added aria-live region to announce current page on complex pagination (i.e. match simple pagination screen reader behaviour).
#1808
> feat(web-components): add aria-live region to announce current page on complex pagination

- .github/workflows/ic-ui-kit-v3.yml
Update lerna command from --tag=next to --dist-tag next
#2147
N/A
> Update lerna command

- packages/web-components/src/components/ic-toast/ic-toast.css
Update toast animation to only work when prefers reduced motion is off
#1926
> 1926 toast doesn't conform to prefers reduced motion

- packages/docs/docs.json
- packages/react/src/component-tests/IcLoadingIndicator/IcLoadingIndicatorTestData.tsx
- packages/react/src/stories/ic-loading-indicator.stories.mdx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.stories.mdx
- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.tsx
- packages/web-components/src/components/ic-loading-indicator/readme.md
- packages/web-components/src/components/ic-loading-indicator/test/basic/ic-loading-indicator.spec.ts
Update loading indicator to use an array when splitting labels instead of / inside a string
BREAKING CHANGE: Instead of passing "loading/still loading" to a loading indicator to dynamically
change the label, it's now passed as ["loading", "still loading"]
#248
> 248 ic loading indicator allow loading indicator to accept arrays of strings

- audit-ci.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
- upgrades express package to fix audit issue
- bumps dates for other allowed items
N/A
> Audit fix - express package upgrade

- audit-ci.json
Tidyup to remove item left after rebase
N/A
> chore(root): tidyup of allowlist for audit

- .github/workflows/add-qa-link-to-issues.yml
- .github/workflows/ic-ui-kit-branches.yml
Removing the link to nextjs from PR comments.
Also removing the build-storybook line, and the deploy step for nextjs.
N/A
N/A
> ci(root): update workflows to remove building/deploying nextjs storybook

- .github/workflows/ic-ui-kit-develop.yml
Remove nextjs build and deploy steps from develop workflow
N/A
N/A
> chore(root): remove nextjs build and deploy steps from develop workflow

- packages/react/src/stories/ic-theme.stories.mdx
- packages/web-components/src/components/ic-theme/ic-theme.stories.mdx
Update theme storybook to have a visualisation playground for top level theme changes (system, light, dark) and component level changes (inherit, light, dark)
#2373
> 2373 add ictheme visualisation to storybook

- packages/docs/docs.json
- packages/react/src/component-tests/IcTabs/IcTabsTestData.tsx
- packages/react/src/stories/ic-tabs.stories.mdx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-tab-context/ic-tab-context.tsx
- packages/web-components/src/components/ic-tab-context/ic-tabs.stories.mdx
- packages/web-components/src/components/ic-tab-context/readme.md
- packages/web-components/src/components/ic-tab-context/test/basic/__snapshots__/ic-tab-context.spec.ts.snap
- packages/web-components/src/components/ic-tab-context/test/basic/ic-tab-context.spec.ts
- packages/web-components/src/components/ic-tab-group/ic-tab-group.css
- packages/web-components/src/components/ic-tab-group/ic-tab-group.tsx
- packages/web-components/src/components/ic-tab-panel/ic-tab-panel.css
- packages/web-components/src/components/ic-tab-panel/ic-tab-panel.tsx
- packages/web-components/src/components/ic-tab/ic-tab.css
- packages/web-components/src/components/ic-tab/ic-tab.tsx
- packages/web-components/src/global/borders.css
- packages/web-components/src/global/color-mode.css
- packages/web-components/src/global/colors.css
Update tabs to use theme and monochrome prop instead of appearance prop
Working towards https://github.com/mi6/ic-ui-kit/issues/1214
> Tabs dark mode

- packages/docs/docs.json
- packages/react/src/component-tests/IcAccordion/IcAccordionTestData.tsx
- packages/react/src/stories/ic-accordion.stories.mdx
Just a quick change to the react story so that the heading on the slotted headings story is in the correct place.
https://github.com/mi6/ic-ui-kit/issues/2148
> 2148 accordion slotted heading story is not as expected in react

- packages/nextjs/package-lock.json
- packages/nextjs/package.json
Update nextjs to 3.0.0-alpha.0
> chore(nextjs): update to 3.0.0-alpha.0

- packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx
- packages/docs/docs.json
- packages/nextjs/package.json
> V3developfix

- audit-ci.json
Bumps dates for audit allowlist
N/A
> chore(root): bump dates for audit allowlist

- packages/canary-react/src/stories/ic-data-table.stories.mdx
- packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx
- packages/canary-web-components/src/components/ic-data-table/story-data.ts
Update to storybook examples for setting a max-width on a column
N/A
> Data table docs fix

- packages/react/src/component-tests/IcStatusTag/IcStatusTag.cy.tsx
- packages/react/src/component-tests/IcStatusTag/IcStatusTagTestData.tsx
Added E2E tests for status tag.
#2097
> test(react): cypress migration for status tag

- packages/react/src/component-tests/IcPopoverMenu/IcPopoverMenu.cy.tsx
- packages/react/src/component-tests/IcPopoverMenu/IcPopoverMenuData.tsx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
…ing submenu
fix the icpopoverclosed event not being emitted when the popovermenu is closed from a submenu and add relevant tests
fix #2297
> fix(web-components): fix icpopoverclosed event not emitting when closing a submenu

- packages/canary-react/package-lock.json
- packages/react/src/component-tests/IcStepper/IcStepper.cy.tsx
- packages/react/src/component-tests/IcToast/IcToast.cy.tsx
Fix cypress test issues introduced by rebase:
- Prettier fixes in toast
- Update prop name in stepper
N/A
> test(react): fix cypress test issues introduced by rebase

- packages/docs/docs.json
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-alert/ic-alert.css
- packages/web-components/src/components/ic-alert/ic-alert.tsx
- packages/web-components/src/components/ic-alert/readme.md
Slight change to previous fix with hiding icon
N/A
> Alert fix when hiding default icon

- packages/docs/docs.json
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-alert/ic-alert.css
- packages/web-components/src/components/ic-alert/ic-alert.tsx
- packages/web-components/src/components/ic-alert/readme.md
Replicates #2616 in V3 branch
N/A
> Gatsby alert fix in V3 branch

- packages/canary-react/.storybook/preview.js
- packages/canary-web-components/.storybook/preview.js
- packages/nextjs/.storybook/preview.js
- packages/react/.storybook/preview.js
- packages/web-components/.storybook/preview.js
Add a "Theme" button to allow for ease of switching between dark mode and light mode
> Add theming for storybook

- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
Replicating changes from https://github.com/mi6/ic-ui-kit/pull/2612 on v3
> fix(web-components): fix multiple radio options being selected with the same value

- packages/web-components/package-lock.json
Upgrades packages to resolve dependabot issues
N/A
> chore(web-components): upgrades express package and dependencies

- packages/web-components/src/components/ic-checkbox-group/test/basic/__snapshots__/ic-checkbox-group.spec.ts.snap
- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
- packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx
In Safari we get a console error as a result of the checkbox's SVG having a width and height set in REM: _Invalid value for <svg> attribute width/height "1.5rem"_. See https://bugzilla.mozilla.org/show_bug.cgi?id=1231147
This PR fixes that by removing the "1.5rem" width/height for the SVG, in favour of adding a default size in CSS. I've checked Storybook + modified text sizes and no visual regressions have been introduced.
> fix(web-components): remove REM explicit width/height from checkbox SVG in favour of CSS default

- packages/web-components/src/components/ic-checkbox-group/test/basic/__snapshots__/ic-checkbox-group.spec.ts.snap
- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
- packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx
Cherry picking work from https://github.com/mi6/ic-ui-kit/pull/2661
N/A
> fix(web-components): remove REM explicit width/height from checkbox SVG (v3)

- packages/web-components/src/global/color-mode.css
- packages/web-components/src/global/colors.css
Add atoms css tokens to colors.css and color-mode.css to be utilised for light and dark themes
Checked Figma and none of the already implemented components use atoms tokens, so no changes required there.
Working towards #1214
> Atoms theme work

- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.tsx
- packages/web-components/src/components/ic-checkbox-group/test/basic/__snapshots__/ic-checkbox-group.spec.ts.snap
- packages/web-components/src/components/ic-input-label/ic-input-label.tsx
- packages/web-components/src/components/ic-input-label/test/basic/__snapshots__/ic-input-label.spec.tsx.snap
- packages/web-components/src/components/ic-input-label/test/basic/ic-input-label.spec.tsx
Removed for argument in ic-checkbox-group label legend and added prop to ic-label-input to specify if label content should be wrapped in label tag
Added a new internal prop to explicitly set if ic-label-input content is wrapped in a label tag or not
#1647
> fix(web-components): added useLabelTag Prop

- packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.css
added height to ic-loading-indicator inner loading icon style 
#1914
> fix(web-components): added styling to loading indicator

- packages/canary-web-components/src/components/ic-date-input/ic-date-input.css
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
Cherry pick work from #2681 
#1967
> 1967 date input browser suggestion cherry pick (v3)

- packages/web-components/src/components/ic-classification-banner/ic-classification-banner.css
- packages/web-components/src/global/colors.css
Implement theme prop for classification banner to make use of light and dark theme colours
Working towards #1214
> Classification banner theme prop

- .github/cherry-pick.yml
Automates cherry-picking (https://github.com/marketplace/actions/github-cherry-pick-action). To convert this from draft to ready, enable the action and merge this PR.
#2669
> chore(root): add automated cherry-picking to v3/develop

- packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx
Fixes truncation of tree items on load
N/A
> fix(canary-web-components): fixes truncation of tree items

- .github/workflows/cherry-pick.yml
Updates workflow file for v3 cherry-picking to work on node 20.
Also sets the title & reference the original PR
N/A
> Updates cherry-pick workflow

- packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx
Fixes truncation of tree items on load - cherry-picked in v3 branch
N/A
> Truncation of tree items - v3 cherry pick

- packages/react/src/component-tests/IcClassificationBanner/IcClassificationBanner.cy.tsx
Fixes wrongly spelled word.
- #2712
> fix(react): fix typo in test title

- packages/react/src/component-tests/IcClassificationBanner/IcClassificationBanner.cy.tsx
Getting the change from https://github.com/mi6/ic-ui-kit/pull/2715 into v3
> v3 Cherrypick - fix(react): reword wrong spelling

- .github/workflows/cherry-pick.yml
update token in cherry-pick workflow to auth as a user, using a PAT rather than a GitHub Token, to bypass branch permissions using my user
NA
> chore(root): update token in cherry-pick workflow

- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
cherry-pick of https://github.com/mi6/ic-ui-kit/pull/2732
N/A
> Audit cherry pick

- audit-ci.json
> chore(root): update audit ci dates (v3)

- packages/react/src/stories/ic-page-header.stories.mdx
- packages/web-components/src/components/ic-navigation-item/ic-navigation-item.tsx
- packages/web-components/src/components/ic-navigation-item/test/basic/__snapshots__/ic-navigation-item.spec.ts.snap
- packages/web-components/src/components/ic-navigation-item/test/basic/ic-navigation-item.spec.ts
- packages/web-components/src/components/ic-page-header/ic-page-header.stories.mdx
cherry pick of https://github.com/mi6/ic-ui-kit/pull/2701 into v3
#2615
> Nav item nvda v3 cherry pick

- .cspell.json
- packages/web-components/src/components/ic-select/ic-select.css
- packages/web-components/src/components/ic-text-field/ic-text-field.css
- packages/web-components/src/global/ag-theme-icds.css
- packages/web-components/stencil.config.ts
Cherry-picked ag-grid changes onto a v3 branch, this is to move them onto v3/develop
#2433
> AG Grid onto v3/develop

- packages/web-components/src/components/ic-footer-link-group/ic-footer-link-group.css
- packages/web-components/src/components/ic-footer-link/ic-footer-link.css
- packages/web-components/src/components/ic-footer/ic-footer.css
- packages/web-components/src/global/colors.css
Update footer to use css tokens to make use of light/dark theme
Working towards #1214
> Footer theme css tokens

- packages/docs/docs.json
- packages/react/src/component-tests/IcPopoverMenu/IcPopoverMenu.cy.tsx
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx
- packages/web-components/src/components/ic-menu-item/readme.md
- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx
Cherrypick of https://github.com/mi6/ic-ui-kit/pull/2723
> Togglechecked-cherry-pick

- packages/web-components/src/global/colors.css
Updates some of the action tokens to match deigns
N/A
> fix(web-components): updates action colors

- README.md
Add instructions on how to test canary react packages in other projects
Based on learnings working on https://github.com/mi6/ic-ui-kit/pull/2760
> docs(root): Add instructions on how to test canary react packages in other projects

- packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumb.cy.tsx
- packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumbTestData.tsx
- packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx
- packages/web-components/src/components/ic-breadcrumb-group/test/basic/__snapshots__/ic-breadcrumb-group.spec.ts.snap
> cherrypick - 1998/ic-breadcrumb-group collapsed prop

- README.md
Just a small fix to follow convention.
N/A
> chore(root): use 'install' not 'i' in guide

- audit-ci.json
cherry-pick of https://github.com/mi6/ic-ui-kit/pull/2791 into v3
adds to allowlist for cross-spawn package
N/A
> chore(root): adds to allowlist for audit issue - v3 cherry-pick

- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
Update showLoadingIndicator to check this.loadingIndicator exists to avoid data table error
#2789
> 2924 - IcDataTable loadingIndicator issue

- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
Cherry pick work from https://github.com/mi6/ic-ui-kit/pull/2812
#2789
> Cherry pick - 2789 data table loading indicator issue

- packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
- packages/web-components/src/components/ic-side-navigation/test/basic/__snapshots__/ic-side-navigation.spec.ts.snap
- packages/web-components/src/components/ic-side-navigation/test/basic/ic-side-navigation.spec.ts
added null handling if there is no icon for navigation item
fix #2795
> fix(web-components): fix side navigation 'failed to execute getComputedStyle' console error

- README.md
- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
- packages/canary-web-components/src/utils/helpers.ts
Cherry pick external contributions:
https://github.com/mi6/ic-ui-kit/pull/2761
https://github.com/mi6/ic-ui-kit/pull/2760
> Cherry-pick-external-contributions

- packages/web-components/src/components/ic-alert/ic-alert.tsx
- packages/web-components/src/components/ic-alert/test/basic/ic-alert.spec.ts
> fix(web-components): ic-alert change

- audit-ci.json
bumps audit dates in v3
replicates https://github.com/mi6/ic-ui-kit/pull/2857 in v3
> chore(root): bumps audit dates

- audit-ci.json
Removes item no longer needed in allowlist. had already been removed from v3 codebase
N/A
> chore(root): removes audit exception

- packages/canary-docs/docs.json
- packages/canary-web-components/src/components.d.ts
- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
Cherry pick of https://github.com/mi6/ic-ui-kit/pull/2855
> Cherry-pick-data-table-contribution

- packages/canary-web-components/src/components/ic-menu-with-multi/test/basic/ic-menu.spec.tsx
Fixes import to match all other canary components
N/A
> test(canary-web-components): fixes import in test file

- packages/canary-web-components/src/components/ic-card-horizontal/ic-card-horizontal.css
Copied styling changes over from PR [#2896](https://github.com/mi6/ic-ui-kit/pull/2896) which was merged into the v2 develop branch.
I don't get any failures when running `npm run audit` on the v3 develop branch so this PR just adds the CSS changes.
N/A
> (Copied from v2) Horizontal card Safari image bug fix

- package-lock.json
updates packages to fix audit issues
N/A
> chore(root): audit fix

- package-lock.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/fonts/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
updates nanoid version in all packages to fix audit issue and match develop branch
N/A
> V3 audit fix

- packages/canary-web-components/src/components/ic-date-input/ic-date-input.css
Update webkit autofill colours for date input dark mode so that it appears correctly after a browser suggestion
#2915
> fix(canary-web-components): update webkit autofill colours for date input dark mode

- packages/docs/docs.json
- packages/web-components/src/components.d.ts
Update components.d.ts and docs.json files that are causing release to fail
> Release-fix

- packages/fonts/package.json
Update @ukic/fonts version to fix failing release
> fix(fonts): update @ukic/fonts version to fix failing release

- packages/fonts/package-lock.json
- packages/fonts/package.json
Update fonts package to alpha versioning for v3 to stop clashes with v2 releases
BREAKING CHANGE: Package version updated to 3.0.0-alpha.0
N/A
> chore(fonts): update fonts package to alpha versioning for v3

- packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
The pagination bar itemsPerPageOptions prop was being mutated by the pagination par component. This was causing duplicate items to appear in the "items per page" dropdown in the pagination bar, due to the original items in the parent component being modified by the pagination bar component.
The solution is to clone the input itemsPerPageOptions props before mutating them in the component.
N/A
> Prevent duplication of pagination bar items per page dropdown items

- packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
replicates #2946 in v3 branch
N/A
> cherry pick : prevent mutation of ic-pagination-bar items per page options prop

- .github/workflows/add-qa-link-to-issues.yml
Update branch deployment links added to PRs to include canary links when a change has been made to the canary packages
#2276
> ci(root): update branch deployment links added to PRs

- audit-ci.json
> chore(root): audit date fix

- packages/react/src/stories/ic-text-field.stories.mdx
- packages/web-components/src/components/ic-text-field/ic-text-field.tsx
The IcTextField was displaying an error in the console and the component was not being displayed if the _value_ prop was passed in as null or undefined.
This change adds some checking around the _value_ prop when assessing its length, in order to avoid the error from occurring when the _value_ prop is null or undefined.
#2813
> 2813 Allow the IcTextField to be able to handle null or undefined values

- packages/react/src/stories/ic-text-field.stories.mdx
- packages/web-components/src/components/ic-text-field/ic-text-field.tsx
cherry-pick of https://github.com/mi6/ic-ui-kit/pull/2990/ into v3
#2813
> V3 cherry pick textfield

- packages/canary-react/README.md
- packages/canary-web-components/README.md
- packages/nextjs/README.md
- packages/react/README.md
- packages/web-components/README.md
Update CHANGELOG links so they point to the right CHANGELOG
> Update CHANGELOG links

- .cspell.json
- packages/codemod/codemod.js
- packages/codemod/package-lock.json
- packages/codemod/package.json
> feat(codemod): add yargs

- packages/react/src/component-tests/IcTextField/IcTextField.cy.tsx
- packages/react/src/component-tests/IcTextField/IcTextFieldTestData.tsx
- packages/react/src/stories/ic-text-field.stories.mdx
- packages/web-components/src/components/ic-text-field/ic-text-field.tsx
> Text field hidden input cherry pick

- packages/canary-react/README.md
- packages/canary-web-components/README.md
- packages/react/README.md
- packages/web-components/README.md
Correct syntax for shell comments.
N/A
> docs: use shell comments correctly

- packages/web-components/src/components/ic-tooltip/ic-tooltip.stories.mdx
Update disabled hover tooltip story to use aria labelledby so that it reads out tooltip information
#1916
> 1916 tooltip disable hover

- .github/workflows/deploy-storybook-only.yml
- .github/workflows/ic-ui-kit-branches.yml
Updates actions cache to v4.2.0
#3037
> chore(root): updates actions cache to latest version

- .github/workflows/deploy-storybook-only.yml
- .github/workflows/ic-ui-kit-branches.yml
replicates https://github.com/mi6/ic-ui-kit/pull/3046/ in v3 branch
updates actions cache to v4.2.0
#3037
> v3 cherry-pick actions cache update

- packages/canary-react/README.md
- packages/canary-web-components/README.md
- packages/react/README.md
- packages/web-components/README.md
Cherry-picked #3033 onto v3.0.0/develop
> Docs comment cherry pick

- packages/react/src/component-tests/IcDialog/IcDialog.cy.tsx
Adds delays to allow dialog to fully load
N/A
> test(react): fixes unreliable dialog tests

- packages/react/README.md
Added web-components to v3 install instructions to ensure correct styling whilst in pre-release
#2974
> docs(react): added web-components to install instructions

- packages/web-components/src/components/ic-tooltip/ic-tooltip.stories.mdx
> Cherry pick 1916

- packages/react/src/component-tests/IcSearchBar/IcSearchBar.cy.tsx
Updated test to avoid unintentionally blurring element and losing focus state and by extension clear button and menu
#2015
> test(react): updated flaky search-bar test

- .github/workflows/ic-ui-kit-v3.yml
Reverts previous change as causing publish failure
N/A
> ci(root): revert publish workflow change

- packages/codemod/package.json
Updates package.json for codemod for publishing
N/A
> chore(codemod): updates package.json for publish

- packages/web-components/src/components/ic-radio-option/ic-radio-option.css
CSS changes to bring ic-radio-option dark theme in line with design
#2909
> style(web-components): ic-radio-option css

- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Cherry picking audit fix https://github.com/mi6/ic-ui-kit/pull/3095
> V3 audit fix 27 01

- packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx
- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
- packages/canary-web-components/src/components/ic-data-table/story-data.ts
> 2819 cherry pick

- packages/docs/docs.json
- packages/react/src/component-tests/IcDialog/IcDialog.cy.tsx
- packages/react/src/component-tests/IcDialog/IcDialogTestData.tsx
- packages/react/src/stories/ic-dialog.stories.mdx
- packages/web-components/src/components/ic-dialog/ic-dialog.stories.mdx
- packages/web-components/src/components/ic-dialog/ic-dialog.tsx
- packages/web-components/src/components/ic-dialog/test/basic/__snapshots__/ic-dialog.spec.ts.snap
- packages/web-components/src/components/ic-dialog/test/basic/ic-dialog.spec.ts
Fixes focus issues with search bar, date input & date picker when used on ic-dialog
Unable to add tests for date components on dialog as in canary package, but tested manually in an app
#2976
> 2976 search bar on dialog fix

- packages/react/src/stories/ic-side-navigation.stories.mdx
- packages/web-components/src/components/ic-navigation-item/ic-navigation-item.tsx
fix: when a slotted element is used, .setFocus will now apply focus on the slotted link
#1145
> 1145 navigation item focus

- packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx
- packages/react/src/component-tests/IcRadio/IcRadioTestData.tsx
- packages/react/src/stories/ic-radio-group.stories.mdx
Updating last react commit message to be feat so that the versions stay in sync
> Updating last react commit message to be feat

- packages/react/src/stories/ic-tooltip.stories.mdx
Update tooltip story title to lowercase - adds a feat commit for release
N/A
> feat(react): update tooltip story title to lowercase

- audit-ci.json
Update audit dates for March
N/A
> chore(root): update audit dates

- audit-ci.json
Update audit dates for March - v3 cherry pick
N/A
> chore(root): update audit dates - v3 cherry pick

- packages/canary-react/README.md
- packages/canary-web-components/README.md
- packages/react/README.md
- packages/web-components/README.md
Adds badges to the readme in each repo that currently has badges. If you click a badge, you get navigated to the npm repo. 
Note: can add badges to remaining if needed.
N/A
> chore: npm badges

- packages/react/src/stories/ic-toast.stories.mdx
- packages/web-components/src/components/ic-toast/ic-toast.stories.mdx
- packages/web-components/src/components/ic-toast/ic-toast.tsx
- packages/web-components/src/components/ic-toast/test/basic/ic-toast.spec.ts
Cherrypick https://github.com/mi6/ic-ui-kit/pull/3147 onto v3
> Cherrypick 2710 toast autodismiss

- packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
Update date input so "with-helper" css isn't used with no helper text - swap null for empty string so input label doesn't render it under the hood
Tested changing hide helper text example to the below code and now date input and text field are aligned.
```
<Canvas withSource="none">
<Story name="Hide helper text">
{html`
<div style="display: flex; gap: 8px"><ic-date-input
label="When would you like to collect your coffee?"
helper-text="You cannot see me, but you can hear me"
hide-helper-text="true"
></ic-date-input>
<ic-text-field label="What is your favourite coffee?"></ic-text-field>
</div>`}
</Story>
</Canvas>
```
#2370
> Date input with helper fix

- packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
> With helper css v3

- packages/docs/docs.json
Docs update as latest not committed
N/A
> docs(docs): docs update

- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
Dependency updates to resolve dependabot issues
elliptic
serialize-javascript
N/A
> Dependencies updates

- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
Updates packages - replicates: https://github.com/mi6/ic-ui-kit/pull/3197 in v3
> V3 dependency updates

- package.json
- packages/canary-docs/package.json
- packages/canary-react/package.json
- packages/canary-web-components/package.json
- packages/docs/package.json
- packages/fonts/package.json
- packages/nextjs/package.json
- packages/react/package.json
- packages/web-components/package.json
Adds metadata about repository, fixes one wrong field and adds packageManager field to package.json's. The npm version is specified by the range starting from the node version in .nvmrc.
N/A
> chore: tweaks to package.json fields

- audit-ci.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Update audit ci json with new vulnerabilities we can't fix.
And ran audit fix in packages for others.
N/A
> Audit fix v2

- audit-ci.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Update audit ci json with new vulnerabilities we can't fix
And run audit fix for others.
N/A
> Audit update v3

- packages/web-components/src/components/ic-dialog/ic-dialog.tsx
- packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx
description change to say default button will not be shown however, slotted controls will
> docs(web-components): description change in the buttons prop

- .github/workflows/ic-ui-kit-v3-release-merged.yml
Adds workflow to trigger v3 guidance site update
N/A
> chore(root): triggers v3 site check-versions

- .github/workflows/ic-ui-kit-v3-release-merged.yml
Adds workflow to trigger v3 guidance site check-versions
Implements https://github.com/mi6/ic-ui-kit/pull/3203 in v3 branch
> cherry-pick trigger of v3 site check-versions

- .github/workflows/ic-ui-kit-release-v3-check.yml
replace references to release with v3.0.0/release in the v3 release check script
> ci(root): fix v3 release workflow part 2

- .github/workflows/ic-ui-kit-release-v3-check.yml
Cherrypick of the two release workflow fixes for v3
> Fix v3 release workflow cherrypick

- packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
Add check for selectedOption to prevent undefined error in radio group
N/A
> Small radio group fix

- packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
> Cherry pick 2244 date input full date deletion

- packages/canary-react/src/component-tests/IcPaginationBar/IcPaginationBar.cy.tsx
- packages/canary-react/src/component-tests/IcPaginationBar/IcPaginationBarTestData.tsx
- packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.stories.mdx
- packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
V3 cherry-pick for https://github.com/mi6/ic-ui-kit/pull/3231
#3223
> [IcPaginationBar]: V3 cherry-pick -- itemsPerPage select fix

- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
Update the screen reader text on data table to use column title instead of key when sorting columns
#3015
> 3015 improve screen reader functionality for sorted columns

- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
> Cherry pick screen reader update data table sorted column

- packages/docs/docs.json
Docs update missed from a previous commit
N/A
> docs(docs): docs update missed from previous commit

- packages/canary-docs/CHANGELOG.md
- packages/canary-react/CHANGELOG.md
- packages/canary-web-components/CHANGELOG.md
- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
Squashed v3 changelogs into one log for v3 release
#2998
> 2998 update changelogs for v3 release

- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.stories.js
- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
Update checkbox so that it works correctly on rtl pages
N/A
> Update checkbox for right to left pages

- packages/web-components/src/components/ic-link/ic-link.css
> fix(web-components): fixed open in new icon colour on certain browsers

- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.stories.js
> feat(web-components): v2 web-comps release bump

- audit-ci.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Increase audit expiry dates to April
> ci(root): Audit Date Bump

- audit-ci.json
- packages/web-components/package-lock.json
Cherrypicked auit-ci.json fix
Didn't cherrypick all the package bumps because when i run audit:fix it removes web-components as a dependency from our other packages and i'm not sure if that's something we want
> V3 Cherrypick 0325 v3 audit fix 

- packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.js
- packages/web-components/src/components/ic-radio-option/ic-radio-option.css
Styling for RTL characters in ic-radio-option
> feat(web-components): styling for RTL characters in ic-radio-option

- package-lock.json
- packages/react/package-lock.json
Updates axios package version to 1.8.2 to fix audit issue
N/A
> V3 audit fix - axios

- package-lock.json
- packages/react/package-lock.json
Updates axios package version to 1.8.2 to fix audit issue
N/A
> Audit fix - update axios package

- README.md
Dont use shorthand for repository
N/A
> chore(root): change abbreviation of "repo"

- README.md
Cherry-pick of https://github.com/mi6/ic-ui-kit/pull/3307
N/A
> chore(root): change abbreviation of "repo" in readme.md

- packages/react/src/stories/ic-back-to-top.stories.js
Changed React story name slightly (with "feat" commit) to bump React version to match the web components version - for the release
N/A
> React version bump - small change to story name

- packages/web-components/src/components/ic-skip-link/test/__snapshots__/ic-skip-link.spec.ts.snap
Update skip link spec tests after stencil upgrade
N/A
> Fix skip link tests

- packages/canary-react/.storybook/preview.js
- packages/canary-web-components/.storybook/preview.js
- packages/nextjs/.storybook/preview.js
- packages/react/.storybook/preview.js
- packages/react/src/stories/ic-divider.stories.js
- packages/web-components/.storybook/preview.js
- packages/web-components/src/components/ic-divider/ic-divider.stories.js
Updates storybook dark mode background color to match figma (#17191c)
N/A
> Storybook dark mode background

- packages/canary-web-components/package-lock.json
Updates vite package to fix audit failure
N/A
> chore(canary-web-components): updates vite to fix audit issue

- .github/workflows/add-qa-link-to-issues.yml
Update PR comment workflow file to be in sync with develop
N/A
N/A
> chore(root): update PR comment workflow file to be in sync with develop

- CONTRIBUTING.md
Makes the `CONTRIBUTING.md` file a bit nicer
N/A
> chore(root): use console when viewing shell code

- packages/web-components/src/components/ic-text-field/ic-text-field.tsx
Added fix to blur text field to prevent numeric text field input being modified by scroll.
#2549
> fix(web-components): fix to prevent numeric text field being modified by scroll

- audit-ci.json
- package-lock.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
Updated package dependencies and audit-ci file after an audit fix
> Audit fix v2 31 3

- audit-ci.json
- package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
Updated packages and audit-ci after audit fix
> Audit fix v3 31 3

- packages/canary-web-components/package-lock.json
> Update canary web audit

- packages/canary-react/.storybook/preview.js
- packages/canary-web-components/.storybook/preview.js
- packages/nextjs/.storybook/preview.js
- packages/react/.storybook/preview.js
- packages/web-components/.storybook/preview.js
Update storybook config to sort docs and playground stories first
#3069
> 3069 storybook sort stories for improved visibility of playgrounds

- packages/canary-react/.storybook/preview.js
- packages/canary-web-components/.storybook/preview.js
- packages/nextjs/.storybook/preview.js
- packages/react/.storybook/preview.js
- packages/web-components/.storybook/preview.js
Update storybook config to sort docs and playground stories first - cherry pick of #3383 
#3069
> 3069 cherry pick

- packages/web-components/src/components/ic-hero/ic-hero.css
Update hero to use --ic-hero-background token
#3369
> 3369 ic hero background token unused

- packages/web-components/src/global/color-mode.css
Update data table row hover colours for dark mode to match design
#3022
> 3022 hover state on striped rows barely visible in dark mode

- packages/web-components/src/components/ic-page-header/ic-page-header.tsx
- packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap
- packages/web-components/src/components/ic-page-header/test/basic/ic-page-header.spec.ts
Remove redundant "navigation landmark" from the <nav> aria label on the ic-page-header (used with slotted tabs).
The aria label is `myHeading page sections` using the heading prop if used or the slotted heading `textContent` if not.
Unit test added to ensure this aria label is correct when a slotted heading is used.
#3120
> fix(web-components): fix ic-page-header nav element aria label

- packages/react/src/component-tests/IcClassificationBanner/IcClassificationBanner.cy.tsx
- packages/web-components/src/components/ic-classification-banner/ic-classification-banner.tsx
- packages/web-components/src/components/ic-classification-banner/test/basic/ic-classification-banner.spec.ts
Correct the formatting of the OFFICIAL-SENSITIVE classification level in the classification banner component. The [Government Security Classification Policy (GCSP) specifies that OFFICIAL documents with the SENSITIVE marking should be marked OFFICIAL-SENSITIVE](https://www.gov.uk/government/publications/government-security-classifications/guidance-11-working-at-official-html#:~:text=%2D%20You%20should%20mark%20all%20information%20with%20%E2%80%9COFFICIAL%2DSENSITIVE%E2%80%9D%20in%20the%20header%20and%20footer.)
This change has no effect on developers as the classification banner component API has not been changed. It already took `official-sensitive` as the classification parameter - this just changes the way it is rendered to match.
No related issue.
> fix(web-components): correct formatting of OFFSEN in classification banner

- packages/canary-docs/docs.json
- packages/canary-web-components/src/components/ic-date-picker/readme.md
Updated readme and canary-docs to add missing style tokens for ic-date-picker
> Update date picker readme

- README.md
- packages/web-components/bootstrap_window.ts
- packages/web-components/stencil.config.ts
Adds build metadata for customers.
#2428
> feat: add build metadata

- packages/react/package-lock.json
Updates http-proxy-middleware package to resolve audit issue
N/A
> v2 audit fix

- README.md
Since the icds logo is center aligned it makes sense to center align the repo name and badges.
N/A
> chore(root): center align

- packages/canary-docs/docs.json
- packages/canary-react/src/stories/ic-date-input.stories.js
- packages/canary-web-components/src/components.d.ts
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.stories.js
- packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
- packages/canary-web-components/src/components/ic-date-input/readme.md
- packages/canary-web-components/src/components/ic-date-input/test/basic/__snapshots__/ic-date-input.spec.tsx.snap
- packages/canary-web-components/src/components/ic-date-input/test/basic/ic-date-input.spec.tsx
Emit UTC date from icChange in date input.
Update snapshot file due to breaking tests.
Update console.log in stories to show UTC format as well as original date value.
#3142
> 3142 ic date input add support for utc format in icchange event output

- audit-ci.json
Adds to allowlist for react router version and updates dates
N/A
> chore(root): adds to audit allowlist

- packages/codemod/README.md
- packages/react/README.md
Update readme file to remove @next from install instructions
https://github.com/mi6/ic-design-system/issues/1262
> Remove next from install instructions

- packages/canary-docs/README.md
- packages/canary-react/README.md
- packages/canary-web-components/README.md
- packages/codemod/README.md
- packages/docs/README.md
- packages/fonts/README.md
- packages/nextjs/README.md
- packages/react/README.md
- packages/web-components/README.md
Added 'feat' scoped commits to trigger an increment in versions on all our packages
> V3 version increments

- packages/docs/CHANGELOG.md
- packages/fonts/CHANGELOG.md
- packages/nextjs/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/web-components/CHANGELOG.md
changelog update to group changes under 3.1.0
N/A
> Changelog update

- packages/react/README.md
minor change to react readme to trigger v2 version increment
Minor feat scoped commit for react, to help increment version number
> feat(react): minor feat for v2 release

- packages/web-components/src/components/ic-button/ic-button.stories.js
fixes issue with loading story in storybook - minor typo was causing the loading variant to not be displayed
N\A
> Fixes storybook loading buttons example

- packages/docs/docs.json
- packages/web-components/src/components.d.ts
- packages/web-components/src/components/ic-skip-link/ic-skip-link.tsx
- packages/web-components/src/components/ic-skip-link/readme.md
- packages/web-components/src/components/ic-skip-link/test/ic-skip-link.spec.ts
Added `setFocus` method to `ic-skip-link`. Added docs and unit test for the method.
#3491
> 3491 add a setfocus method to the ic skip link

- packages/web-components/src/components/ic-select/ic-select.tsx
Fix the following: loading state cannot be toggled to false, placeholder text has "clear selection" button if loading state is changed to true while select has a value, placeholder text is the wrong colour in loading state if select has value, if select has multiple values, they display as commas in the loading state
<table>
<tr>
<td></td>
<th>Select</th>
<th>Searchable select</th>
<th>Multi-select</th>
</tr>
<tr>
<th>Toggling loading prop to false doesn't show results</th>
<td>Present in storybook</td>
<td>Present in storybook</td>
<td>Present in storybook</td>
</tr>
<tr>
<th>"Clear selection" button next to placeholder text if loading is changed to true while value is selected</th>
<td>Present in storybook and stackblitz</td>
<td>Not present</td>
<td>Present in storybook and …
> fix(web-components): fix select loading state bugs

- TESTING.md
> chore(root): use correct lang in preview

- check-audit-expiry.js
Removes an extra access to each of the audit objects, saves a bit cost in the CI.
N/A
> chore(root): use different for loop in audit script

- packages/canary-web-components/src/utils/constants.ts
- packages/canary-web-components/src/utils/helpers.ts
- packages/canary-web-components/src/utils/types.ts
Brings files back in sync with files in web-components package. Should make future moving of components out of canary easier
N/A
> refactor(canary-web-components): brings files back in sync with core version

- packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
- packages/web-components/src/components/ic-search-bar/test/basic/ic-search-bar.spec.ts
- Removed icChange call from componentWillLoad by extracting out other necessary code into seperate function.
- Cleared IDE warnings for missing prop values
> fix(web-components): removed icChange event from componentWillLoad

- audit-ci.json
updates dates for audit exceptions
N/A
> chore(root): update of dates for audit

- audit-ci.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
Updated package-locks and audit-ci following an audit fix
> Audit fix v2 28 05

- audit-ci.json
Applies recent audit allowlist changes to v2 codebase
N\A
> v2 audit updates

- audit-ci.json
updates to audit allow list for webpack-dev-server
N/A
> chore(root): updates to audit allow list

- packages/web-components/src/components/ic-popover-menu/ic-popover-menu.css
Fixes animations that were not working for popover menu
#3616
> fix(web-components): fixes popover menu slide in animation

- .github/scripts/scope-check.js
Update commitlint script to accept release commit - only affects develop to main PR after the release pipeline has been run.
> fix(root): update commitlint script to accept release commit

- .github/workflows/ic-ui-kit-branches.yml
Update "Branches" workflow file to include check for uncommitted changes to auto-generated files (e.g. docs.json).
The code has been copied from PR #3758 - where it was added to the release workflow. Adding this check at a PR / branch level will help capture any required changes before the release happens to help make the release process quicker.
#3641
> ci(root): update 'Branches' workflow to include uncommitted changes check

- .github/workflows/ic-ui-kit-branches.yml
Temporarily remove uncommitted changes check from "Branches" workflow (until we sort out issue with differing docs.json whitespace characters)
N/A
> Temporarily remove uncommitted changes check from Branches workflow

- packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx
- packages/canary-react/src/stories/ic-data-table.stories.js
- packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.js
- packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
- packages/canary-web-components/src/components/ic-data-table/story-data.ts
- packages/canary-web-components/src/components/ic-data-table/test/basic/ic-data-table.spec.tsx
The current implementation of the actionElement and actionOnClick fields being passed in via data means there is a limit on what can go into that field, because there is both a clickable button and an icon in the actionElement next to each other, then clicking on the icon will trigger the actionOnClick even though it was only supposed to be used for the button. This is both a usability and an accessibility issue.
This change means that whole components can be passed in with their original functionality intact, and the data input for the actionElement is being removed for not meeting our needs.
Note: This is an alternative solution to the deprecated solution that was implemented in the following V2 branch:
https://github.com/mi6/ic-ui-kit/pull/3723
> Slotted actionElement solution in IcDataTable

- package-lock.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/react/package-lock.json
- packages/web-components/package-lock.json
Bump versions in package-lock files with audit fix
> Audit fix 220525

- packages/canary-react/src/stories/ic-date-input.stories.js
- packages/canary-react/src/stories/ic-date-picker.stories.js
- packages/react/src/stories/ic-checkbox.stories.js
- packages/react/src/stories/ic-radio-group.stories.js
- packages/react/src/stories/ic-select_(multi).stories.js
- packages/react/src/stories/ic-select_(searchable).stories.js
- packages/react/src/stories/ic-select_(single).stories.js
- packages/react/src/stories/ic-text-field.stories.js
- packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.stories.js
- packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.js
- packages/web-components/src/components/ic-select/ic-select_(multi).stories.js
- packages/web-components/src/components/ic-select/ic-select_(searchable).stories.js
- packages/web-components/src/components/ic-select/ic-select_(single).stories.js
- packages/web-components/src/components/ic-text-field/ic-text-field.stories.js
Following a change I made in https://github.com/mi6/ic-ui-kit/pull/3779. This prevents having a weird looking empty radio/select option, instead it will show a validation status option of no status.
N/A
> Update validation status playgrounds

- audit-ci.json
- packages/canary-react/package-lock.json
- packages/canary-web-components/package-lock.json
- packages/nextjs/package-lock.json
- packages/react/package-lock.json
Update dates in audit-ci.json and run npm audit:fix
> Audit fixes

- packages/web-components/comps-list.ts
Update component list to exclude action chip from canary
N/A
> Fix action chip build

- packages/web-components/src/components/ic-checkbox/ic-checkbox.css
When the label of an ic-checkbox is very long it wraps onto the next line. When this happens, it no longer left-aligns properly and becomes overlaid by the checkbox focus indicator:
This CSS fix prevents this from happening:
N/A
> Fix alignment of long labels in ic-checkbox

- packages/react/src/stories/ic-back-to-top.stories.js
- packages/web-components/src/components/ic-back-to-top/ic-back-to-top.stories.js
- packages/web-components/src/components/ic-footer/ic-footer.stories.js
- packages/web-components/src/components/ic-hero/ic-hero.stories.js
- packages/web-components/src/components/ic-section-container/ic-section-container.stories.js
- packages/web-components/src/components/ic-toggle-button/ic-toggle-button.stories.js
Added playground to storybooks for back-to-top, footer, hero, section container and toggle button
web components
#2063
> 2063 duplicate playground storybooks in web components

- packages/web-components/src/components/ic-chip/ic-chip.css
- packages/web-components/src/components/ic-chip/ic-chip.tsx
fix the dismissible chips leaving gap behind after being dismissed
fix #3549
> fix(web-components): fix dismissible chips leaving gap behind

- packages/canary-react/src/component-tests/IcTimeInput/IcTimeInput.cy.tsx
- packages/canary-web-components/src/components/ic-time-input/ic-time-input.tsx
- packages/canary-web-components/src/components/ic-time-input/test/basic/ic-time-input.spec.tsx
Updates time input to fix issue with 12 hour input incorrectly showing hours as 0-11
#3960
> Time input 12 hour

- .husky/pre-commit
Updates pre-commit hooks to remove cypress tests which fail locally
#3975
> chore(root): updates pre-commit hooks to remove visual tests

- audit-ci.json
- packages/react/package-lock.json
updates tar-fs package and adds to allow list for audit issue
N/A
> tar-fs audit fix

- packages/web-components/src/components/ic-dialog/ic-dialog.tsx
Fixes ic-dialog infinite loop issue in Jest tests
#3660 
Tested against ui-kit-test-app which previously showed the errors mentioned in the associated issue
> fix(web-components): fixes ic-dialog infinite loop issue in Jest tests
