packages/web-components/src/components/ic-footer-link/ic-footer-link.css
Make footer link have white text when light and active
#84
=> fix(web-components): fix light footer link turning blue

packages/web-components/src/components/ic-alert/ic-alert.css
Removed circle styles that clashed with icon button shadow styles
=> fix(web-components): remove clashing button styles from dismissable alert

packages/web-components/src/components/ic-breadcrumb/ic-breadcrumb.css, packages/web-components/src/components/ic-button/ic-button.css, packages/web-components/src/components/ic-card/ic-card.css, packages/web-components/src/components/ic-checkbox/ic-checkbox.css, packages/web-components/src/components/ic-footer-link-group/ic-footer-link-group.css, packages/web-components/src/components/ic-footer-link/ic-footer-link.css, packages/web-components/src/components/ic-input-component-container/ic-input-component-container.css, packages/web-components/src/components/ic-link/ic-link.css, packages/web-components/src/components/ic-menu/ic-menu.css, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css, packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css, packages/web-components/src/components/ic-radio-option/ic-radio-option.css, packages/web-components/src/components/ic-select/ic-select.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css, packages/web-components/src/components/ic-tab-group/ic-tab-group.css, packages/web-components/src/components/ic-tab/ic-tab.css, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css, packages/web-components/src/global/variables.css
Adds outline token to be used for windows high contrast mode
=> feat(web-components): adds focus borders for high contrast mode

packages/web-components/src/components/ic-search-bar/ic-search-bar.spec.ts, packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx, packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
Added "no results" state to search bar variant with disabled filter, fixed z-index of tooltips on clear and search buttons, stopped icSubmitSearch being emitted when enter pressed while search button showing as disabled, set text of ARIA live region to emptyOptionListText when no results are found (was previously being set to "1 result available"), stopped live region updating when menu not displayed due to charactersUntilSuggestions prop.
I have checked this by importing it into the guidance site locally. Another way this can be tested is to not pass any options to it and it should display "No results found"
#111
=> feat(web-components): add "no results" state to search bar variant with disabled filter

packages/web-components/src/components/ic-alert/ic-alert.css, packages/web-components/src/components/ic-classification-banner/ic-classification-banner.css, packages/web-components/src/components/ic-footer/ic-footer.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css, packages/web-components/src/components/ic-status-tag/ic-status-tag.css, packages/web-components/src/components/ic-switch/ic-switch.css, packages/web-components/src/components/ic-tooltip/ic-tooltip.css, packages/web-components/src/global/variables.css
Add transparent borders in HCM to alert, classification banner, footer, side nav, status tags, switch, and tooltips.
91 on design system
=> fix(web-components): add transparent borders in HCM

packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
Added -webkit-hyphens property to define behaviour on safari
[138](https://github.com/mi6/ic-ui-kit/issues/138)
=> fix(web-components): removed hyphenated title on Safari

packages/web-components/src/components/ic-button/ic-button.css
Set outer colour of loading indicator to transparent when part of loading buttons
#5
=> Set outer colour of loading indicator to transparent when part of loading buttons

packages/web-components/src/components/ic-theme/ic-theme.spec.tsx, packages/web-components/src/components/ic-theme/ic-theme.stories.mdx, packages/web-components/src/components/ic-theme/ic-theme.tsx, packages/web-components/src/global/variables.css, packages/web-components/src/utils/helpers.ts, packages/web-components/src/utils/types.ts
Update theme to use rgba that can either be set by user, or sets to 1 for hex and rgb inputs.
#4
=> fix(web-components): add rgba themes

packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.css, packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.spec.ts, packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.tsx, packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.types.tsx
Using SVG to add rounded corners to loading indicator. Psuedo elements are no longer required as stroke-linecap on SVG works. Also updated code to only display necessary linear or circular inline styling
#118
=> fix(web-components): switching out svg for rounded circular determinate indicator

packages/web-components/src/components/ic-theme/ic-theme.tsx, packages/web-components/src/global/variables.css, packages/web-components/src/utils/constants.ts, packages/web-components/src/utils/helpers.ts
Updated foreground colour calculations - updated dark mode threshold and changed -1000 to -10000 as foreground colour was sometimes showing as grey because this number wasn't large enough to bring it over 255, ran prettier:fix, added colour contrast check to ic-theme component which creates a console warning if the chosen colour has a colour brightness which is too close to being halfway between that of the black and white foregound colours - and therefore not a high enough contrast.
#3
=> fix(web-components): updated foreground colour calculations, added colour contrast check

packages/web-components/src/components/ic-alert/ic-alert.css
Now applies correct colour to icon when JavaScript disabled.
=> fix(web-components): fixes alert styling when javascript disabled

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-step/ic-step.tsx, packages/web-components/src/components/ic-tab-panel/ic-tab-panel.tsx, packages/web-components/src/components/ic-tab/ic-tab.tsx, packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
Removes required(!) decorator to fix errors appearing in console. Not needed as parent components set the props
#193
=> feat(web-components): removes required flag for internal props

packages/web-components/src/utils/helpers.ts
In ic-top-navigation, navigation-button contained an ic-button so would call the getThemeFromContext, and would have its parent checked. Since it was the parent of a shadow component, el.parentElement returns null causing the error.
My changes add an additional piece of code when it is null to get the shadow parent element, in order to find its actual parent.
7 (In ic-design-system)
=> Fix console error

packages/react/package.json
Node 'NCP' package requires the file name to be added to the copy command. This PR adds the file name in the command. Previously, the core.css file was not being regenerated.
#206
=> fix(react): updated css copy script

packages/react/src/stories/ic-radio-group.stories.mdx
Import text field into react radio examples to fix conditional examples not displaying
#221
=> fix(react): import text field into react radio examples

packages/react/src/index.ts, packages/react/src/react-component-lib/slottedSVG.tsx
Add slotted svg component to react library in order to remove remove error that appears in typescript applications.
Tested by packing this work, and replacing the current slotted SVG in the design system with the slotted svg imported from this work. Everything seems to work as normal.
#280
=> feat(react): add slotted svg component to react library

packages/web-components/src/components/ic-search-bar/ic-search-bar.e2e.ts, packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Fixes debounce prop not working, which caused icChange event to emit immediately.
- No longer need to watch changes to debounce prop of ic-search-bar
- The debounce value is passed to ic-text-field
- icChange and icInput are emitted from ic-text-field. Due to the way Stencil scopes events in the shadowDOM, they appear to consumers as if they are emitted by the parent component
- debounceAriaLiveUpdate was incorrectly updating the debounce prop, instead of using private state. This means the debounce prop no longer needs to be mutable.
- Adds e2e test
#295
=> fix(web-components): fixes searchbar debounce prop

.github/workflows/update-visual-regression-tests.yml, package.json
Adds a manual github action to update loki visual regression test reference images.
#200
=> Add loki visual test update github action

packages/web-components/src/components/ic-classification-banner/ic-classification-banner.spec.ts, packages/web-components/src/components/ic-classification-banner/ic-classification-banner.tsx
The contentinfo role on the classification banner caused an accessibility violation when used alongside a footer so has been removed.
The contentinfo role on the classification banner caused an accessibility violation when used alongside a footer so has been removed.
#317
=> Remove contentinfo role from classification banner

packages/web-components/src/components/ic-select/ic-select.css, packages/web-components/src/components/ic-text-field/ic-text-field.css, packages/web-components/src/components/ic-text-field/ic-text-field.stories.mdx
Add width: 100% to select and text field host to fix full width not working when wrapped in display:flex
To test, wrap the full width example in 
`<div style='display: flex'></div>`
#315
=> add width: 100% to select host to fix full width not working with flex

packages/react/src/react-component-lib/slottedSVG.tsx
Now possible to pass child elements to the component as an alternative to path prop
=> feat(react): enchances slottedsvg component

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-chip/ic-chip.tsx, packages/web-components/src/components/ic-chip/readme.md
Update chip to use icDismiss event and deprecate current dismiss event
N/A
=> fix(web-components): update dismiss to icDismiss for chip component

.github/workflows/check-pr-target.yml
Changes PR target to develop if it is incorrectly set to main. This means that any dependabot PRs will automatically get changed to develop
#2
=> build(root): sets PR target to develop if set to main

packages/react/package-lock.json, packages/web-components/package-lock.json, packages/web-components/src/components/ic-page-header/ic-page-header.tsx
Add condition that checks if actions slot is being used before running the reverseOrder function.
This is to prevent the console error that appears when the reverseOrder prop is used but the actions
slot is empty
Update package-locks
#354
=> Change reverse order functionality so it only works when the action slot is used

packages/react/src/stories/ic-top-navigation.stories.mdx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/components/ic-top-navigation/readme.md
Add a slot for use of router links for top navigation app title, and update app title prop to not be required, but still show the console error if a top nav has no app title or slotted app title link.
Updated the react router story to use a routed app title.
#179
=> Allow use of gatsby or any slotted links for app title link in top nav

packages/web-components/src/components/ic-text-field/ic-text-field.tsx
Prettier update for ic-text-field which has prevent the build since prettier step added to pipeline. 
N/A
=> [ix-text-field]: Prettier formating fix

packages/react/src/stories/ic-side-navigation.stories.mdx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-side-navigation/readme.md
Update app title to allow for slotted links for side nav.
Update React Router story to use slotted app title.
#376
=> 376 Allow use of slotted link for app title for side navigation

.github/workflows/ic-ui-kit-branches.yml, .github/workflows/ic-ui-kit-develop.yml
Concurrency action has been moved from the deployment step to the overall action. This will make sure the latest codebase of the branch is being built. Updated concurrency for QA and develop due to the high volume of builds.  As part of the investigation, there was a requirement to update the concurrency property on `pages-build-deployment` action provided by GitHub Pages by default but it is not accessible.
https://github.com/mi6/ic-design-system/issues/6
=> [github-action]: fix(root): updated concurrency step for qa deployments

packages/web-components/src/components/ic-classification-banner/ic-classification-banner.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css, packages/web-components/src/global/variables.css
Items and components from other DS were appearing above the expanded drawer of ic-side-nav, a new Z-index has been applied which stops this behaviour. Also z-index variable added.
#322
=> fix(web-components): updated side navigation z-index

packages/web-components/src/components/ic-tab-panel/ic-tab-panel.css
Added `:host([hidden])` `display:none` to `ic-tab-panel` as the hidden attribute was previously getting it's styling from normalize.css. If normalize.css is not provided, the tab component appears broken. This is to remove the reliance on normalize.css
N/A
=> fix(web-components): added hidden style to ic-tab-panel

packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css
Fixes z-index issue when top nav contains navigation groups
#375
=> fix(web-components): fixes z-index on top nav dropdown

packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
Fixed gap appearing under nav items with slotted `<a>`s (e.g. in React router story) - caused by changes made during horizontal scroll work.
=> fix(web-components): fix gap appearing under slotted nav items

packages/web-components/src/components/ic-page-header/ic-page-header.css, packages/web-components/src/components/ic-page-header/readme.md
Fixes an issue with previous changes to z-index of page header. It only worked for sticky prop and not stickyDesktopOnly
#391
=> fix(web-components): fixes page header z-index issue

packages/web-components/src/components/ic-top-navigation/ic-top-navigation.e2e.ts
Updated top nav e2e flaky test. The `ic-navigation-group` selector needed updating as it was appearing outside of the ShadowDOM. This PR fixes this test: https://github.com/mi6/ic-ui-kit/actions/runs/4374871463/jobs/7654841381#step:5:694
N/A
=> fix(web-components): updated top-navigation e2e test

packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-select/ic-select.e2e.ts, packages/web-components/src/components/ic-select/ic-select.stories.mdx
Moved the calculations which were setting the scroll bars from componentDidLoad to componentDidRender because a re-calculation was required if the options where initially `[]`. compontnDidLoad was only triggered once so any data which populated options after a request or update was not re-calculated for the scroll bar
#501
=> fix(web-components): moved scroll bar calculations to componentDidRender

packages/web-components/src/components/ic-select/ic-select.spec.tsx, packages/web-components/src/components/ic-select/ic-select.tsx
Updated default value functionality as there are use cases where the options are initially set to [] and then populated after a useEffect or setTimeout. By moving the method to componentWillRender, the scroll bar calculations will happen more frequently and when the menu is open. It was initially running within componentWillLoad which only runs on initial load.
#456
=> fix(web-components): updated default value functionality

packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Add check to search isSubmitDisabled for if the value length is too low (less than charactersUntilSuggestion), so that the submit button isn't enabled on initial value
#363
=> fix(web-components): add extra check to search isSubmitDisabled

packages/react/src/stories/ic-select.stories.mdx, packages/web-components/src/components/ic-select/ic-select.spec.tsx, packages/web-components/src/components/ic-select/ic-select.stories.mdx, packages/web-components/src/components/ic-select/ic-select.tsx
Fixes issue where `IcChange` event was not emitting on a delay when `debounce` prop set and using the arrow keys to navigate the items in the dropdown.
This change means that it is no longer necessary to set the `value` prop in an IcChange handler. it can still be done, but will not have any effect as the value will match the internal state in the component
#461
=> Fixes select IcChange debounce when using arrow keys

packages/web-components/src/components/ic-select/__snapshots__/ic-select.spec.tsx.snap, packages/web-components/src/components/ic-select/ic-select.css, packages/web-components/src/components/ic-select/ic-select.tsx
Fixes styling & interaction after removing disabled prop. Styles are now applied based on classes being applied to the host rather than relying on the prop\attribute.
#548
=> fix(web-components): fixes changing disabled prop

packages/web-components/src/components/ic-breadcrumb/ic-breadcrumb.css, packages/web-components/src/components/ic-card/ic-card.css, packages/web-components/src/components/ic-footer-link/ic-footer-link.css, packages/web-components/src/components/ic-link/ic-link.css
Replace text-decoration-thickness and text-underline-offset with border-bottom for breadcrumb, card, footer link, and links so that all browsers provide the correct hover state
#508
=> fix(web-components): replace underline thickness and offset for some components

.github/workflows/ic-ui-kit-branches.yml
Added additional trigger events on CI build so tests can be run on forked repos which are contributing to base develop branch. Hopefully this change will enable the 'Approve and run' functionality (https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). 
The update includes adding a build trigger when a PR has been:
- Opened
- Reopened
- Edited
This update should work in unison with the default 'push' to branch trigger. There is a particular instance where 'skipped' will appear within the checks:
- If a 'push' tagged build in ongoing and a PR is created.
Also, if a 'push' tagged build is run and complete and a PR is created afterwards, the build will run again tagged as 'pull_request'. 
N/A
=> chore(root): updated branch CI workflow to run tests on contributor code

packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-search-bar/ic-search-bar.e2e.ts, packages/web-components/src/components/ic-search-bar/ic-search-bar.spec.ts, packages/web-components/src/components/ic-select/__snapshots__/ic-select.spec.tsx.snap, packages/web-components/src/components/ic-select/ic-select.e2e.ts, packages/web-components/src/components/ic-select/ic-select.spec.tsx, packages/web-components/src/components/ic-select/ic-select.tsx
aria-owns and aria-controls was unable to link to the UL element within ic-menu due to shadow DOM encapsulation. Instead of restructuring the component, scoped worked.
Checked against accessibility scanner 'Equal Access Accessibility Checker' chrome plugin
#484
=> fix(web-components): removed shadow DOM from ic-menu for a11y fixes

packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
Fixes tooltips not displaying for secondary nav items. 
#463
=> fix(web-components): fixes tooltips on side navigation items

packages/web-components/src/components/ic-navigation-button/ic-navigation-button.css
Update navigation buttons to have 100% height so that focus doesn't appear cut off on small breakpoints
#598
=> fix(web-components): update navigation buttons to have 100% height

packages/web-components/src/components/ic-hero/ic-hero.css
Added flex-wrap: wrap to stack buttons if IcHero is zoomed in 200%+
Screenshots can be found in #594 
#594
=> fix(web-components): added wrap to interaction-container to stack buttons/links zoomed in

packages/web-components/src/components/ic-select/ic-select.tsx
…added to DOM
`initialRender` is now no longer required. Was affecting a bug where menu was opening unintentionally on conditional render so removed that aswell
#591
=> fix(web-components): removed initialRender

.github/workflows/ic-ui-kit-branches.yml
Added `synchronize` to the action trigger so updated PRs will require 'approve and run' to continuiously run checks. Also added ternary to deploy step so it is not run during check for external contributors
#627
=> fix(root): updating github actions for external contributions

packages/web-components/src/components/ic-navigation-menu/ic-navigation-menu.css, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx
Add overlay to pages when top navigation pop out menu is open to ensure the rest of the page is not responsive
#621
=> fix(web-components): add overlay to pages when top navigation pop out menu is open

.github/workflows/ic-ui-kit-branches.yml
Additional check on deploy step to run if event name is push. This should not be possible for external contrributors. Their build trigger is invoked from the pull_request trigger. Push event should be triggered from internal PRs
#629
=> fix(root): updated github action to check event name

packages/web-components/src/components/ic-popover-menu/ic-popover-menu.spec.ts, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
fixed keyboard closing of popover menu when other elements feature on a page
#564
=> fix(web-components): fixed closing of popover menu

packages/web-components/src/components/ic-select/ic-select.spec.tsx, packages/web-components/src/components/ic-select/ic-select.tsx
Return out of onBlur for select if scrollbar/group title is clicked to ensure the menu stays open
#596
=> fix(web-components): return out of onBlur for select if scrollbar/group title is clicked

packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx
Updated aria-hidden to false due to interactive close button inside menu. Error appearing within Lighthouse Accessibility report should now be fixed.
N/A
=> fix(web-components): updated aria-hidden on mobile menu button

packages/web-components/src/components/ic-tab-context/ic-tab-context.e2e.ts, packages/web-components/src/components/ic-tab-context/ic-tab-context.spec.ts, packages/web-components/src/components/ic-tab-context/ic-tab-context.tsx, packages/web-components/src/components/ic-tab-context/ic-tabs.stories.mdx, packages/web-components/src/components/ic-tab-panel/ic-tab-panel.tsx, packages/web-components/src/components/ic-tab/ic-tab.tsx
Added stopImmediatePropagate method to prevent icTabSelect event bubbling up outside of its own context. For example, nested tab event should not trigger events within the parent tab component
#684
=> fix(web-components): added stopImmediatePropagation to icTabSelect

packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
Replaced box-shadow with ::after to style selected state. This removes the curved underline when navigation item has focus state. Tested with React Router (slotted) example
#537
=> fix(web-components): replaced box-shadow for page-header selected nav item

packages/web-components/src/components/ic-menu-group/__snapshots__/ic-menu-group.spec.ts.snap, packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx
Add condition to menu item aria label so it doesn't read undefined menu group when menu group has no label
#656
=> fix(web-components): add condition to menu item aria label so it doesn't read undefined menu group

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-pagination/ic-pagination.spec.ts, packages/web-components/src/components/ic-pagination/ic-pagination.tsx, packages/web-components/src/components/ic-pagination/readme.md
Adds a public method to the pagination component to allow current page to be set.
#707
=> feat(web-components): adds method to set current page to pagination

packages/web-components/src/components/ic-typography/__snapshots__/ic-typography.spec.ts.snap, packages/web-components/src/components/ic-typography/ic-typography.tsx
Add aria-hidden to see more/see less typography as the screen reader reads out the whole text.
#712
=> fix(web-components): add aria-hidden to see more/see less typography

packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
Fixed static side navigation falling off screen. Adjusted padding for static variant.
To test this, add a lot of text / a large div to the page in the static variant story so that the page is scrollable and then scroll down.
Other issues mentioned in the [comment on the ticket](https://github.com/mi6/ic-ui-kit/issues/700#issuecomment-1571584355) are being made into tickets.
#700
=> fix(web-components): fix static side navigation falling off screen

packages/web-components/src/components/ic-button/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
Fixes issue with events being created by popperjs for tooltip
ic-tooltip is no longer added to DOM for icon buttons if `disableTooltip ` is `true`
resize & scroll event listeners are no longer added to tooltips
#788
=> fix(web-components): fixes memory leak in ic-button\ic-tooltip

packages/web-components/src/components/ic-navigation-group/ic-navigation-group.spec.ts, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.e2e.ts
Group-navigation has been changed to apply new WCAG features;
.5 second delay when hovering a grouped-nav-item (when mouse is idle) before dropdown.
delay not applied when mouse enters sibling grouped-nav-item.
dropdown can be cancelled with escape, space or enter (without focus).
.5 second delay after mouse leaves grouped-nav-item before dropdown is closed
#674
=> Group nav changes

packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
Fix resizeObserver calculation for top nav height to remove extra padding so that it works at any resize rather than just resizing between set screen sizes.
#785
=> 785 side navigation padding issue at small screen size

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-select/ic-select.e2e.ts, packages/web-components/src/components/ic-select/ic-select.spec.tsx, packages/web-components/src/components/ic-select/ic-select.tsx
Searchable IcSelect now keeps suggestions after typing and then closing\reopening menu
#704
=> fix(web-components): fix suggestions after typing

audit-ci.json, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-card/ic-card.tsx, packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.tsx, packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx, packages/web-components/src/components/ic-chip/ic-chip.tsx, packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx, packages/web-components/src/components/ic-pagination-item/ic-pagination-item.tsx, packages/web-components/src/components/ic-pagination/ic-pagination.tsx, packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx, packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx, packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx, packages/web-components/src/components/ic-switch/ic-switch.tsx, packages/web-components/src/components/ic-tab-context/__snapshots__/ic-tab-context.spec.ts.snap, packages/web-components/src/components/ic-tab/ic-tab.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx, packages/web-components/src/utils/helpers.ts
Remove disabled attribute from components when disabled is false so that it doesn't get passed down to the native element causing dimmed to be read by screen readers
#799
=> fix(web-components): remove disabled attribute from components when disabled is false

.github/workflows/ic-ui-kit-branches.yml
Replaced push trigger with workflow dispatch to run development bilds manually. This will also prevent duplicate builds during the PR stage
N/A
=> ci(root): removed push trigger and replaced with workflow_dispatch

packages/web-components/src/components/ic-select/ic-select.e2e.ts
Added page.waitForChanges to flaky select test. Removed unnecessary test button which is also rendered to make sure it is not affecting the behaviour being tested at all (may be interfering with the tabbing? But not needed anyway)
I wasn't getting the E2E tests failing at all so no idea if this will stop it failing sometimes for others. If anyone has any other ideas to improve it further then let me know :)
#694
=> Update flaky select test to try and stop it failing

packages/web-components/src/components/ic-select/ic-select.tsx
Add removeDisabledFalse helper to select to ensure dimmed isn't read out by a screen reader when disabled="false"
=> fix(web-components): add removeDisabledFalse helper to select

.github/workflows/ic-ui-kit-branches.yml
The deploy step was skipping if run manually via workflow_dispatch. This was due to the if parameter in the deploy step not taking into the account a build being triggered by workflow_dispatch.
N/A
=> ci(root): updated trigger to run if manually triggered

packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx, packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx, packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.tsx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-tab-context/ic-tab-context.tsx
Remove event listeners correctly for breadcrumb group, checkbox, horizontal scroll, side navigation and tab context
#791
=> fix(web-components): remove event listeners

packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
Duplicate a.link styles for div.link on nav items so that when there is no href the label doesn't show when collapsed
#726
=> fix(web-components): duplicate a.link styles for div.link on nav items

packages/web-components/src/components/ic-button/ic-button.css, packages/web-components/src/components/ic-button/ic-button.tsx
Increased width of button by 2rem when it is loading and the icon slot is used (24px for the icon plus the 8px gap).
This can be checked in the 'Playground with icon' story.
When a button is changed from not loading to loading, the width still decreases but to a larger width if it has an icon. This matches the behaviour of buttons when they don't have an icon - they are set to a set width, so not exactly the same width as the button when it isn't loading.
#838
=> Increase width of button when it is loading and has an icon

packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.tsx, packages/web-components/src/components/ic-horizontal-scroll/test/basic/__snapshots__/ic-horizontal-scroll.spec.ts.snap
Add role tab to divs in horizontal scroll to stop axe issue.
I couldn't find an alternative to stop the axe accessibility issues other than to add role="tab" to the left and right arrow button divs, but I've checked in multiple components (page header, top nav, tabs) and it doesn't seem to have a negative affect on anything due to the aria hidden, so I think it should be okay.
#721
=> fix(web-components): add role tab to divs in horizontal scroll

packages/web-components/src/components/ic-button/ic-button.stories.mdx, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-button/test/basic/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-button/test/basic/ic-button.e2e.ts, packages/web-components/src/components/ic-button/test/basic/ic-button.spec.ts, packages/web-components/src/components/ic-dialog/test/basic/ic-dialog.e2e.ts, packages/web-components/src/components/ic-select/test/basic/ic-select.e2e.ts, packages/web-components/src/components/ic-typography/test/basic/ic-typography.e2e.ts, packages/web-components/src/testspec.setup.ts
Fixes aria-describedby not working by allowing it to be set to a sibling element of the ic-button element. When the component loads it creates an element in the shadowDOM with the same id and sets the innerText to match the light DOM element.
A mutationObserver is used to keep the shadowDOM element in sync with the light DOM element, if the text content changes.
#898
=> fix(web-components): fixes ic-button aria-describedby not working

packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-side-navigation/test/basic/__snapshots__/ic-side-navigation.spec.ts.snap
For #739: Updated CSS so that the visibility is handled by just the 'menu-visibility-visible' class instead of in the media query, and remove unused classes in ic-navigation-group CSS.
For #885: Fixed padding so content is pushed to the side the correct amount with static variant.
For #896: Updated transition handlers - re-added functionality for adding / removing classes on transition start.
#739, #885 and #896.
=> Side navigation bug fixes

packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
Update if statement in side navigation code to look for `<div>` if `<a>` not present - for when neither an href or slotted link is used.
I have tested this by console logging the `navItemLink` variable - tested on navigation items with an href, with a slotted link and with neither, and the `<a>` or `<div>` is always found
#863
=> Fix console error in side navigation if no href / slotted link

packages/web-components/src/components/ic-card/ic-card.tsx, packages/web-components/src/components/ic-card/test/basic/__snapshots__/ic-card.spec.ts.snap
conditional render of ic-typogrpahy element when using slot vs message
Update to ic-card message slot structure
#527
=> fix(web-components): ic-card message rendering

.github/workflows/ic-ui-kit-main.yml, packages/docs/package.json, packages/fonts/package.json, packages/react/package.json, packages/web-components/package.json
Remove `--conventional-prerelease` and `--preid=beta` flags from the Lerna command. The removal of these flags transition ICDS from using pre-release versions with the “beta” identifier to adopting regular semantic versioning.
This change will mean that merging it now will remove the prerelease as of the next release.
`npx lerna publish` has no `--dry-run` flag, for testing purposes, the following command would be suffice to test the change: `npx lerna publish --conventional-commits --no-commit-hooks --no-git-tag-version --no-push`, which currently returns:
```js
Changes:
- @ukic/docs: 2.1.0 => 2.2.0
- @ukic/fonts: 2.1.0 => 2.2.0
- @ukic/react: 2.1.0 => 2.2.0
- @ukic/web-components: 2.1.0 => 2.2.0
```
An addition check with `npm run release-check` returns the following:
```js
Changes:
- …
```
=> ci(root): remove pre-release flags to resume semantic versioning

packages/web-components/src/components/ic-pagination/ic-pagination.tsx, packages/web-components/src/components/ic-pagination/test/basic/ic-pagination.spec.ts
Allows the pagination to dynamically update and re-render the number of pages when the pages prop is updated.
#921
=> Dynamic pages update for pagination

packages/web-components/src/components/ic-page-header/ic-page-header.css, packages/web-components/src/global/variables.css
adds new z-index value for sticky page header to prevent select box overlapping
#653
=> Z index not correct for sticky ic page

packages/web-components/package.json
Remove watch from storybook command to fix error when building as it's looking to run a command that no longer exists.
=> chore(web-components): remove watch from storybook command

packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx, packages/web-components/src/components/ic-search-bar/test/basic/__snapshots__/ic-search-bar.spec.ts.snap, packages/web-components/src/components/ic-search-bar/test/basic/ic-search-bar.e2e.ts
only adding aria-owns if the menu is being rendered at the same time
=> fix(web-components): conditionally adding aria-owns to search-bar

packages/web-components/src/components/ic-alert/ic-alert.tsx
titleAbove prop was incorrectly documented.
N/A
=> docs(web-components): fixes error in IcAlert docs

packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx
Ic Tooltip would, when the previous element is conditionally rendered in react lifecycle, replace the contents of it. Now we store ariaDescribedBy in a variable so we don't search for that previousElementSibling
Changed how updateLabel() functions, instead of getting the previous element sibling on every call, it refers to an ariaDescribedBy variable created on load. 
However, i've been unable to add a test - because the issue occurs during react apps with conditional rendering. We only have web-component unit tests. I will enquire with the developer team :) 
#986
=> fix(web-components): ic-tooltip no longer interferes with previousSibling

package-lock.json, package.json, packages/react/package-lock.json, packages/react/package.json, packages/react/src/react-component-lib/utils/attachProps.ts, packages/web-components/package-lock.json, packages/web-components/package.json
Update stencil v3 to v4 and update stencil/react-output-target to minimum version allowed for stencil v4. Also includes updates to a react file that were made automatically after installing the new stencil version.
#1015
=> 1015 upgrade stenciljs from v3 to v4

packages/web-components/src/components/ic-dialog/ic-dialog.stories.mdx, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.css, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx, packages/web-components/src/components/ic-popover-menu/test/basic/__snapshots__/ic-popover-menu.spec.ts.snap, packages/web-components/src/components/ic-popover-menu/test/basic/ic-popover-menu.spec.ts, packages/web-components/src/components/ic-tooltip/ic-tooltip.css, packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx, packages/web-components/src/components/ic-tooltip/test/basic/__snapshots__/ic-tooltip.spec.ts.snap, packages/web-components/src/components/ic-tooltip/test/basic/ic-tooltip.e2e.ts, packages/web-components/src/components/ic-tooltip/test/basic/ic-tooltip.spec.ts
Update tooltip and popover menu to adjust placement on dialogs. Update tooltip to only create popper on show
#1006
=> fix(web-components): update tooltip and popover menu to adjust placement on dialogs

.husky/email-check.sh, .husky/pre-commit, CONTRIBUTING.md
Added a email checking script to husky precommit hook that enforces git email to be set to github user email address. Added guidance to contributing.md
Added a script to the precommit hook that gets the email stored in git config and compares it against regex for the github user email address. It rejects any non-github email addresses to support best practice.
Section added to CONTRIBUTING.md to instruct users on this change.
#532
=> chore(root): enforce github user email in precommit

packages/web-components/src/components/ic-button/ic-button.css, packages/web-components/src/components/ic-button/ic-button.tsx
Update loading button to have minimum width of original button
#1066
=> fix(web-components): update loading button to have minimum width of original button

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-date-input/ic-date-input.tsx, packages/web-components/src/components/ic-date-input/test/basic/ic-date-input.spec.tsx
Renames method to `setDisableDays`, to match prop name `disableDays`
N/A
=> fix(web-components): rename method to match prop name

packages/web-components/src/global/variables.css
Fixes issue where rgb alpha was not getting applied. this issue was introduced with Chromium v117, & seem to be when the individual r,g,b values exceeded 255
The fix sets upper limit for calculated values to be 255
N/A
=> fix(web-components): fix for css calc issue in new chromium version

packages/web-components/src/components/ic-radio-group/ic-radio-group.css, packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx, packages/web-components/src/components/ic-radio-group/test/basic/__snapshots__/ic-radio-group.spec.ts.snap, packages/web-components/src/components/ic-radio-group/test/basic/ic-radio-group.spec.ts
Update radio group to use resize observer to ensure horizontal orientation doesn't cut off radio options
#1055
=> fix(web-components): update radio group to use resize observer

packages/web-components/src/global/variables.css
Changes z-index for side-nav and nav items to prevent sticky page header from overlapping nav-items on focus and side nav on smaller viewports
#1142
=> fix(web-components): changes side-nav and nav-items z-index

packages/docs/docs.json
adds missing docs for ic-badge
n/a
=> docs(docs): adds badge docs

packages/web-components/src/components/ic-button/ic-button.css, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.css
fixes lint errors in navigation group and button css
N/A
=> fix(web-components): fixes lint errors

packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-menu/test/basic/ic-menu.spec.tsx, packages/web-components/src/components/ic-search-bar/ic-search-bar.stories.mdx
disabled options in search bar suggestions can no longer be selected
#1090
=> fix(web-components): prevents disabled search options being selected

audit-ci.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
Add aria owns and aria controls to host tag of button, and added props so that they can be added from other components.
#1012
=> 1012 ic button using aria controls or aria owns on ic button

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-button/readme.md, packages/web-components/src/components/ic-button/test/basic/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-button/test/basic/ic-button.spec.ts, packages/web-components/src/components/ic-link/ic-link.tsx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/utils/constants.ts
- Fixes issue where aria-label update was not passed to native button element.
- Now will reflect any changes made to any aria- attribute or title attribute.
- Moved all aria-* attributes from components into IC_INHERITED_ARIA.
- Removes internal method for updating the aria-label as no longer required. Can now call setAttribute() directly on IcButton element.
#1110
=> fix(web-components): fixes aria label not updating on button

packages/web-components/src/components/ic-button/ic-button.css
adds pressed button styling whilst ensuring the order of events is: 
Button exists on page unfocused or hovered showing default state.
Mouse over causes hover state.
Mouse down causes active state plus applies focus
Mouse up event causes complete click event (if still over button) and button remains hovered and focused.
Mouse leaves button area causing default state to return, with focus still displayed.
#844
=> adds button pressed styling

packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.mdx
Navigation group had expanded prop in storybook, however this is only applicable for side nav. This  fix removes it from the code. There is another ticket to remove from Design Kit
=> fix(web-components): removes expandable from storybook

packages/docs/docs.json, packages/react/src/stories/ic-checkbox.stories.mdx, packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.stories.mdx, packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.tsx, packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx
fixes issue where icchange event would not fire for a textfield, when slotted in a checkbox as an additional field
#1252
=> fix textfield slotted in checkbox change event not running

packages/docs/docs.json, packages/react/src/stories/ic-toast.stories.mdx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-toast-region/ic-toast-region.tsx, packages/web-components/src/components/ic-toast-region/readme.md, packages/web-components/src/components/ic-toast-region/test/basic/ic-toast-region.spec.ts, packages/web-components/src/components/ic-toast/ic-toast.stories.mdx, packages/web-components/src/components/ic-toast/ic-toast.tsx, packages/web-components/src/components/ic-toast/readme.md
Deprecate setVisible method on toast region.
Add openToast prop to toast region.
Add internal decorator to setVisible on toast.
Update to toast after some linting issues.
#1210
=> 1210 ic toast update toast to use prop to openclose

packages/web-components/src/components/ic-select/ic-select.tsx, packages/web-components/src/components/ic-select/test/basic/__snapshots__/ic-select.spec.tsx.snap, packages/web-components/src/components/ic-select/test/basic/ic-select.e2e.ts, packages/web-components/src/components/ic-select/test/basic/ic-select.spec.tsx, packages/web-components/src/utils/helpers.ts
When no options are provided initially, select will now populate the menu with the no results option. Made some adjustments to when the no-results class is applied to the menu to accommodate this case.
Also refactored some functions to be cleaner
#1207
=> feat(web-components): added default no results state to select

packages/web-components/src/components/ic-select/ic-select.css
display: block is featured on many components, and adding it to ic-select allows the width to be more easily overridden, similar to ic-text-field
#1143
=> fix(web-components): added display property to ic-select

packages/web-components/src/components/ic-text-field/ic-text-field.stories.mdx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx
Update text field to not call watchValueHandler on first load and move max length exceeded code into its own function so that it can be called in componentWillLoad and the watchValueHandler. Added a web component story logging out icChange
#1163
=> fix(web-components): update text field to not call watchValueHandler on first load

packages/docs/docs.json, packages/react/src/stories/ic-dialog.stories.mdx, packages/web-components/src/components/ic-dialog/ic-dialog.stories.mdx, packages/web-components/src/components/ic-dialog/ic-dialog.tsx
A new open prop has recently been added to the IcDialog component, which replaces the deprecated showDialog and hideDialog methods.
The trouble is, when an instance of an IcDialog component is initialised using the new open prop, with open="true", the dialog remains hidden. This is because the dialog is only made visible when the value of the open prop changes, i.e. when it is assigned a different value after the component has been initialised (which happens in the watchOpenHandler method).
In particular, this causes a problem for testing IcDialog based components using Cypress component tests, as it is currently not possible to instantiate a component using a prop of open="true" and then just go ahead and run assertions in Cypress, as a change of state is needed for the open prop to make …
=> fix(web-components): open ic-dialog during initialisation using the open prop

packages/web-components/src/components/ic-button/ic-button.css
I have added height to the 'popout-menu-button' class. This allows the button focus to resize accordingly when it is a multiple line button within a navigation menu.
Ticket number 1262
=> fix(web-components): add height to the popout-menu-button css class

packages/web-components/src/components/ic-navigation-menu/ic-navigation-menu.css, packages/web-components/src/components/ic-navigation-menu/ic-navigation-menu.tsx, packages/web-components/src/components/ic-navigation-menu/test/basic/__snapshots__/ic-navigation-menu.spec.ts.snap, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx
Add conditional check to navigation buttons in top navigation so that it doesn't appear as two dividers if there are no navigation buttons on small devices
#1299
=> fix(web-components): add conditional check to navigation buttons in top nav

packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
Add white space normal so that text wrap works on safari for navigation items in top nav side menu
Related to the work done in #1292
=> fix(web-components): add white space normal so that text wrap works on safari

packages/web-components/src/components/ic-tab-panel/ic-tab-panel.css
Fixes display of tabs when normalize.css is not imported into application
#1179
=> fix(web-components): fixes tabs display when normalize.css not imported

packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-button/test/basic/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-button/test/basic/ic-button.spec.ts, packages/web-components/src/components/ic-navigation-button/ic-navigation-button.tsx
Hides tooltips for top navigation icon buttons, when on popout menu
#1267
=> fix(web-components): hides tooltips for navigation buttons on menu

packages/docs/docs.json, packages/react/src/stories/ic-side-navigation.stories.mdx, packages/react/src/stories/ic-top-navigation.stories.mdx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.stories.mdx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.types.ts, packages/web-components/src/components/ic-side-navigation/readme.md, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.mdx, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/components/ic-top-navigation/readme.md
Update sideNavExpanded and topNavResized to use event decorator in order to appear in docs.
#1348
=> 1348 side nav expanded event should appear in docs

packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css
Removes unused css in ic-top-navigation
N/A
=> fix(web-components): removes unused css

packages/web-components/src/components/ic-page-header/ic-page-header.tsx, packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/components/ic-top-navigation/test/basic/__snapshots__/ic-top-navigation.spec.ts.snap
updated accessible labels for the nav sections of page header and top nav to be more descriptive of the page content and less confusing for SR users
[#610](https://github.com/mi6/ic-design-system/issues/610)
=> fix(web-components): updated accessible label for nav sections in page-header and top-nav

packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx, packages/web-components/src/components/ic-tooltip/test/basic/ic-tooltip.spec.ts
Before, if a label wasn't provided to a tooltip component (or icon variant button, which internally renders a tooltip):
(a malformed blob would appear - the tail and body of an empty tooltip)
Now, the tooltip won't 'show' if a label isn't provided, and a console warning will be logged. This is in addition to the existing error logged by onComponentRequiredPropUndefined()
How to replicate:
1. run branch locally
2. Edit the icon-only button story, deleting the 'aria-label' on one of the buttons
3. Hover over/tab onto the button.
4. Note that no tooltip appears
#1346
=> Fix Malformed Tooltips when label not provided

packages/web-components/src/components/ic-menu-item/ic-menu-item.css
Update css for menu item so that css parts works in safari for hover, active and focus states
719 in design system repo
=> popover menu not displaying items in safari

packages/canary-web-components/stencil.config.ts
Excludes new IcToggleButton from canary package
N/A
=> chore(canary-web-components): excludes toggle button from canary package

packages/react/src/stories/ic-popover-menu.stories.mdx, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx
This ticket fixes the react and web-component IcPopoverMenu storybook empty and closed states.
#1413
=> 1413 ic popover menu popover menu button not closing open popover menu

packages/web-components/src/components/ic-footer-link/ic-footer-link.css
This ticket fixes the footer link active state, it was previously quickly flashing a border when active- this behaviour was different to the IcLink. Now the IcFooterLink is aligned with the IcLink. This PR should then also fix the issues with the guidance sites footer links active state.
#1485
=> 1485 footer link active state

packages/docs/docs.json, packages/react/src/component-tests/IcSideNavigation/IcSideNavigation.cy.tsx, packages/react/src/component-tests/IcSideNavigation/IcSideNavigationTestData.tsx, packages/react/src/stories/ic-side-navigation.stories.mdx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.stories.mdx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-side-navigation/readme.md
Update expanded prop on side nav to allow state change programmatically.
#1474
=> 1474 ic side navigation collapse and expand state

packages/react/.storybook/preview.js, packages/react/.storybook/storybook.css, packages/web-components/.storybook/preview.js, packages/web-components/.storybook/storybook.css
Grabs the current appearance preference of the user with 2 .storybook.cc files, and changes the component environment in Storybook to reflect this. Will aid users wanting to test components in dark mode.
991
=> 991 add color scheme css property to storybook

packages/react/src/stories/ic-alert.stories.mdx, packages/web-components/src/components/ic-alert/ic-alert.css, packages/web-components/src/components/ic-alert/ic-alert.stories.mdx
Update alert to not set font size to 0 so that slotted message and title above can be used at the same time.
#1394
=> 1394 icalert cannot use message slot when titleabove is set to true

packages/web-components/src/components/ic-back-to-top/test/basic/__snapshots__/ic-back-to-top.spec.tsx.snap, packages/web-components/src/components/ic-footer-link-group/test/basic/__snapshots__/ic-footer-link-group.spec.ts.snap, packages/web-components/src/components/ic-footer/ic-footer.tsx, packages/web-components/src/components/ic-footer/test/basic/__snapshots__/ic-footer.spec.ts.snap
Conditionally render description block for footer so less space is taken up if no description is provided
#1491
=> fix(web-components): conditionally render description block for footer

packages/canary-web-components/src/components/ic-pagination-bar/test/a11y/ic-pagination-bar.test.a11y.ts, packages/web-components/src/components/ic-button/ic-button.stories.mdx, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-button/test/basic/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-dialog/test/basic/__snapshots__/ic-dialog.spec.ts.snap, packages/web-components/src/components/ic-navigation-menu/test/basic/__snapshots__/ic-navigation-menu.spec.ts.snap, packages/web-components/src/components/ic-pagination/test/a11y/ic-pagination.test.a11y.ts, packages/web-components/src/components/ic-search-bar/test/a11y/ic-search-bar.test.a11y.ts, packages/web-components/src/components/ic-search-bar/test/basic/__snapshots__/ic-search-bar.spec.ts.snap, packages/web-components/src/components/ic-select/test/basic/__snapshots__/ic-select.spec.tsx.snap
Update button to apply silent prop to tooltip if aria label is provided to reduce screen reader duplication
#1503
=> 1503 ic tooltip silent prop not applying on buttons with aria label

packages/web-components/src/components/ic-alert/ic-alert.stories.mdx, packages/web-components/src/components/ic-alert/ic-alert.tsx
Tiny change to remove `role` attribute on ic-alert when `announced` prop is "false". This was causing an Accessibility Insights error with the alerts used in the guidance on the ICDS website because it was causing `role` to be set to "false" which is an invalid value for that attribute.
N/A
=> fix(web-components): remove role on ic-alert when "announced" prop is false.

packages/web-components/src/components/ic-button/test/basic/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-button/test/basic/ic-button.spec.ts, packages/web-components/src/components/ic-tooltip/ic-tooltip.tsx, packages/web-components/src/components/ic-tooltip/test/basic/__snapshots__/ic-tooltip.spec.ts.snap
Fixes aria-hidden a11y issue on tooltips. Was previously setting aria-hidden="" when silent prop was set to false. this was causing a failure in the a11y testing.
N\A
=> fix(web-components): fixes aria-hidden a11y issue

packages/docs/docs.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-accordion-group/ic-accordion-group.tsx, packages/web-components/src/components/ic-accordion-group/readme.md, packages/web-components/src/components/ic-accordion-group/test/basic/__snapshots__/ic-accordion-group.spec.ts.snap
Add accessible title prop to accordion group to improve accessibility for screen reader users, and add aria label to see all/hide all button which utilises the new accessible title prop
#1488
=> 1488 accordion group improve see all labelling accessibility

packages/react/src/component-tests/IcDataEntity/IcDataEntity.cy.tsx, packages/web-components/src/components/ic-data-entity/ic-data-entity.tsx, packages/web-components/src/components/ic-data-row/ic-data-row.tsx, packages/web-components/src/components/ic-data-row/test/basic/__snapshots__/ic-data-row.spec.ts.snap
Removed cell role from ic-data-entity
#1465
=> fix(web-components): removed role of cell on the end-adornment in ic-data-entity

packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx, packages/web-components/src/components/ic-toggle-button/test/basic/__snapshots__/ic-toggle-button.spec.ts.snap
role='checkbox' removed from button and aria-pressed used to indicate state
#1502
=> fix(web-components): ic-toggle-button a11y fix

.github/workflows/ic-ui-kit-branches.yml, .github/workflows/update-cypress-visual-regression-tests.yml
- updated vr cypress action to check files against develop branch when running cypress tests
- added develop as base branch for feature github action
N/A
N/A
=> fix(root): updated github action for vr

packages/react/.storybook/preview.js, packages/react/.storybook/storybook.css, packages/web-components/.storybook/preview.js, packages/web-components/.storybook/storybook.css
Initially, dark color-scheme was implemented to allow us to spot where our components don't work with dark mode. However, since we don't support dark mode, this change gives the impression that our components now support this feature, which would subsequently cause confusion for users who view our components not working in our own storybook. I have documented which components are most affected in dark mode, and following conversation with design, it has become clear that a technical review needs to be done of our component library as to how we can smoothly implement a fully researched dark mode colour scheme, that maintains appropriate colour contrast and follows best practises, before we can begin making changes to our components. 
Until this research has been done, the dark color-scheme …
=> Remove storybook dark theme

packages/react/src/component-tests/IcSelect/IcSelect.cy.tsx, packages/web-components/src/components/ic-select/ic-select.tsx
Improve select onBlur to not blur if focusing on a menu option rather than just menu
#1349
=> 1349 ic selectic menu prevent icblur from being triggered

packages/web-components/src/components/ic-select/ic-select.tsx, packages/web-components/src/utils/helpers.ts
added check to icBlur to ensure that ic-menu element exists before using querySelector on it
#1458
=> fix(web-components): changed ic-select icBlur to confirm menu exists before using querySelector

.github/workflows/ic-ui-kit-branches.yml, .github/workflows/ic-ui-kit-develop.yml, .github/workflows/ic-ui-kit-main.yml
Updated the e2e steps for building component for canary tests. If the core e2e tests were skipped, canary e2e tests would fail. An additional step has been added so if core e2e tests (which includes a build) are skipped, a separate build command is run in place.
N/A
N/A
=> fix(root): updated e2e tests to fix the build step for canary components

packages/web-components/src/components/ic-button/ic-button.tsx
Add a watch to button disabled prop to remove it when disabled=false to ensure accessibility when toggling between disabled states
Can be tested using the disabled toggle in the playground examples for button
N/A
=> fix(web-components): add a watch to button disabled prop to remove it when disabled=false

audit-ci.json
Adds new allowlist item as Lerna v6 package update not available and bumps dates
N/A
=> chore(root): fixes audit issue

packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.css
Add auto height to `ic-navigation-item` when it's in the side menu to prevent it stretching when used in Stackblitz
https://github.com/mi6/ic-design-system/issues/760 https://github.com/mi6/ic-design-system/issues/764  https://github.com/mi6/ic-design-system/issues/751
=> Add auto height to `ic-navigation-item` when it's in the side menu

packages/canary-react/src/component-tests/IcDatePicker/IcDatePicker.cy.tsx, packages/canary-react/src/stories/ic-date-picker.stories.mdx, packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx, packages/canary-web-components/src/components/ic-date-picker/ic-date-picker.tsx, packages/canary-web-components/src/components/ic-date-picker/test/basic/ic-date-picker.spec.ts
fixes issue where props updated on ic-date-picker were not being passed to the ic-date-input inside
#1738
=> 1738 - ic-date-picker props not updating

packages/canary-react/src/component-tests/IcDatePicker/IcDatePicker.cy.tsx, packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx, packages/canary-web-components/src/components/ic-date-input/test/basic/__snapshots__/ic-date-input.spec.tsx.snap, packages/canary-web-components/src/components/ic-date-input/test/basic/ic-date-input.spec.tsx
fixes issue where change the `required` prop did not update the label to show\hide the asterisk. Also enables Cypress test in ic-date-picker which previously failed due to this issue
#1751
=> ic-date-input required prop change

packages/web-components/src/components/ic-select/test/basic/ic-select.spec.tsx, packages/web-components/src/utils/helpers.ts
Added an additional check to a helper function to avoid a bug with chrome browser returning a `maxTouchPoints` value.
#1765
=> fix(web-components): strengthen helper function

packages/canary-docs/docs.json, packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/story-data.ts, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx, packages/canary-web-components/src/components/ic-pagination-bar/test/basic/__snapshots__/ic-pagination-bar.spec.ts.snap, packages/canary-web-components/src/components/ic-pagination-bar/test/basic/ic-pagination-bar.spec.ts
Fixes Pagination bar not updating when props change
replaces #1725 
#1337
=> Fix Pagination bar not updating

packages/react/cypress.config.ts, packages/react/src/component-tests/IcLink/IcLink.cy.tsx, packages/react/src/component-tests/IcTopNavigation/IcTopNavigation.cy.tsx, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-dialog/test/basic/__snapshots__/ic-dialog.spec.ts.snap, packages/web-components/src/components/ic-link/ic-link.tsx, packages/web-components/src/components/ic-link/test/basic/ic-link.spec.ts, packages/web-components/src/components/ic-navigation-button/ic-navigation-button.tsx, packages/web-components/src/components/ic-navigation-button/test/basic/ic-navigation-button.spec.ts, packages/web-components/src/components/ic-navigation-menu/test/basic/__snapshots__/ic-navigation-menu.spec.ts.snap, packages/web-components/src/components/ic-select/ic-select.tsx, packages/web-components/src/components/ic-select/test/basic/__snapshots__/ic-select.spec.tsx.snap, packages/web-components/src/components/ic-select/test/basic/ic-select.spec.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx, packages/web-components/src/components/ic-text-field/test/basic/ic-text-field.e2e.ts, packages/web-components/src/components/ic-text-field/test/basic/ic-text-field.input.spec.tsx
Added mutation observers to components that inherit attributes from its host element, to ensure that the are updated when a host element updates its attributes.
Added tests to various files for the mutation observer, in cypress for e2e testing and in spec tests to boost code coverage. Also updated some snapshots for some components
#1121
=> 1121 test mutating attributes

packages/canary-web-components/src/components/ic-date-input/ic-date-input.css
Add container class to focus-indcator css in ic-date-input to stop it being overriden in gatsby
This relates to a [comment on PR899 on design system](https://github.com/mi6/ic-design-system/pull/899#issuecomment-2066505495)
=> fix(canary-web-components): make focus indicator in data-input more specific

.github/workflows/ic-ui-kit-branches.yml
Added action permissions for failed cypress test uploads on feature builds.
N/A
N/A
=> ci(root): adding action permissions for cypress uploading

.github/pull_request_template.md, packages/react/src/component-tests/IcCheckbox/IcCheckbox.cy.tsx, packages/react/src/component-tests/IcCheckbox/IcCheckboxTestData.tsx, packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx, packages/react/src/component-tests/IcRadio/IcRadioTestData.tsx, packages/react/src/component-tests/IcSearchBar/IcSearchBar.cy.tsx, packages/react/src/component-tests/IcSearchBar/IcSearchBarTestData.tsx, packages/react/src/component-tests/IcSelect/IcSelect.cy.tsx, packages/react/src/component-tests/IcSelect/IcSelectSearchable.cy.tsx, packages/react/src/component-tests/IcSelect/IcSelectTestData.tsx, packages/react/src/component-tests/IcSwitch/IcSwitch.cy.tsx, packages/react/src/component-tests/IcSwitch/IcSwitchTestData.tsx, packages/react/src/component-tests/IcTextField/IcTextField.cy.tsx, packages/react/src/component-tests/IcTextField/IcTextFieldTestData.tsx, packages/react/src/stories/ic-checkbox.stories.mdx, packages/react/src/stories/ic-radio-group.stories.mdx, packages/react/src/stories/ic-search-bar.stories.mdx, packages/react/src/stories/ic-select_(searchable).stories.mdx, packages/react/src/stories/ic-select_(single).stories.mdx, packages/react/src/stories/ic-switch.stories.mdx, packages/react/src/stories/ic-text-field.stories.mdx
Add storybook examples and cypress tests for controlled/uncontrolled comps using useState and useRef
#1118
=> 1118 test controlled and uncontrolled

packages/react/src/component-tests/IcChip/IcChip.cy.tsx
[Disabled interface items are not required to meet constrast values](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum#:~:text=User%20Interface%20Components%20that%20are%20not%20available%20for%20user%20interaction%20(e.g.%2C%20a%20disabled%20control%20in%20HTML)%20are%20not%20required%20to%20meet%20contrast%20requirements.) so we can disable that rule in the cypress accessibility check for disabled chips. 
#1505
=> test(react): add a11y test to disabled chips

packages/web-components/src/components/ic-tooltip/ic-tooltip.css
Set width and height on ic-tooltip to `max-content` so that it always matches the size of the child element.
You can see this working if you go to the [StackBlitz](https://stackblitz.com/edit/3uyj9c?file=src%2Fapp.tsx) provided on the ticket; go to the `<ic-tooltip>` element in the DevTools and add `width: max-content` in the styles.
#1815
=> fix(web-components): add max-content to ic-tooltip to make size match child element

packages/react/src/stories/ic-breadcrumb-group.stories.mdx, packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx
- Fix React Router storybook for breadcrumbs, so it actually displays breadcrumbs
- When breadcrumbs are Collapsed, and the '...' button is clicked to expand them, focus is moved to the first expanded breadcrumb (previously focus was lost, particularly noticeable when using a screenreader)
#1817
=> Breadcrumb fixes as part of Component Review

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-button/ic-button.stories.mdx, packages/web-components/src/components/ic-button/ic-button.tsx, packages/web-components/src/components/ic-button/test/basic/__snapshots__/ic-button.spec.ts.snap, packages/web-components/src/components/ic-status-tag/ic-status-tag.tsx, packages/web-components/src/components/ic-status-tag/readme.md
To test this:  go to the [Card with interaction Button story (develop)](https://mi6.github.io/ic-ui-kit/branches/develop/web-components/?path=/story/web-components-card--with-interaction-button) and use voiceover to read the icon button. 
That story on this branch will read the tooltip.
#1845
=> 1845 ic button accessibility error when setting title attribute on icon variant

packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx, packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-menu/test/basic/__snapshots__/ic-menu.spec.tsx.snap, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx, packages/web-components/src/components/ic-select/ic-select.tsx, packages/web-components/src/components/ic-select/test/basic/__snapshots__/ic-select.spec.tsx.snap
Removed p tag from typography in single select and menu options, to prevent text becoming misaligned when text spacing is increased
#1817
=> fix(web-components): removed p tag from select and menu options

packages/react/src/component-tests/IcToggleButtonGroup/IcToggleButtonGroupTestData.tsx, packages/react/src/stories/ic-toggle-button-group.stories.mdx, packages/web-components/src/components/ic-toggle-button-group/ic-toggle-button-group.stories.mdx, packages/web-components/src/components/ic-toggle-button/ic-toggle-button.tsx
Update toggle button icon placement to be overridden by group icon placement if its set
#1811
=> Update toggle button icon placement to be overridden by group icon placement

packages/web-components/src/components/ic-button/ic-button.css
Updated ic-button colour tokens to use more appropriate ones for future reference and alterations. Done inline with ticket. Also removed some redundant/incorrect class selectors from the css to make it less bulky.
Also added a few missing prop/slot descriptions to the docs package so they will be updated on the guidance site.
#1659
=> 1659 new button interaction state

packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx
Removed state update when escape is pressed on the menu, to prevent the menu from receiving focus after it has technically been closed.
#703
=> fix(web-components): removed state update that triggers focusing of the menu after closing

packages/react/src/stories/ic-section-container.stories.mdx, packages/react/src/stories/ic-select_(searchable).stories.mdx, packages/react/src/stories/ic-select_(single).stories.mdx, packages/react/src/stories/ic-side-navigation.stories.mdx, packages/web-components/src/components/ic-section-container/ic-section-container.tsx
Add Storybook playgrounds for Select, SideNav and Section Container
Small fix to Section Container for when you change 'aligned' prop to null after first render (as what happens in the storybook)
#1970
=> 1970 playground select, side nav and section container

.github/workflows/ic-ui-kit-branches.yml
changed the output of a failed cypress visual regression test in the CI to output the diff directory directly and the html format of the report
=> ci(root): github workflow change

packages/react/src/stories/ic-chip.stories.mdx, packages/react/src/stories/ic-classification-banner.stories.mdx, packages/react/src/stories/ic-data-entity.stories.mdx, packages/react/src/stories/ic-dialog.stories.mdx, packages/react/src/stories/ic-empty-state.stories.mdx, packages/react/src/stories/ic-toast.stories.mdx, packages/web-components/src/components/ic-chip/ic-chip.stories.mdx, packages/web-components/src/components/ic-classification-banner/ic-classification-bannner.stories.mdx, packages/web-components/src/components/ic-data-entity/ic-data-entity.stories.mdx, packages/web-components/src/components/ic-dialog/ic-dialog.stories.mdx, packages/web-components/src/components/ic-empty-state/ic-empty-state.stories.mdx, packages/web-components/src/components/ic-toast/ic-toast.stories.mdx, packages/web-components/src/components/ic-toast/ic-toast.tsx
Add playground stories for chip, classification banner, data entity, dialog, empty state and toast.
Update dismissMode on toast so that it can change between manual and automatic
Part of #1970
=> 1970 more component playgrounds

.github/workflows/deploy-storybook-only.yml, .github/workflows/ic-ui-kit-branches.yml, .github/workflows/ic-ui-kit-develop.yml, .github/workflows/ic-ui-kit-main.yml, .github/workflows/run-cypress-tests.yml, .github/workflows/update-cypress-visual-regression-tests.yml, .github/workflows/update-visual-regression-tests.yml
Removes `--legacy-peer-deps` flag from ci actions as not required
#1759
=> ci(root): removes --legacy-peer-deps flag from actions

packages/react/src/stories/ic-popover-menu.stories.mdx, packages/react/src/stories/ic-radio-group.stories.mdx, packages/react/src/stories/ic-status-tag.stories.mdx, packages/react/src/stories/ic-tabs.stories.mdx, packages/react/src/stories/ic-toggle-button-group.stories.mdx, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx, packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.mdx, packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx, packages/web-components/src/components/ic-status-tag/ic-status-tag.stories.mdx, packages/web-components/src/components/ic-tab-context/ic-tab-context.tsx, packages/web-components/src/components/ic-tab-context/ic-tabs.stories.mdx, packages/web-components/src/components/ic-toggle-button-group/ic-toggle-button-group.stories.mdx
Add playground stories for popover menu, radio, status tag, tab, and toggle button. 
Add watch to tab context appearance prop so that it passes down the correct value to tab/tab group/tab panel when appearance is toggled.
Tickets created for missing/incorrect functionality - #2017, #2018, #2022 
Part of #1970
=> 1970 additional component playgrounds

packages/canary-react/cypress.config.ts, packages/react/cypress.config.ts
When running Cypress tests locally with `open` there will now be 0 retries, this will help save time when testing and increase accuracy of tests ensuring they pass first time. Tests on the CI remain at 3.
=> Cypress config retries

packages/react/src/stories/ic-badge.stories.mdx, packages/react/src/stories/ic-breadcrumb-group.stories.mdx, packages/react/src/stories/ic-card.stories.mdx, packages/web-components/src/components/ic-badge/ic-badge.stories.mdx, packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.stories.mdx, packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx, packages/web-components/src/components/ic-breadcrumb-group/test/basic/__snapshots__/ic-breadcrumb-group.spec.ts.snap, packages/web-components/src/components/ic-card/ic-card.stories.mdx, packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap
Storybook playgrounds for badge, breadcrumb and card. Fix for breadcrumbs so that appearance and backBreadcrumbOnly props can be changed after being set.
Ticket created for collapsed prop not working after being set on breadcrumbs - https://github.com/mi6/ic-ui-kit/issues/1998
Part of #1970
=> 1970 badge, breadcrumb and card playgrounds

packages/canary-react/src/stories/ic-date-input.stories.mdx, packages/canary-react/src/stories/ic-date-picker.stories.mdx
Add playground stories for date input and date picker
Ticket already created for startOfWeek not updating - https://github.com/mi6/ic-ui-kit/issues/1877
Part of #1970
=> 1970 canary date component playgrounds

packages/react/src/stories/ic-text-field.stories.mdx, packages/web-components/src/components/ic-input-component-container/ic-input-component-container.tsx, packages/web-components/src/components/ic-input-component-container/test/basic/ic-input-component-container.spec.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx, packages/web-components/src/components/ic-text-field/test/basic/ic-text-field.input.spec.tsx, packages/web-components/src/utils/helpers.ts
- Updated state when maxCharacters is set to zero after the validation has been shown, to allow users to enter text in this instance. Previously the text-field would not allow new characters due to the max being zero.
- Added child components to mutation observer for ic-text-field and ic-input-component-container, which will force an update if a slotted icon is added as a child, meaning that the icon can now be conditionally rendered
#1970
=> 1970 text field playground

packages/canary-react/src/component-tests/IcDatePicker/IcDatePicker.cy.tsx
Increases threshold for failing datepicker test
N/A
=> fix(canary-react): fixes test threshold issue

packages/canary-react/src/stories/ic-data-table.stories.mdx
Add playground story for data table incorporating pagination bar args so pagination bar playground could be removed
Part of #1970
=> docs(canary-react): add playground story for data table

packages/react/src/component-tests/IcTypography/IcTypography.cy.tsx, packages/web-components/src/components/ic-typography/ic-typography.tsx, packages/web-components/src/components/ic-typography/test/basic/__snapshots__/ic-typography.spec.ts.snap
Removes aria hidden attribute and enables skipped a11y tests in ic -typography.
Fixes #1854
=> fix(web-components): remove aria-hidden in see more/less buttons

packages/docs/docs.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-hero/ic-hero.tsx, packages/web-components/src/components/ic-hero/readme.md, packages/web-components/src/components/ic-hero/test/basic/__snapshots__/ic-hero.spec.ts.snap, packages/web-components/src/components/ic-hero/test/basic/ic-hero.spec.ts
Set heading prop to h2 and secondaryHeading to h3 semantic elements in Hero component
BREAKING CHANGE: Heading hierarchy of the component has changed, which might affect accessibility compliance when integrated
re #1687
=> fix(web-components): set heading levels on Hero component

packages/web-components/src/components/ic-breadcrumb/ic-breadcrumb.css, packages/web-components/src/components/ic-card/ic-card.css, packages/web-components/src/components/ic-footer-link/ic-footer-link.css, packages/web-components/src/components/ic-link/ic-link.css, packages/web-components/src/components/ic-typography/ic-typography.css
Update footer link, breadcrumb, card, link and typography support css so that focus underline appears on focus and hover
#1869, #1910, #1855, #1861
=> safari links dont get focus

.github/pull_request_template.md, CHECKLIST.md, packages/react/.storybook/main.js, packages/react/.storybook/preview.js, packages/react/package-lock.json, packages/react/package.json
Add the storybook-addon-performance package to react. Now the performance tab is visible in react storybook
ref #2087
First commit added the performance addon to React storybook.
Potentially follow up commits will add an 'Interaction' (as per [the addon's documentation](https://storybook.js.org/addons/storybook-addon-performance) ) to one of the Stories
As of yet i'm unsure how we can make use of this package. The docs mention using a 'Save API' to save results, but there's no example given. I think this is purely going to be a manual test, and in the browser is the only place i've found the ability to Save results. 
#2087
=> test(react): install storybook performance addon to react

packages/react/src/stories/ic-card.stories.mdx, packages/web-components/src/components/ic-card/ic-card.css, packages/web-components/src/components/ic-card/ic-card.stories.mdx
- Added CSS to card component to stop its contents overflowing when it has a set height or width and the text size is increased. 
- Change 'Reduced width' card stories to include an increased width card as well to help with checking that changing the text size works for different widths.
- ^ Changed text to fewer words to help with checking the cards aren't wrapping to the width of the text.
- Added sizes to the images as not having a size was causing the images to not display in Safari.
To test this, go to the 'Reduced width' and 'Additional height' card stories and increase the text size in the browser (e.g. in Chrome, Settings > Appearance > Font size).
#1860
=> fix(web-components): make card contents stop overflowing when text size increased

packages/web-components/src/components/ic-footer-link-group/ic-footer-link-group.tsx, packages/web-components/src/components/ic-footer-link-group/test/basic/__snapshots__/ic-footer-link-group.spec.ts.snap, packages/web-components/src/components/ic-footer-link-group/test/basic/ic-footer-link-group.spec.ts, packages/web-components/src/components/ic-footer-link/ic-footer-link.tsx, packages/web-components/src/components/ic-footer-link/test/basic/__snapshots__/ic-footer-link.spec.ts.snap, packages/web-components/src/components/ic-footer-link/test/basic/ic-footer-link.spec.ts, packages/web-components/src/components/ic-footer/ic-footer.tsx, packages/web-components/src/components/ic-footer/test/basic/__snapshots__/ic-footer.spec.ts.snap
Add semantic roles to ic-footer-link and ic-footer-link-group for accessibility. Update tests following this change
#1686
=> fix(web-components): add list role to ic-footer-link and listitem role to ic-footer-link-group

packages/web-components/src/components/ic-accordion-group/ic-accordion-group.css, packages/web-components/src/components/ic-accordion/ic-accordion.css
Now using primary text color as per designs
#2210
=> fix(web-components): fixes accordion using wrong text color

packages/react/src/component-tests/IcClassificationBanner/IcClassificationBanner.cy.tsx, packages/web-components/src/components/ic-classification-banner/ic-classification-banner.tsx, packages/web-components/src/components/ic-classification-banner/test/basic/ic-classification-banner.spec.ts
Wasn't able to reproduce the bug, but I believe an extra check in the render should do the trick. If you can show me code to make the reproduction viable, I can adjust the PR to that (https://github.com/evenstensberg/banner-repro-ic/blob/master/src/HelloWorldComponent.js)
#2177
=> fix(web-components): extra check to default & remove dupe conditional

packages/canary-react/.webpack/webpack.config.js, packages/canary-react/cypress/plugins/index.js, packages/fonts/.webpack/webpack.config.js, packages/fonts/package.json, packages/nextjs/.webpack/webpack.config.js, packages/react/.webpack/webpack.config.js, packages/react/cypress.config.ts, packages/react/cypress/plugins/index.js
Moves webpack to dedicated folder.
N/A
=> chore: move webpack to its own folder

packages/web-components/src/components/ic-footer-link/ic-footer-link.css
Restored some CSS in footer-link to style slotted SVG icons correctly in theme switcher
See the slottedSVG displaying incorrectly in black on v3.0.0/develop branch:
=> fix(web-components): restore slotted-svg styles in footer link

packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx
Changed usage of variable to string in tree-item so `ic-tooltip` appears as a dependency within the canary `docs.json`
N/A
N/A
=> [ic-tree-item]: changed usage of variable to string

packages/canary-docs/docs.json, packages/canary-web-components/stencil.config.ts, packages/docs/docs.json, packages/web-components/stencil.config.ts
Adds a custom handler that deletes timestamp from the built json docs
- https://github.com/mi6/ic-ui-kit/issues/2391
=> fix: dont add timestamps in docs generation

package.json
Removed nextjs build from root level to reduce build time. Any actions to be carried out for the nextJS storybook instance can be actioned inside the nextjs package.
N/A
N/A
=> [nextJs]: Removed from root build command

packages/web-components/src/components/ic-badge/ic-badge.css, packages/web-components/src/components/ic-badge/ic-badge.tsx, packages/web-components/src/components/ic-badge/test/basic/__snapshots__/ic-badge.spec.tsx.snap
I've added a screenreader-only label to type="dot" badges. This makes them read a little better to NVDA screenreader.
Please read the ticket (linked below) to see mine and @GCHQ-Developer-847 's experience with this issue. I don't think there's much more that can be done for NVDA - all the badges can be read by NVDA users, but it is an inferior experience to Voiceover. This change makes Dot badges readable as "badge".
#1717
=> fix(web-components): make dot type badges read to screenreaders

packages/react/src/component-tests/IcToast/IcToast.cy.tsx, packages/react/src/component-tests/IcToast/IcToastTestData.tsx, packages/react/src/stories/ic-toast.stories.mdx, packages/web-components/src/components/ic-toast-region/ic-toast-region.tsx
- Added componentDidLoad to ic-toast-region to check whether openToast is set when the component is rendered, to immediately show it.
- Added cypress test.
=> Auto loading toasts

packages/canary-docs/docs.json, packages/canary-react/src/stories/ic-pagination-bar.stories.mdx, packages/canary-web-components/src/components.d.ts, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.types.ts, packages/canary-web-components/src/components/ic-pagination-bar/readme.md, packages/canary-web-components/src/components/ic-pagination-bar/test/basic/__snapshots__/ic-pagination-bar.spec.ts.snap, packages/canary-web-components/src/components/ic-pagination-bar/test/basic/ic-pagination-bar.spec.ts
Adds `currentPage` prop to pagination bar to control the page number currently displayed
Adds additional `fromItemsPerPage` in `icPageChange` event to allow user to determine what action triggered the page change
Adds React storybook playground
#2407, #2408
=> 2408 pagination page number

packages/react/src/component-tests/IcSearchBar/IcSearchBar.cy.tsx, packages/web-components/src/components/ic-search-bar/ic-search-bar.tsx, packages/web-components/src/components/ic-select/ic-select.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx
- Changed condition for when to apply combobox role to the input of ic-search-bar. Now matches aria-expanded condition to ensure they are applied at the same time.
- Added back missing a11y checks to cypress tests
#1912
Still some a11y violations on certain tests, that will be covered in [this ticket](https://github.com/mi6/ic-ui-kit/issues/2015)
=> 1912 aria expanded

packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx, packages/react/src/component-tests/IcSearchBar/IcSearchBar.cy.tsx, packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
- Removed shadow from radio tests
- Updated to v3 class names 
- Restore orientation overrides
N/A
=> test(react): update Cypress e2e tests after v2 -> v3 rebase

packages/web-components/src/components/ic-alert/ic-alert.css, packages/web-components/src/components/ic-page-header/ic-page-header.css, packages/web-components/src/components/ic-page-header/ic-page-header.tsx, packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap
Removed margin-bottom from heading and added margin-top to subheading so the heading appears centred vertically when no subheading has been set
N/A
N/A
N/A
N/A
=> [ic-page-header]: removed margin-bottom from heading

packages/web-components/src/components/ic-alert/ic-alert.css, packages/web-components/src/components/ic-page-header/ic-page-header.css, packages/web-components/src/components/ic-page-header/ic-page-header.tsx, packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap
Removed margin-bottom from heading and added margin-top to subheading so the heading appears centred vertically when no subheading has been set
N/A
N/A
N/A
N/A
=> [ic-page-header]: removed margin-bottom from heading (v3)

packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumb.cy.tsx, packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumbTestData.tsx, packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx, packages/web-components/src/components/ic-breadcrumb-group/test/basic/__snapshots__/ic-breadcrumb-group.spec.ts.snap
Fixed the issue with the breadcrumb group collapsed prop not toggling properly and fixed the back arrow not turning back into a chevron
fix #1998 
fix #2028
Fixed the issue where the breadcrumb group prop would, when toggled, not remove the collapsed ellipses element so they would just stack up
Also fixed the issue where, when toggled back and forth, the back arrow for the 'back breadcrumb only' prop would not switch back to a chevron icon
#1998 
#2028
=> fix(web-components): breadcrumb group collapsed prop issue

packages/react/src/component-tests/IcTooltip/IcTooltip.cy.tsx, packages/react/src/component-tests/IcTooltip/IcTooltipTestData.tsx
Created a long label tooltip test in react
#2540
=> test(react): added long label tooltip test

packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx, packages/react/src/component-tests/IcRadio/IcRadioTestData.tsx, packages/react/src/stories/ic-radio-group.stories.mdx, packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.mdx, packages/web-components/src/components/ic-radio-group/test/basic/ic-radio-group.spec.ts, packages/web-components/src/components/ic-radio-option/ic-radio-option.css, packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
fix click event not being emitted properly on components that are in the additional field slot
fix #2514
=> Ic-radio-option: fix click event not working on components in additional field slot

packages/canary-web-components/src/components/ic-date-input/ic-date-input.css, packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
Add check to event.key to ensure it exists in date input so that browser input suggestions can be accepted
#1967
=> 1967 date input unable to deal with browser input suggestions

packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.tsx, packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-tab-context/ic-tab-context.tsx, packages/web-components/src/components/ic-toggle-button-group/ic-toggle-button-group.tsx, packages/web-components/src/components/ic-toggle-button-group/test/ic-toggle-button-group.spec.ts
Added optional chaining on removeEventListener methods within disconnectedCallback to prevent vitest console errors. For example, the Vitest console would output `Cannot read properties of undefined (reading 'removeEventListener')` for `this.tabGroup`. By adding the optional chaining, removeEventListener is not called if there is no `tabGroup`
N/A
=> [disconnectedCallback update]: optional chaining to removeEventListener functions

packages/web-components/src/components/ic-horizontal-scroll/ic-horizontal-scroll.tsx, packages/web-components/src/components/ic-menu/ic-menu.tsx, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-tab-context/ic-tab-context.tsx, packages/web-components/src/components/ic-toggle-button-group/ic-toggle-button-group.tsx, packages/web-components/src/components/ic-toggle-button-group/test/ic-toggle-button-group.spec.ts
Added optional chaining on removeEventListener methods within disconnectedCallback to prevent vitest console errors. For example, the Vitest console would output `Cannot read properties of undefined (reading 'removeEventListener')` for `this.tabGroup`. By adding the optional chaining, removeEventListener is not called if there is no `tabGroup`
N/A
=> [v3 cherry-pick / disconnectedCallback update]: optional chaining to removeEventListener functions

packages/docs/docs.json, packages/react/src/component-tests/IcPopoverMenu/IcPopoverMenu.cy.tsx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx, packages/web-components/src/components/ic-menu-item/readme.md, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx
Change toggleChecked state to a prop and add new icToggleChecked event to ic-menu-item. The need for this became apparent after the work done in https://github.com/mi6/ic-design-system/issues/1184
=> Add IcToggleChecked event to IcMenuItem and change toggleChecked state to prop

packages/react/src/stories/ic-page-header.stories.mdx, packages/web-components/src/components/ic-navigation-item/ic-navigation-item.tsx, packages/web-components/src/components/ic-navigation-item/test/basic/__snapshots__/ic-navigation-item.spec.ts.snap, packages/web-components/src/components/ic-navigation-item/test/basic/ic-navigation-item.spec.ts, packages/web-components/src/components/ic-page-header/ic-page-header.stories.mdx
Fixes nav-item screen reader issue where aria-label was not being read out in NVDA
Now also supports the aria-label being changed after initial render
#2579
=> Navigation item aria label not read out in NVDA

packages/web-components/src/components/ic-menu-group/ic-menu-group.tsx, packages/web-components/src/components/ic-menu-group/test/basic/__snapshots__/ic-menu-group.spec.ts.snap, packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx, packages/web-components/src/components/ic-menu-item/test/basic/__snapshots__/ic-menu-item.spec.ts.snap, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx, packages/web-components/src/components/ic-popover-menu/test/basic/__snapshots__/ic-popover-menu.spec.ts.snap
Modified some semantics/aria inside popover menu to clear errors in Accessibility Insights. 
I've personally tested the popover in VoiceOver and NVDA (using the TextViewer in a virtual machine) and it reads the elements and their relationships okay in both.
#1897
=> 1897 ic popover menu accessibility failures

packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/utils/helpers.ts
There were a number of issues with how columns were laid out before with slotting this corrects them
~To take out of draft I want to take a look at:~
I have tried to create a unit test for the helper but jest is only configured for a11y on this project and looks to be a pain to setup, I can try if deemed needed
fixes #2743
=> fix(canary-web-components): skip adding slotted column placeholders when the slotted column already has data

packages/canary-react/package-lock.json, packages/canary-web-components/package-lock.json, packages/canary-web-components/src/components/ic-card-horizontal/ic-card-horizontal.css, packages/fonts/package-lock.json, packages/nextjs/package-lock.json, packages/react/package-lock.json, packages/web-components/package-lock.json
Change horizontal card styles so image size is set directly on image to fix issue in Safari where the images were being displayed smaller than they should (you can see this bug on the [horizontal card Sizes story](https://mi6.github.io/ic-ui-kit/branches/canary/develop/web-components/?path=/story/web-components-horizontal-card--sizes) in Safari).
The behaviour of the images now matches the behaviour in Chrome.
Also added fixes for audit failures.
N/A
=> Fix horizontal card Safari image size bug

.gitignore
=> chore(root): add mac generated cache to gitignore

packages/react/src/component-tests/IcTextField/IcTextField.cy.tsx, packages/react/src/component-tests/IcTextField/IcTextFieldTestData.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.stories.mdx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx
When validation status is set to an empty string,  ic-input-validation no longer renders
#2140
=> 2140 text field renders ic input validation element in the html when validationstatus is set to an empty string

packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.css, packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts, packages/canary-web-components/src/components/ic-data-table/test/basic/__snapshots__/ic-data-table.spec.tsx.snap, packages/canary-web-components/src/components/ic-data-table/test/basic/ic-data-table.spec.tsx
Added action-element to ICDataTable cells that can be passed in through the data.
The action-element can be any HTMLElement, so a lot of the checklist would seem to not be applicable. Happy to help with any issues that arise and listen to any comments.
Storybook:
#2847
2934
=> 2934 add elements to end of cells in icdatatable

packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.css, packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts, packages/canary-web-components/src/components/ic-data-table/test/basic/__snapshots__/ic-data-table.spec.tsx.snap, packages/canary-web-components/src/components/ic-data-table/test/basic/ic-data-table.spec.tsx
cherry-pick of https://github.com/mi6/ic-ui-kit/pull/2912 into v3
#2847
=> Datatable cell elements v3 cherry pick

packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx, packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx
Fix for when arrow keys are pressed when additional field has focus
- Radio-group will ignore keydown when additional field has focus
- Cypress test added
#2685
=> 2685 ic radio   using arrows keys in additional field input changes selected radio

packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts
Allow specifying target and rel attributes for the anchor tag in the cell, along with the href. There are existing styles that add a new window icon to the link when the target is "_blank" and so no change is required to achieve that.
Closes: #2751
=> feat(canary-web-components): allow specifying target for anchor in ic-data-table cell

packages/react/src/component-tests/IcSelect/IcSelect.cy.tsx, packages/react/src/stories/ic-select_(single).stories.mdx, packages/web-components/src/components/ic-select/ic-select.tsx
when no options available the 'no options found' item cannot be selected
Can't have `cursor event` and `pointer` CSS changes on the same element, so I created a `<span>` to wrap the li option on a different layer, only when options not available, not when 'retry' is available.
#2390
=> fix(web-components): select bugfix

packages/web-components/package-lock.json, packages/web-components/package.json
Fixed build problem in web-components by adding dependency on React types.
The npm run build task was failing with the following error: Cannot find namespace 'JSX'
This has been fixed by adding dev dependencies on the following packages:
- @types/react
- @types/react-dom
The versions of these dependencies being used ("^17.0.37") match those being used in the canary-react package.
N/A
=> Add React types to fix build issue

packages/canary-web-components/src/components/ic-card-horizontal/ic-card-horizontal.tsx, packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.tsx, packages/canary-web-components/src/utils/helpers.ts, packages/web-components/src/components/ic-alert/ic-alert.tsx, packages/web-components/src/components/ic-alert/test/basic/__snapshots__/ic-alert.spec.ts.snap, packages/web-components/src/components/ic-alert/test/basic/ic-alert.spec.ts, packages/web-components/src/components/ic-card/ic-card.tsx, packages/web-components/src/components/ic-card/test/basic/__snapshots__/ic-card.spec.ts.snap, packages/web-components/src/components/ic-card/test/basic/ic-card.spec.ts, packages/web-components/src/components/ic-empty-state/ic-empty-state.tsx, packages/web-components/src/components/ic-footer/ic-footer.tsx, packages/web-components/src/components/ic-footer/test/basic/__snapshots__/ic-footer.spec.ts.snap, packages/web-components/src/components/ic-footer/test/basic/ic-footer.spec.ts, packages/web-components/src/components/ic-hero/ic-hero.tsx, packages/web-components/src/components/ic-hero/test/basic/__snapshots__/ic-hero.spec.ts.snap, packages/web-components/src/components/ic-hero/test/basic/ic-hero.spec.ts, packages/web-components/src/components/ic-input-component-container/ic-input-component-container.tsx, packages/web-components/src/components/ic-input-component-container/test/basic/__snapshots__/ic-input-component-container.spec.tsx.snap, packages/web-components/src/components/ic-input-component-container/test/basic/ic-input-component-container.spec.tsx, packages/web-components/src/testspec.setup.ts, packages/web-components/src/utils/helpers.ts
- Updated `ic-footer` to forceUpdate if `link` slot rendered after initial load.
- Refactored mutationObserver function to use in other components where relevant
- Created unit tests
N/A
=> [ic-footer]: Slot updates after initial render

packages/react/src/component-tests/IcTextField/IcTextField.cy.tsx, packages/react/src/component-tests/IcTextField/IcTextFieldTestData.tsx, packages/react/src/stories/ic-text-field.stories.mdx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx
Adds in removeHiddenInput for text field so hidden input prop can be toggled
#1785
=> 1785 changing text field hidden input has no effect

packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts, packages/canary-web-components/src/components/ic-data-table/test/basic/__snapshots__/ic-data-table.spec.tsx.snap, packages/canary-web-components/src/components/ic-data-table/test/basic/ic-data-table.spec.tsx
replicates https://github.com/mi6/ic-ui-kit/pull/2988 in v3 branch
part of #2847
=> V3 cherry pick action element onclick

packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts
Added check to stop duplicate tooltips being created in cells when it is already truncated, preventing content being forced right
#2819
=> fix(canary-web-components): added check to prevent duplicate tooltip being added

packages/react/src/component-tests/IcRadio/IcRadio.cy.tsx, packages/react/src/component-tests/IcRadio/IcRadioTestData.tsx, packages/react/src/stories/ic-radio-group.stories.mdx, packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.mdx, packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx, packages/web-components/src/components/ic-radio-group/test/basic/ic-radio-group.spec.ts, packages/web-components/src/components/ic-radio-option/ic-radio-option.css, packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
- Adjusted some event listeners to not propagate the event higher up the tree. This is for when (as in the example stackblitz in the ticket) a radio-group is slotted as a child element in the additional field. This enables keyboard interaction without overriding the radio-group higher up the tree.
- Added a test for the keyboard interaction.
- Updated storybook to show different elements being used in the slot.
#2826
=> 2826 Added ability to slot other elements into radio-option `additional-field` slot

packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx
Using a code snippet provided by the internal customer, i've recreated tooltip overflow issues that they were finding in the data table (screenshots available on internal ticket) and then, using code suggested by a colleague i've made fixCellTootips search recursively through slotted elements to modify tooltips. 
Seemingly this has fixed the issue - as demonstrated by changes to the *Links and slotted elements in data* story
#2894
=> 2894 internal issue 2841 icdatatable truncates tooltips passed in via slots

packages/canary-react/src/stories/ic-tree-view.stories.mdx, packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx, packages/canary-web-components/src/components/ic-tree-item/test/basic/__snapshots__/ic-tree-item.spec.ts.snap, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.css, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.stories.mdx, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.tsx, packages/canary-web-components/src/components/ic-tree-view/test/basic/__snapshots__/ic-tree-view.spec.ts.snap
Updated tree view to improve FOUC. Click between the different tree view stories to see that the flashing is now reduced (also improved for on whole page reload / refresh).
<br />
Added `visibility: hidden` to certain elements until they have fully loaded. Means there is still a kind of flashing but I feel it looks nicer than elements moving about?
<br />
Removing the truncation timeouts has helped improve the flashing slightly I think - truncation is now applied as soon as the tree view is fully loaded rather than waiting 0.1 seconds. 
Without the timeouts, however, I was sometimes getting an issue where the heading wouldn't truncate. I've added padding-right while the component hydrates as this accounts for the change in text width, which was affecting the scrollHeight check on line 271 …
=> fix(canary-web-components): update tree view to improve FOUC

packages/react/src/component-tests/IcToast/IcToast.cy.tsx, packages/web-components/src/components/ic-toast/ic-toast.tsx, packages/web-components/src/components/ic-toast/test/basic/ic-toast.spec.ts
Added a description to auto dismiss toast loading indicator - an empty description was causing an a11y failure due to the loading indicator having an empty aria-label. The empty description was recently added to prevent the default aria-label of "Loading" being read out be screen readers - see [issue 1291](https://github.com/mi6/ic-ui-kit/issues/1291 ). Though the new description will be read out by screen readers, it prevents the a11y failure and the more relevant description should mean a better user experience.
#2402
=> 2402 a11y violation on auto dismiss toast

packages/web-components/src/components/ic-popover-menu/ic-popover-menu.stories.mdx, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx
fix for when ic-popover-menu sub-menu is open and the anchor button is clicked all menus close
To test go to the default storybook story, open the menu, click into a sub menu, click the anchor/menu button. All menus should close.
#2853
=> fix(web-components): ic-popover-menu close sub menus fix

packages/web-components/src/components/ic-dialog/ic-dialog.tsx
Removing " if default buttons are displayed" from the destructive prop description
#3100
=> fix(web-components): destructive prop description change

packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-react/src/stories/ic-data-table.stories.mdx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts, packages/canary-web-components/src/components/ic-data-table/test/basic/ic-data-table.spec.tsx
Provide access to the the click event in the Data Table action element, thereby allowing the event propagation to be stopped in individual data table action element click handlers.
This is to prevent IcDataTable rows from becoming selected when the row contains an IcButton in an action element and the button is clicked.
N/A
=> Prevent IcDataTable action element clicks from selecting the table row

.github/workflows/ic-ui-kit-release-v3-check.yml
replace references to regular develop with v3 develop
V3 Release workflow has been getting 422 failures - we think this is because it was referencing the develop branch.
This change to the script replaces those references with ones for v3.0.0/develop
=> ci(root): fix v3 release script

packages/react/src/stories/ic-dialog.mdx
Fix small mistake in dialog storybook which I've just noticed in PR #3218 - accidentally made a change to the wrong story
#2773
=> docs(react): fix small mistake in dialog storybook from PR 3218

packages/canary-react/src/component-tests/IcPaginationBar/IcPaginationBar.cy.tsx, packages/canary-react/src/component-tests/IcPaginationBar/IcPaginationBarTestData.tsx, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.stories.mdx, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx
ItemsPerPage has been updated to store the value when the user has explicitly set a value. This an update to totalItems which needs to be paginated to go from 'All' back to the itemsPerPage the user previously set.
#3223
=> [IcPaginationBar]: itemsPerPage select fix

.github/workflows/ic-ui-kit-release-check.yml, .github/workflows/ic-ui-kit-release-v3-check.yml
As a follow up to https://github.com/mi6/ic-ui-kit/pull/3156
improve the layout of the release check file, so it is easily readable on new lines. Additionally, the versions for react and web-components will be checked in canary/stable, including the v3 branches
#2765
=> ci(root): improve RELEASE_CHECK file layout and check versions match

packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx, packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
Add the ability to backspace through a date input to delete the date, using moveToPreviousInput after the last character has been deleted
#2244
=> 2244 ic date input improve deletion of full date via keyboard

packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.tsx
modified tree view to allow tree items to truncate on first render 
to test: 
- open storybook and go to truncated behavior, should emulate correct behavior without loading state
- 
#3171
=> fix(canary-web-components): truncation on first render

packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx, packages/web-components/src/components/ic-breadcrumb-group/test/basic/__snapshots__/ic-breadcrumb-group.spec.ts.snap, packages/web-components/src/components/ic-breadcrumb-group/test/basic/ic-breadcrumb-group.spec.ts
when the window is resized only one collapsed breadcrumb will render
=> fix(web-components): render only one collapsed breadcrumb when window is resized

packages/web-components/src/components/ic-loading-indicator/ic-loading-indicator.tsx
Fixed issue which I noticed was introduced by my TypeScript strict mode PR where circular indeterminate variant of the loading indicator was just showing as a complete circle.
(I think the v3 develop branch has not updated properly so isn't showing the bug - look at a build on another PR if not)
N/A
=> fix(web-components): fix circular loading indicator showing as complete circle

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.types.ts
Update navigation group so that two nav groups can't be open simultaneously
#3117
=> Navigation groups overlapping

packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.tsx, packages/web-components/src/components/ic-navigation-group/ic-navigation-group.types.ts
Update navigation group so that two nav groups can't be open simultaneously - cherry pick of #3385  
#3117
=> 3117 cherry pick

packages/canary-docs/docs.json, packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx, packages/canary-react/src/component-tests/IcDatePicker/IcDatePicker.cy.tsx, packages/canary-web-components/src/components.d.ts, packages/canary-web-components/src/components/ic-date-input/ic-date-input.stories.js, packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx, packages/canary-web-components/src/components/ic-date-input/readme.md, packages/canary-web-components/src/components/ic-date-input/test/basic/ic-date-input.spec.tsx, packages/canary-web-components/src/components/ic-date-picker/ic-date-picker.stories.js, packages/canary-web-components/src/components/ic-date-picker/ic-date-picker.tsx, packages/canary-web-components/src/components/ic-date-picker/readme.md, packages/canary-web-components/src/components/ic-date-picker/story-data.ts
Added a dateObject field to IcChange return detail, IcChange is now emitted after every section of input date is completed.
showInputs is an additional prop added so that any current implementations of datePicker or dateInput will not be affected by these changes rather setting showInputs to `true` will enable the emit on each field input
#3010
=> 3010 internal issue 2949   date input extend events to include string value of date input

packages/canary-web-components/package-lock.json
Using npm run audit:fix, bumped version of vite
=> chore(canary-web-components): audit fix - bump vite version

packages/web-components/src/components/ic-button/ic-button.css, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/components/ic-top-navigation/test/basic/__snapshots__/ic-top-navigation.spec.ts.snap
Updated the menu button on side navigation (shown on small screens) to have the correct hover and pressed state colours.
Fixed for both light and dark theme colours (see "Brand" story in React storybook). 
#3380
=> fix(web-components): update side nav menu button to correct hover and pressed colours

packages/web-components/src/components/ic-page-header/ic-page-header.tsx, packages/web-components/src/components/ic-page-header/test/basic/__snapshots__/ic-page-header.spec.ts.snap, packages/web-components/src/components/ic-page-header/test/basic/ic-page-header.spec.ts
change nav aria label to reflect slotted heading text content and remove redundant "navigation landmark"
Remove redundant "navigation landmark" from the <nav> aria label on the ic-page-header (used with slotted tabs).
The aria label is `myHeading page sections` using the heading prop if used or the slotted heading `textContent` if not.
Unit test added to ensure this aria label is correct when a slotted heading is used.
#3120
=> fix(web-components): fix ic-page-header nav element aria label

packages/canary-docs/CHANGELOG.md, packages/canary-react/CHANGELOG.md, packages/canary-web-components/CHANGELOG.md, packages/docs/CHANGELOG.md, packages/fonts/CHANGELOG.md, packages/nextjs/CHANGELOG.md, packages/react/CHANGELOG.md, packages/web-components/CHANGELOG.md
- Updates changelogs to include recent v2 releases
- Merges recent v3 alpha releases under 3.0.0 section
- Canary changelogs reverted back to individual releases rather than a single 3.0.0, as there have been no alpha packages for canary
- Tried to improve some messages where they were particularly vague
#3462
=> Changelog updates for v3 release

packages/web-components/src/components/ic-text-field/ic-text-field.tsx, packages/web-components/src/utils/constants.ts
There were three issues causing the max length validation message to not appear correctly.
1. The max length validation message was not appearing when pasting in more than maxLength characters. The validation message only appeared when another key was pressed (e.g. ArrowLeft) after the paste and data truncation had occurred.
2. The max length validation message was also appearing when it shouldn't have been, when maxLength chars had been entered into the textfield and then keyboard keys were pressed with don't affect the length of the input, e.g. ArrowLeft, Home, End, etc. If one of these keys has been pressed then then the keypress is ignored when working out whether to display the maxLength validation message.
3. Similar to 2. above, another case of the validation message appearing when …
=> V3 Fix appearance and non-appearance of length validation message in ic-textfield

packages/web-components/src/components/ic-dialog/ic-dialog.css
Removed a translate Y line in the ic-dialog.css that was forcing the dialog up off the screen on narrow widths and high zoom levels. See the ticket linked below for an example of the behaviour occuring, which I was able to replicate on Storybook and Stackblitz on Windows.
By removing this line, dialogs on narrow / zoomed in screens now fill the screen properly. 
Additionally `npm lint:fix` was run and added some linebreaks further up the file. 
##How to replicate
Compare [develop](https://mi6.github.io/ic-ui-kit/branches/develop/web-components/?path=/story/web-components-dialog--sizes) and [this branch](https://mi6.github.io/ic-ui-kit/branches/3432-zoom-icdialogs-are-cut-off-at-the-top/web-components/?path=/story/web-components-dialog--sizes)
1. click Launch Medium Dialog
2. Shrink the …
=> fix(web-components): dialogs at narrow width/high zoom fix

packages/canary-react/src/component-tests/IcTreeView/IcTreeView.cy.tsx, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.tsx
fix: arrow down moves to the next item when a child in tree view is expanded
=> 3358 ic tree view trying to arrow down doesn't move to the next item when a child in tree view is expanded

.github/ISSUE_TEMPLATE/report-bug.md, .github/ISSUE_TEMPLATE/suggest-guidance.md, .github/ISSUE_TEMPLATE/suggest-improvement.md, .github/ISSUE_TEMPLATE/suggest-new-component-pattern.md, .github/ISSUE_TEMPLATE/suggest-new-feature-existing-component.md, .github/ISSUE_TEMPLATE/suggest-process-improvement.md, .github/workflows/add-issue-urgency.yml
Updated issue templates to include a new “Urgency” section and added a workflow file. This workflow will run whenever an issue is created or edited, check what has been written in the “Urgency” section, and populate the urgency custom field with the appropriate value. (I will create the urgency custom field in our Project immediately after this PR has been merged).
Had to make the headings on the templates level 3 (###) because the issue parser only works with this heading level.
I will open an equivalent PR in the ic-design-system repo.
-----
See the [example issues I created in a test repo](https://github.com/GCHQ-Developer-847/test-repo/issues) ([associated actions](https://github.com/GCHQ-Developer-847/test-repo/actions)) which shows the urgency field, in the "Projects" section on the …
=> feat(root): issue urgency changes - add workflow and update templates

packages/docs/docs.json, packages/react/src/component-tests/IcBreadcrumb/IcBreadcrumb.cy.tsx, packages/web-components/src/components.d.ts, packages/web-components/src/components/ic-breadcrumb-group/ic-breadcrumb-group.tsx, packages/web-components/src/components/ic-breadcrumb-group/readme.md, packages/web-components/src/components/ic-breadcrumb-group/test/basic/__snapshots__/ic-breadcrumb-group.spec.ts.snap, packages/web-components/src/components/ic-breadcrumb-group/test/basic/ic-breadcrumb-group.spec.ts, packages/web-components/src/components/ic-breadcrumb/ic-breadcrumb.tsx, packages/web-components/src/components/ic-breadcrumb/ic-breadcrumb.types.ts, packages/web-components/src/components/ic-breadcrumb/readme.md, packages/web-components/src/components/ic-breadcrumb/test/basic/ic-breadcrumb.spec.ts, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx, packages/web-components/src/components/ic-text-field/ic-text-field.tsx, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/utils/helpers.ts
- Refactored ic-breadcrumb-group to set collapsed as mutable prop rather than relying on internal state.
- Now is able to accurately determine collapsed state and react accordingly when showing/hiding elements after clicking the expand button. (Was getting wrong value in `revertLastParentCollapsedBreadcrumb` so the hide class was being applied)
- Added test to cypress to cover this behaviour.
#3514
=> Updated breadcrumb group to not incorrectly apply hide class to last breadcrumb

packages/react/src/stories/ic-link.stories.js, packages/web-components/src/components/ic-link/ic-link.stories.js, packages/web-components/src/components/ic-link/ic-link.tsx, packages/web-components/src/components/ic-link/test/basic/__snapshots__/ic-link.spec.ts.snap, packages/web-components/src/components/ic-link/test/basic/ic-link.spec.ts
Update link download prop to handle boolean values correctly - remove download from <a> completely if download is false, and set download to "" if download is true
#2184
=> 2184 link download prop not working as expected

packages/react/src/component-tests/IcPopoverMenu/IcPopoverMenu.cy.tsx, packages/web-components/src/components/ic-menu-group/test/basic/__snapshots__/ic-menu-group.spec.ts.snap, packages/web-components/src/components/ic-menu-item/ic-menu-item.css, packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx, packages/web-components/src/components/ic-menu-item/test/basic/__snapshots__/ic-menu-item.spec.ts.snap, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.css, packages/web-components/src/components/ic-popover-menu/ic-popover-menu.tsx, packages/web-components/src/components/ic-popover-menu/test/basic/__snapshots__/ic-popover-menu.spec.ts.snap
- Refactor ic-menu-item to remove redundant `<li>` element
- Refactor ic-popover-menu to replace `<ul>` element with a `<div>`, allowing us to remove redundant styles that suppressed the normal list display behaviour. Renamed element's class selector too to be more readible. 
- Re-enable .checkA11y() calls in IcPopoverMenu.cy.tsx, and add an exception to the one that failed for 'nested-interactive' rule
This pull request doesn't resolve the accessibility failure reported by Accessibility Insights, my reasoning being that when manually testing with NVDA and Voiceover, the toggle variant menu items read out fine. My understanding is that we'd need to remove the ic-button from inside ic-menu-item altogether and that's a lot of bespoke code for a fix that, IMO, isn't necessary. Please do …
=> 2722 popover menu toggle variant menu items

packages/react/src/stories/ic-hero.stories.js, packages/web-components/src/components/ic-hero/ic-hero.css, packages/web-components/src/components/ic-hero/ic-hero.stories.js, packages/web-components/src/components/ic-hero/ic-hero.tsx, packages/web-components/src/components/ic-hero/test/basic/__snapshots__/ic-hero.spec.ts.snap
Add conditional styles to improve Hero component display when right-content is present on smaller screen widths.
The best comparison for this is the [develop Hero Brand story](https://mi6.github.io/ic-ui-kit/branches/develop/web-components/?path=/story/web-components-hero--brand) where if you shrink the screen width, the right-content overflows to the right. This PR modifies should address that 
#274
=> fix(web-components): improve Hero right-content display at small screen widths

packages/react/src/stories/ic-accordion.stories.js, packages/web-components/src/components/ic-accordion/ic-accordion.stories.js, packages/web-components/src/components/ic-accordion/ic-accordion.tsx
I've modified the Accordion Popover Content stories in Web Components and React to have their first accordion expanded on first render, where you can test that the popover (in this case an Ic-Select) does render outside the accordion. 
#2541
=> 2541 icselect dropdown not visible in expanded accordion

packages/web-components/src/components/ic-top-navigation/ic-top-navigation.css, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.tsx, packages/web-components/src/components/ic-top-navigation/test/basic/__snapshots__/ic-top-navigation.spec.ts.snap, packages/web-components/src/components/ic-top-navigation/test/basic/ic-top-navigation.spec.ts
- When a slotted app-icon is used and is a link, sets the tabindex to be -1 to skip it in the focus order. Focus now moves to the title-link wrapper which still lets the user navigate and click. Can still click the app-icon link.
- Added test to check the tabindex is being set. Added minor css to apply a pointer cursor even when the app-icon is not a link, since it can still be clicked due to it being contained by the title-link wrapper.
#1508
=> fix(web-components): fixed double tab on top-nav title

packages/canary-docs/docs.json, packages/canary-react/src/component-tests/IcTreeView/IcTreeView.cy.tsx, packages/canary-react/src/stories/ic-tree-view.stories.js, packages/canary-web-components/src/components.d.ts, packages/canary-web-components/src/components/ic-tree-item/ic-tree-item.tsx, packages/canary-web-components/src/components/ic-tree-item/readme.md, packages/canary-web-components/src/components/ic-tree-item/test/basic/ic-tree-item.spec.ts, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.stories.js, packages/canary-web-components/src/components/ic-tree-view/ic-tree-view.types.tsx
- Added new `treeItemId` prop to `ic-tree-item`. This allows developers to provide their own custom IDs.
- Added the Tree Item ID to the expanded emitted event.
#3670 
N/A
N/A
=> [ic-tree-item]: add prop for custom tree item id

packages/react/src/stories/ic-side-navigation.stories.js, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.stories.js, packages/web-components/src/components/ic-side-navigation/ic-side-navigation.tsx
Storybook changes:
- Added static/disableTopBarBehaviour/expanded props to react storybook
- Added playground story to web-components storybook
New behaviour:
- DisableTopBarBehaviour, when forcing the sideNav to display as normal, now acknowledges 'static' prop setting
#2806
=> 2806 side navigation static prop does not work with disabletopbarbehaviour

packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css
Added hover state to slotted nav items in top and side navigation.
Can be tested in the "React Router" stories
#3649
=> fix(web-components): add hover state to slotted nav items

packages/canary-docs/docs.json, packages/canary-react/src/component-tests/IcDataTable/IcDataTable.cy.tsx, packages/canary-react/src/stories/ic-data-table.stories.js, packages/canary-web-components/src/components/ic-data-table/ic-data-table.stories.js, packages/canary-web-components/src/components/ic-data-table/ic-data-table.tsx, packages/canary-web-components/src/components/ic-data-table/ic-data-table.types.tsx, packages/canary-web-components/src/components/ic-data-table/story-data.ts
- Added `disableAutoSort` to the data table column object to enable external sorting for specific columns
- Added tests and stories 
#3294
=> 3294 ic data table column specific disableautosort

packages/react/src/stories/ic-top-navigation.stories.js, packages/web-components/src/components/ic-badge/ic-badge.tsx, packages/web-components/src/components/ic-badge/test/basic/__snapshots__/ic-badge.spec.tsx.snap, packages/web-components/src/components/ic-badge/test/basic/ic-badge.spec.tsx, packages/web-components/src/components/ic-navigation-item/ic-navigation-item.css, packages/web-components/src/components/ic-navigation-item/ic-navigation-item.tsx, packages/web-components/src/components/ic-top-navigation/ic-top-navigation.stories.js
Update badges so that they appear inline with navigation items in top nav - to match behaviour in mobile mode of top nav.
Also make navigation items span the full width so that when hovered over, they're not different widths.
Tried to add a Cypress test but I couldn't get the mega menu to stay open for the screenshot. We don't seem to have any Cypress visual tests with the mega menu open so I assume it's an issue we've run into before.
#3527 & #3574
=> 3527 badge position on navigation items within top navigation mega menu

packages/react/src/component-tests/IcDialog/IcDialog.cy.tsx, packages/web-components/src/components/ic-alert/ic-alert.tsx
When the Cypress tests are run via GitHub workflows, one of the tests within IcAlert.cy.tsx is occasionally failing due to a type error and a few tests within IcDialog.cy.tsx are occasionally failing as the expected elements do not have focus. These changes attempt to prevent these failures and flakiness.
=> Fix flaky Cypress tests

packages/canary-web-components/src/components/ic-date-input/ic-date-input.tsx
Remove check for selectedDate !== 0 in date input as new Date("1970-01-01") is 0, so it was specifically excluding it
#3360
=> 3360 ic date input 01-01-1970 reported as an invalid date

packages/react/src/component-tests/IcDialog/IcDialog.cy.tsx, packages/react/src/component-tests/IcDialog/IcDialogTestData.tsx, packages/react/src/stories/ic-dialog.stories.js, packages/web-components/src/components/ic-dialog/ic-dialog.stories.js, packages/web-components/src/components/ic-dialog/ic-dialog.tsx
Fixes issue where unselected radio options did not receive focus on dialog
#3724
=> 3724 radio focus on dialog

packages/web-components/src/global/variables.css, packages/web-components/src/patterns/z-index.stories.js
- Increase z-index for `IcSkipLink` so it appears above `IcSideNavigation`
- Add `ic-skip-link` to component z-index story
#3716
=> fix(web-components): increase z-index for skip link

packages/react/src/component-tests/IcAlert/IcAlert.cy.tsx
Noticed the IcAlert tests are still failing occasionally so created this PR to temporarily skip the problematic tests before investigating an actual fix, so as not to waste dev time with workflows having to be re-run.
=> test(react): add skip to IcAlert high contrast visual regression tests

packages/react/src/component-tests/IcAlert/IcAlert.cy.tsx
Added uncaught exception handler to high contrast mode IcAlert tests to prevent failure.
=> test(react): dealing with uncaught exception in IcAlert tests

packages/canary-docs/docs.json
Updated canary-docs.json file.
I have also reverted all commits we have made today which were attempts to fix the release (plus the release commit itself). You can compare the commits on this branch with develop to see: [this branch](https://github.com/mi6/ic-ui-kit/commits/fix-release-issues/) vs [develop](https://github.com/mi6/ic-ui-kit/commits/develop)
=> docs(canary-docs): update docs.json file

.gitattributes
To test: 
- Make sure your local git config is not overriding line endings by running
```
git config --global core.autocrlf false
git config --global core.eol lf
```
- Then run 
```
git rm --cached -r .
git reset --hard
```
It should update all files to have LF line endings.
For new clones of the project, this won't be necessary, it should just automatically use LF line endings.
#3774
=> 3774 differing white space in docs

packages/canary-react/src/component-tests/IcDateInput/IcDateInput.cy.tsx
Move the value for a future date in IcDateInput cypress tests far into the future rather than august this year
=> test(canary-react): move dateInput cy test future date back into the future

packages/react/src/stories/ic-checkbox.stories.js, packages/react/src/stories/ic-radio-group.stories.js, packages/web-components/src/components/ic-checkbox-group/ic-checkbox-group.stories.js, packages/web-components/src/components/ic-checkbox-group/test/basic/__snapshots__/ic-checkbox-group.spec.ts.snap, packages/web-components/src/components/ic-checkbox/ic-checkbox.css, packages/web-components/src/components/ic-checkbox/ic-checkbox.tsx, packages/web-components/src/components/ic-radio-group/ic-radio-group.stories.js, packages/web-components/src/components/ic-radio-group/ic-radio-group.tsx, packages/web-components/src/components/ic-radio-group/test/basic/__snapshots__/ic-radio-group.spec.ts.snap, packages/web-components/src/components/ic-radio-option/ic-radio-option.tsx
Added role=alert to radiobutton and checkboxes that announces the dynamicText information when the parent input is checked.
Bonus fix: Refactored radio group so that helper text reads to screenreaders
Tested with NVDA (reading the speechviewer) and with VO on Mac. 
#3898
Removed unrelated checklist items
=> fix(web-components): dynamic fields on Checkboxes/Radio Buttons and screenreaders

packages/canary-web-components/src/components/ic-date-input/ic-date-input.css, packages/canary-web-components/src/components/ic-time-input/ic-time-input.css
Added media query to set clear button svg to currentcolor in HCM for dateinput
Updated time-input to use "currentcolor" all lowercase, to make linter happy :) 
#3929
=> fix(canary-web-components): make date input clear button visible in HCM

packages/canary-docs/docs.json, packages/canary-react/src/component-tests/IcPaginationBar/IcPaginationBar.cy.tsx, packages/canary-web-components/src/components.d.ts, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.stories.js, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.tsx, packages/canary-web-components/src/components/ic-pagination-bar/ic-pagination-bar.types.ts, packages/canary-web-components/src/components/ic-pagination-bar/readme.md, packages/canary-web-components/src/components/ic-pagination-bar/test/basic/ic-pagination-bar.spec.ts
- Added logic to correctly set itemsPerPage when totalItems is updated
- Added `isUserAction` to IcItemsPerPageChange due to event trigger when totalItems updates itermPerPage selection
#3939 
N/A
N/A
N/A
=> [ic-pagination-bar]: itemsPerPage incorrect value on totalItems update fix
